import { Problem } from '@/types';

export const JHARKHAND_DISTRICTS = [
  'Ranchi',
  'Dhanbad',
  'East Singhbhum (Jamshedpur)',
  'Bokaro',
  'Hazaribagh',
  'Deoghar',
  'Giridih',
  'Ramgarh',
  'Gumla',
  'Latehar',
  'Khunti',
  'West Singhbhum (Chaibasa)',
  'Seraikela Kharsawan',
  'Dumka',
  'Palamu',
  'Garhwa',
  'Chatra',
  'Godda',
  'Sahebganj',
  'Pakur',
  'Jamtara',
  'Lohardaga',
  'Simdega',
  'Koderma',
];

export const INITIAL_PROBLEMS: Problem[] = [
  {
    id: 'pr-jh-001',
    trackingCode: 'JH-2026-WTR-8812',
    title: 'High Fluoride & Iron Contamination in Deep Borewells Across Karra Block',
    category: 'Water Resources',
    description:
      'Over 14 village primary schools and 8 Anganwadi centers in Karra block are reporting water samples with fluoride levels exceeding 3.8 mg/L (WHO standard max 1.5 mg/L). Children are displaying early symptoms of dental and skeletal fluorosis. Conventional domestic candle filters fail within 3 weeks due to severe ferric clogging. Urgent requirement for low-cost, regeneration-free bio-sorbent adsorption or low-pressure solar electro-coagulation units operable by rural panchayats.',
    location: {
      district: 'Khunti',
      block: 'Karra',
      villageOrArea: 'Govindpur & Mahil Gram Panchayat',
      pincode: '835227',
      latitude: 23.1842,
      longitude: 85.1294,
      formattedAddress: 'Karra Block, Khunti District, Jharkhand - 835227',
    },
    media: [
      {
        id: 'med-01',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80',
        name: 'water_sample_lab_report.jpg',
        size: '1.8 MB',
      },
      {
        id: 'med-02',
        type: 'document',
        url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        name: 'District_Water_Quality_Survey_Khunti.pdf',
        size: '3.4 MB',
      },
    ],
    status: 'In Progress',
    upvotes: 342,
    submittedBy: {
      id: 'usr-k-01',
      fullName: 'Sunil Munda',
      phone: '+91 98351 44219',
      district: 'Khunti',
      isVerified: true,
    },
    matchedInstitution: {
      name: 'BIT Mesra (Birla Institute of Technology)',
      type: 'University',
      leadResearcher: 'Dr. R. K. Dey, Dept. of Chemical & Environmental Engineering',
      department: 'Center for Water Technology & Sustainable Rural Solutions',
      projectTitle: 'Chitosan-Activated Laterite Hybrid Gravity Filtration Bed',
    },
    solutionSummary:
      'Engineers at BIT Mesra deployed a 400 L/hour pilot gravity-fed column using locally sourced red laterite clay activated with bio-derived chitosan. Tested fluoride levels dropped from 3.8 mg/L to 0.42 mg/L without electricity.',
    impactMetrics: 'Potable water restored for 1,200+ students and 450 rural households.',
    milestones: [
      {
        id: 'm-01-1',
        problemId: 'pr-jh-001',
        stage: 'Submitted',
        title: 'Issue Lodged by Citizen Panchayat Representative',
        description: 'Problem uploaded with district health clinic reports and water spectrophotometry readings.',
        timestamp: '12 Jan 2026, 10:30 AM',
        completed: true,
        officerName: 'Sunil Munda (Citizen)',
      },
      {
        id: 'm-01-2',
        problemId: 'pr-jh-001',
        stage: 'Under Review',
        title: 'Verified by District Nodal Officer & PHED',
        description: 'Field inspection confirmed severity index 9.2/10. Categorized as High Priority Civic Challenge.',
        timestamp: '15 Jan 2026, 03:15 PM',
        completed: true,
        officerName: 'A. K. Verma (District Nodal Officer, Khunti)',
      },
      {
        id: 'm-01-3',
        problemId: 'pr-jh-001',
        stage: 'Matched with Institution',
        title: 'Adopted by BIT Mesra Research Cell',
        description: 'MoE Innovation Cell matched problem with Dr. Dey’s lab under the SocioSolve Grant scheme.',
        timestamp: '28 Jan 2026, 11:00 AM',
        completed: true,
        institution: 'BIT Mesra',
      },
      {
        id: 'm-01-4',
        problemId: 'pr-jh-001',
        stage: 'In Progress',
        title: 'Field Prototype Testing in Govindpur Middle School',
        description: 'First 2 units installed on-site. Real-time sensor monitoring water quality daily.',
        timestamp: '14 Feb 2026, 04:45 PM',
        completed: true,
        institution: 'BIT Mesra & PHED Khunti',
      },
      {
        id: 'm-01-5',
        problemId: 'pr-jh-001',
        stage: 'Solution Implemented',
        title: 'Full Block Rollout & Gram Panchayat Handover',
        description: 'Scaling to all 14 schools upon 90-day continuous field validation approval.',
        timestamp: 'Expected Apr 2026',
        completed: false,
      },
    ],
    createdAt: '2026-01-12T10:30:00Z',
    updatedAt: '2026-02-14T16:45:00Z',
  },
  {
    id: 'pr-jh-002',
    trackingCode: 'JH-2026-AGR-4491',
    title: 'Post-Harvest Spoilage of Lac & Mahua Flowers Due to Uncontrolled Moisture',
    category: 'Agriculture',
    description:
      'Over 3,500 tribal forest-dwelling farmers in Gumla and Raidih blocks depend heavily on Kusmi Lac and seasonal Mahua collection. Due to unseasonal pre-monsoon rains and lack of clean drying infrastructure, nearly 38% of gathered produce develops Aspergillus fungal mold, causing catastrophic grade downgrades at haat bazars (loss of ₹140 per kg). Need solar thermal hybrid drying tunnels and automated moisture-sensing sorting boxes suited for off-grid forest clusters.',
    location: {
      district: 'Gumla',
      block: 'Raidih',
      villageOrArea: 'Kanshiram Toli & Bharno Border',
      pincode: '835232',
      latitude: 23.0418,
      longitude: 84.5422,
      formattedAddress: 'Raidih Block Forest Range, Gumla, Jharkhand - 835232',
    },
    media: [
      {
        id: 'med-03',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80',
        name: 'mahua_drying_spoilage_field.jpg',
        size: '2.1 MB',
      },
    ],
    status: 'Solution Implemented',
    upvotes: 489,
    submittedBy: {
      id: 'usr-g-02',
      fullName: 'Mangri Oraon',
      phone: '+91 94311 88402',
      district: 'Gumla',
      isVerified: true,
    },
    matchedInstitution: {
      name: 'Birsa Agricultural University (BAU), Kanke',
      type: 'University',
      leadResearcher: 'Prof. Alok Pandey & Team AGRI-TECH',
      department: 'Dept. of Agricultural Engineering & Non-Timber Forest Products',
      projectTitle: 'Smart Solar-Tunnel Polycarbonate Desiccant Dryer with IoT hygrometer',
    },
    solutionSummary:
      'Designed and deployed collapsible 500kg-batch parabolic solar dryers lined with black anodized aluminium and battery-backed ventilation fans. Drying time dropped from 6 days to 18 hours, eliminating mold completely.',
    impactMetrics: 'Average tribal household earnings increased by ₹14,200 per harvesting season across 12 SHGs.',
    milestones: [
      {
        id: 'm-02-1',
        problemId: 'pr-jh-002',
        stage: 'Submitted',
        title: 'Challenge Registered by Gumla Tribal SHG Federation',
        description: 'Detailed economic loss breakdown submitted with photos of degraded Lac crops.',
        timestamp: '02 Dec 2025, 09:15 AM',
        completed: true,
      },
      {
        id: 'm-02-2',
        problemId: 'pr-jh-002',
        stage: 'Under Review',
        title: 'Evaluated by State Tribal Welfare & Agriculture Cell',
        description: 'Categorized under High Economic Impact Challenge for Minor Forest Produce.',
        timestamp: '08 Dec 2025, 02:30 PM',
        completed: true,
      },
      {
        id: 'm-02-3',
        problemId: 'pr-jh-002',
        stage: 'Matched with Institution',
        title: 'Assigned to BAU Kanke Agri-Engineering Labs',
        description: 'Grant sanctioned by MoE Innovation Cell & Jharkhand State Livelihood Mission.',
        timestamp: '20 Dec 2025, 11:45 AM',
        completed: true,
        institution: 'Birsa Agricultural University',
      },
      {
        id: 'm-02-4',
        problemId: 'pr-jh-002',
        stage: 'In Progress',
        title: '5 Prototype Solar Dryers Installed in Raidih & Sisai',
        description: 'Farmer Producer Companies trained on loading, IoT moisture monitoring, and packaging.',
        timestamp: '18 Jan 2026, 01:20 PM',
        completed: true,
        institution: 'BAU Kanke',
      },
      {
        id: 'm-02-5',
        problemId: 'pr-jh-002',
        stage: 'Solution Implemented',
        title: 'Commercial SHG Handover & State Procurement Linkage',
        description: 'TRIFED approved Grade-A certified packaging protocol developed by BAU researchers.',
        timestamp: '08 Feb 2026, 05:00 PM',
        completed: true,
        institution: 'BAU Kanke & TRIFED Jharkhand',
      },
    ],
    createdAt: '2025-12-02T09:15:00Z',
    updatedAt: '2026-02-08T17:00:00Z',
  },
  {
    id: 'pr-jh-003',
    trackingCode: 'JH-2026-ENV-9021',
    title: 'Human-Elephant Conflict & Crop Raiding Along Dalma Wildlife Sanctuary Corridor',
    category: 'Environment',
    description:
      'Herd movements from Dalma Wildlife Sanctuary into fringe paddy cultivation in Bodam and Patamda blocks result in frequent life risks, property destruction, and retaliation. Existing electric fencing is either severed or vandalized. Need non-invasive, solar-powered acoustic infrasound/seismic tripwire sensors connected to LoRa mesh networks that send automated multilingual SMS/siren alarms to village headmen and forest guards before herds breach residential perimeters.',
    location: {
      district: 'East Singhbhum (Jamshedpur)',
      block: 'Bodam',
      villageOrArea: 'Bangurda & Dimna Foothills',
      pincode: '832105',
      latitude: 22.8926,
      longitude: 86.2238,
      formattedAddress: 'Bodam Block, East Singhbhum, Jharkhand - 832105',
    },
    media: [
      {
        id: 'med-04',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80',
        name: 'dalma_corridor_crop_damage.jpg',
        size: '3.1 MB',
      },
    ],
    status: 'Matched with Institution',
    upvotes: 512,
    submittedBy: {
      id: 'usr-j-03',
      fullName: 'Ravi Shekhar Soren',
      phone: '+91 97092 11540',
      district: 'East Singhbhum (Jamshedpur)',
      isVerified: true,
    },
    matchedInstitution: {
      name: 'NIT Jamshedpur & IIT ISM Dhanbad (Joint Consortium)',
      type: 'NIT',
      leadResearcher: 'Dr. Sneha Ghosh (Dept. of ECE) & Prof. V. K. Jha',
      department: 'Embedded AI & Sensor Systems Group',
      projectTitle: 'Geo-Acoustic LoRa Elephant Early Warning Grid (GALE-Grid)',
    },
    solutionSummary:
      'Triangulating low-frequency ground vibrations (10-40 Hz) using buried seismic geophones with onboard edge-AI microcontrollers to identify elephant footfall signatures up to 800 meters away without false positives.',
    impactMetrics: 'Targeting 0 human casualties and 75% reduction in crop trampling across 8 villages.',
    milestones: [
      {
        id: 'm-03-1',
        problemId: 'pr-jh-003',
        stage: 'Submitted',
        title: 'Emergency Issue Raised by Joint Gram Sabha Bodam',
        description: 'Supported by forest range report documenting 19 intrusion incidents in 60 days.',
        timestamp: '18 Jan 2026, 11:20 AM',
        completed: true,
      },
      {
        id: 'm-03-2',
        problemId: 'pr-jh-003',
        stage: 'Under Review',
        title: 'Endorsed by Divisional Forest Officer (DFO) Dalma',
        description: 'Field mapped GPS hotspots and designated 4 corridor choke points.',
        timestamp: '25 Jan 2026, 04:10 PM',
        completed: true,
      },
      {
        id: 'm-03-3',
        problemId: 'pr-jh-003',
        stage: 'Matched with Institution',
        title: 'R&D Sanctioned to NIT Jamshedpur & IIT ISM Dhanbad',
        description: 'Formal MoU signed under Jharkhand Science & Technology Council.',
        timestamp: '05 Feb 2026, 02:00 PM',
        completed: true,
        institution: 'NIT Jamshedpur',
      },
      {
        id: 'm-03-4',
        problemId: 'pr-jh-003',
        stage: 'In Progress',
        title: 'Sensor Hardware Fabrication & Edge-AI Model Training',
        description: 'Training deep learning classifier on Dalma herd movement seismic patterns.',
        timestamp: 'Scheduled Mar 2026',
        completed: false,
      },
      {
        id: 'm-03-5',
        problemId: 'pr-jh-003',
        stage: 'Solution Implemented',
        title: 'Village Tower Sirens & Forest Ranger App Integration',
        description: 'Complete pilot deployment along 6 km perimeter.',
        timestamp: 'Scheduled May 2026',
        completed: false,
      },
    ],
    createdAt: '2026-01-18T11:20:00Z',
    updatedAt: '2026-02-05T14:00:00Z',
  },
  {
    id: 'pr-jh-004',
    trackingCode: 'JH-2026-HLT-2180',
    title: 'Lack of Cold-Chain & Diagnostic Connectivity for High-Risk Pregnancies in Netarhat Hills',
    category: 'Healthcare',
    description:
      'Remote hilly hamlets in Latehar and Mahuadanr blocks face severe delays in detecting pre-eclampsia and fetal distress among primitive tribal groups (Asur and Birhor). During monsoon landslides, road transit to Latehar District Hospital takes 4+ hours. Need a ruggedized, portable point-of-care ultrasound + automated maternal vitals kit operable by Sahiya workers, transmitting compressed telemetry via low-bandwidth satellite/RF link.',
    location: {
      district: 'Latehar',
      block: 'Mahuadanr',
      villageOrArea: 'Netarhat Plateau & Lodh Falls Hamlets',
      pincode: '822119',
      latitude: 23.4795,
      longitude: 84.2697,
      formattedAddress: 'Mahuadanr, Latehar District, Jharkhand - 822119',
    },
    media: [
      {
        id: 'med-05',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
        name: 'sub_center_health_clinic.jpg',
        size: '2.4 MB',
      },
    ],
    status: 'In Progress',
    upvotes: 628,
    submittedBy: {
      id: 'usr-l-04',
      fullName: 'Anita Asur (Sahiya Sathi)',
      phone: '+91 94709 33812',
      district: 'Latehar',
      isVerified: true,
    },
    matchedInstitution: {
      name: 'AIIMS Deoghar & BIT Sindri (Biomedical Engineering Unit)',
      type: 'University',
      leadResearcher: 'Dr. Priyaranjan Mahapatra (Dept. of Community Medicine)',
      department: 'Telemedicine & Digital Health Innovation Wing',
      projectTitle: 'Smart-Sahiya AI Diagnostic Backpack & Off-Grid Tele-Triage Hub',
    },
    solutionSummary:
      'Custom solar-rechargeable medical backpack containing Bluetooth non-invasive Hb scanner, automated BP cuff, ultrasound probe, and ruggedized Hindi voice-guided diagnostic tablet.',
    impactMetrics: 'Reduced emergency referral lag by 70%; zero maternal mortalities recorded in pilot cohort.',
    milestones: [
      {
        id: 'm-04-1',
        problemId: 'pr-jh-004',
        stage: 'Submitted',
        title: 'Identified through Village Health Sanitation & Nutrition Day',
        description: 'Submission accompanied by letter from 12 Sahiya health workers.',
        timestamp: '10 Nov 2025, 08:30 AM',
        completed: true,
      },
      {
        id: 'm-04-2',
        problemId: 'pr-jh-004',
        stage: 'Under Review',
        title: 'Approved by National Health Mission (NHM) Jharkhand',
        description: 'Validated as model innovation for Particularly Vulnerable Tribal Groups (PVTG).',
        timestamp: '19 Nov 2025, 03:00 PM',
        completed: true,
      },
      {
        id: 'm-04-3',
        problemId: 'pr-jh-004',
        stage: 'Matched with Institution',
        title: 'Project Adopted by AIIMS Deoghar Tele-Health Taskforce',
        description: 'Clinical trial protocols approved by institutional ethics board.',
        timestamp: '05 Dec 2025, 10:00 AM',
        completed: true,
        institution: 'AIIMS Deoghar',
      },
      {
        id: 'm-04-4',
        problemId: 'pr-jh-004',
        stage: 'In Progress',
        title: 'Deployment of 15 Diagnostic Backpacks to Mahuadanr Sahiyas',
        description: 'Live testing connecting Sahiya workers to AIIMS obstetrician tele-consultation panel.',
        timestamp: '10 Feb 2026, 11:30 AM',
        completed: true,
        institution: 'AIIMS Deoghar & BIT Sindri',
      },
      {
        id: 'm-04-5',
        problemId: 'pr-jh-004',
        stage: 'Solution Implemented',
        title: 'Statewide PVTG Health Mission Expansion',
        description: 'Budget provisioning for 200 backpacks across Latehar, Gumla, and Garhwa.',
        timestamp: 'Target June 2026',
        completed: false,
      },
    ],
    createdAt: '2025-11-10T08:30:00Z',
    updatedAt: '2026-02-10T11:30:00Z',
  },
  {
    id: 'pr-jh-005',
    trackingCode: 'JH-2026-PUB-5532',
    title: 'Digitization & OCR Bottleneck for Santhali (Ol Chiki) & Mundari Historical Land Titles',
    category: 'Public Administration',
    description:
      'Over 2.4 lakh historical land Khatiyan documents, Chota Nagpur Tenancy (CNT) Act registries, and Santhal Pargana Tenancy (SPT) records in Dumka and Deoghar are decaying. Existing commercial OCR engines only recognize English and Devanagari Hindi, completely failing on cursive Ol Chiki and archaic Kaithi scripts. Citizens face massive litigation delays and land disputes. Need an open-source Transformer-based OCR model tuned for Ol Chiki script and degraded manuscripts.',
    location: {
      district: 'Dumka',
      block: 'Dumka Sadar',
      villageOrArea: 'District Record Room & Sub-Division Registries',
      pincode: '814101',
      latitude: 24.2698,
      longitude: 87.2489,
      formattedAddress: 'Collectorate Campus, Dumka, Jharkhand - 814101',
    },
    media: [
      {
        id: 'med-06',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
        name: 'archaic_land_manuscript_scan.jpg',
        size: '4.2 MB',
      },
    ],
    status: 'In Progress',
    upvotes: 418,
    submittedBy: {
      id: 'usr-d-05',
      fullName: 'Shiblal Soren',
      phone: '+91 93081 72901',
      district: 'Dumka',
      isVerified: true,
    },
    matchedInstitution: {
      name: 'IIT (ISM) Dhanbad & Sido Kanhu Murmu University (SKMU)',
      type: 'IIT',
      leadResearcher: 'Prof. Chiranjeev Kumar & Tribal Linguistic Heritage Lab',
      department: 'Dept. of Computer Science & Engineering',
      projectTitle: 'ChikiVision: High-Accuracy Deep OCR for Indigenous Scripts',
    },
    solutionSummary:
      'Trained a custom Vision-Transformer model on 65,000 annotated Ol Chiki characters and degraded colonial stamp papers, achieving 96.4% character accuracy on damaged records.',
    impactMetrics: 'Processed 42,000 land deeds in 40 days; reduced citizen mutation verification time from 6 months to 48 hours.',
    milestones: [
      {
        id: 'm-05-1',
        problemId: 'pr-jh-005',
        stage: 'Submitted',
        title: 'Filed by Dumka Bar Association & Citizen Heritage Forum',
        description: 'Outlined legal gridlock affecting over 50,000 rural tribal families.',
        timestamp: '15 Dec 2025, 02:00 PM',
        completed: true,
      },
      {
        id: 'm-05-2',
        problemId: 'pr-jh-005',
        stage: 'Under Review',
        title: 'Endorsed by Department of Revenue & Land Reforms',
        description: 'Declared strategic governance priority under Digital India Bhashini initiative.',
        timestamp: '22 Dec 2025, 11:30 AM',
        completed: true,
      },
      {
        id: 'm-05-3',
        problemId: 'pr-jh-005',
        stage: 'Matched with Institution',
        title: 'Project Sanctioned to IIT ISM Dhanbad CSE AI Lab',
        description: 'Co-supervised with native Santhali linguists at SKMU Dumka.',
        timestamp: '04 Jan 2026, 04:00 PM',
        completed: true,
        institution: 'IIT ISM Dhanbad',
      },
      {
        id: 'm-05-4',
        problemId: 'pr-jh-005',
        stage: 'In Progress',
        title: 'Alpha Pipeline Deployed at Dumka Record Room Scanner Unit',
        description: 'Batch processing 1,000 pages per day with human-in-the-loop validation.',
        timestamp: '12 Feb 2026, 10:15 AM',
        completed: true,
        institution: 'IIT ISM Dhanbad & Revenue Dept',
      },
      {
        id: 'm-05-5',
        problemId: 'pr-jh-005',
        stage: 'Solution Implemented',
        title: 'Statewide Integration into Jharbhoomi Land Portal',
        description: 'Public API release enabling all 24 district portals to search Ol Chiki Khatiyans.',
        timestamp: 'Target May 2026',
        completed: false,
      },
    ],
    createdAt: '2025-12-15T14:00:00Z',
    updatedAt: '2026-02-12T10:15:00Z',
  },
  {
    id: 'pr-jh-006',
    trackingCode: 'JH-2026-ENE-7734',
    title: 'Frequent Coal-Dust Spark Short-Circuits & Inefficient Biomass Gasification in Katras Collieries',
    category: 'Energy',
    description:
      'High ambient coal dust and airborne particulate matter in Katras and Jharia mining clusters induce severe insulation breakdown in low-voltage distribution transformers and solar microgrid panels. Energy loss exceeds 29%. Need dust-repellent hydrophobic nanocoatings or self-cleaning electrostatic shields designed for harsh coalfield environments.',
    location: {
      district: 'Dhanbad',
      block: 'Katras',
      villageOrArea: 'Angarpathra & Sijua Colliery Peripheral Basti',
      pincode: '828113',
      latitude: 23.8124,
      longitude: 86.2891,
      formattedAddress: 'Katras Mining Zone, Dhanbad, Jharkhand - 828113',
    },
    media: [
      {
        id: 'med-07',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80',
        name: 'transformer_coal_dust_deposit.jpg',
        size: '1.9 MB',
      },
    ],
    status: 'Under Review',
    upvotes: 274,
    submittedBy: {
      id: 'usr-dh-06',
      fullName: 'Pradeep Kumar महतो',
      phone: '+91 94317 22094',
      district: 'Dhanbad',
      isVerified: true,
    },
    milestones: [
      {
        id: 'm-06-1',
        problemId: 'pr-jh-006',
        stage: 'Submitted',
        title: 'Submitted by Katras Residents Welfare Association',
        description: 'Power outage logs and equipment failure photographic evidence submitted.',
        timestamp: '01 Feb 2026, 05:40 PM',
        completed: true,
      },
      {
        id: 'm-06-2',
        problemId: 'pr-jh-006',
        stage: 'Under Review',
        title: 'Scrutiny by Jharkhand Urja Vikas Nigam Limited (JUVNL)',
        description: 'Engineering assessment in progress for academic R&D challenge matching.',
        timestamp: '09 Feb 2026, 02:20 PM',
        completed: true,
      },
      {
        id: 'm-06-3',
        problemId: 'pr-jh-006',
        stage: 'Matched with Institution',
        title: 'Awaiting Institutional Challenge Bidding',
        description: 'Open for proposals from engineering institutes.',
        timestamp: 'Pending',
        completed: false,
      },
      {
        id: 'm-06-4',
        problemId: 'pr-jh-006',
        stage: 'In Progress',
        title: 'Prototype Development & Lab Testing',
        description: 'Not started yet.',
        timestamp: 'Pending',
        completed: false,
      },
      {
        id: 'm-06-5',
        problemId: 'pr-jh-006',
        stage: 'Solution Implemented',
        title: 'Grid Hardening & Field Commissioning',
        description: 'Not started yet.',
        timestamp: 'Pending',
        completed: false,
      },
    ],
    createdAt: '2026-02-01T17:40:00Z',
    updatedAt: '2026-02-09T14:20:00Z',
  },
  {
    id: 'pr-jh-007',
    trackingCode: 'JH-2026-EDU-1092',
    title: 'Lack of Accessible STEM Science Kits in Regional Dialects for Kasturba Gandhi Balika Vidyalayas',
    category: 'Education',
    description:
      'Over 200 KGBV residential girls schools in rural Jharkhand lack experimental physics and biology lab apparatus designed for tactile, experiential learning in vernacular languages (Khortha, Ho, Nagpuri). Student conceptual retention in board examinations suffers. Need low-cost, open-hardware modular STEM kits accompanied by interactive audio-visual modules.',
    location: {
      district: 'Ranchi',
      block: 'Ormanjhi',
      villageOrArea: 'KGBV Ormanjhi & Kanke Clusters',
      pincode: '835219',
      latitude: 23.4827,
      longitude: 85.4789,
      formattedAddress: 'Ormanjhi Block, Ranchi, Jharkhand - 835219',
    },
    media: [
      {
        id: 'med-08',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80',
        name: 'kgbv_girls_classroom.jpg',
        size: '2.8 MB',
      },
    ],
    status: 'Solution Implemented',
    upvotes: 590,
    submittedBy: {
      id: 'usr-r-07',
      fullName: 'Pooja Kumari',
      phone: '+91 98357 66100',
      district: 'Ranchi',
      isVerified: true,
    },
    matchedInstitution: {
      name: 'Ranchi University & IIM Ranchi (CSR Incubation)',
      type: 'University',
      leadResearcher: 'Dr. Smita Keshri & Student Innovation Cell',
      department: 'Dept. of Physics & Education Innovation Cell',
      projectTitle: 'Jigyasa-Jharkhand: Low-Cost Vernacular Experiential STEM Lab in a Box',
    },
    solutionSummary:
      'Created 45 paper-microscopy, solar-circuit, and hydraulics experiment modules made from eco-friendly bamboo and recycled acrylic, with QR-coded vernacular video explainers.',
    impactMetrics: 'Dispatched to 84 KGBVs, reaching over 14,000 adolescent girls with 32% increase in STEM test scores.',
    milestones: [
      {
        id: 'm-07-1',
        problemId: 'pr-jh-007',
        stage: 'Submitted',
        title: 'Raised by Teacher Association Ranchi District',
        description: 'Detailed analysis of laboratory shortage submitted.',
        timestamp: '14 Oct 2025, 10:00 AM',
        completed: true,
      },
      {
        id: 'm-07-2',
        problemId: 'pr-jh-007',
        stage: 'Under Review',
        title: 'Approved by Jharkhand Education Project Council (JEPC)',
        description: 'Sanctioned under Samagra Shiksha Abhiyan innovation track.',
        timestamp: '22 Oct 2025, 03:30 PM',
        completed: true,
      },
      {
        id: 'm-07-3',
        problemId: 'pr-jh-007',
        stage: 'Matched with Institution',
        title: 'Partnered with Ranchi University Maker Space',
        description: 'Design workshops conducted with 60 rural science teachers.',
        timestamp: '10 Nov 2025, 11:00 AM',
        completed: true,
        institution: 'Ranchi University',
      },
      {
        id: 'm-07-4',
        problemId: 'pr-jh-007',
        stage: 'In Progress',
        title: 'Pilot Testing in 20 KGBVs across Ranchi and Khunti',
        description: 'Iterative improvements based on student feedback.',
        timestamp: '15 Dec 2025, 02:00 PM',
        completed: true,
        institution: 'Ranchi University & JEPC',
      },
      {
        id: 'm-07-5',
        problemId: 'pr-jh-007',
        stage: 'Solution Implemented',
        title: 'Statewide Distribution & Teacher Certification',
        description: 'Kits mass-manufactured by local rural SHG artisan clusters.',
        timestamp: '20 Jan 2026, 04:00 PM',
        completed: true,
        institution: 'Ranchi University & JEPC',
      },
    ],
    createdAt: '2025-10-14T10:00:00Z',
    updatedAt: '2026-01-20T16:00:00Z',
  },
  {
    id: 'pr-jh-008',
    trackingCode: 'JH-2026-URB-6302',
    title: 'Solid Waste & Heavy Metal Leachate in Harmu River Urban Catchment Basin',
    category: 'Urban Development',
    description:
      'Urban runoff and unsegregated municipal dumping into the Harmu river channel in Ranchi has created toxic sludge deposition, choking natural groundwater recharge aquifers and causing chronic monsoon inundation in low-lying bastis. Need automated floating bio-retention booms and modular decentralized vermi-filtration barriers.',
    location: {
      district: 'Ranchi',
      block: 'Ranchi Municipal Corporation',
      villageOrArea: 'Harmu Housing Colony & Kishoreganj',
      pincode: '834002',
      latitude: 23.3612,
      longitude: 85.3129,
      formattedAddress: 'Harmu River Basin, Ranchi, Jharkhand - 834002',
    },
    media: [
      {
        id: 'med-09',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?auto=format&fit=crop&w=800&q=80',
        name: 'harmu_drainage_sludge.jpg',
        size: '3.6 MB',
      },
    ],
    status: 'Under Review',
    upvotes: 310,
    submittedBy: {
      id: 'usr-r-08',
      fullName: 'Deepak Sinha',
      phone: '+91 94313 55902',
      district: 'Ranchi',
      isVerified: true,
    },
    milestones: [
      {
        id: 'm-08-1',
        problemId: 'pr-jh-008',
        stage: 'Submitted',
        title: 'Petition by Citizen Harmu Restoration Action Group',
        description: 'Comprehensive water testing and satellite imagery attached.',
        timestamp: '28 Jan 2026, 11:15 AM',
        completed: true,
      },
      {
        id: 'm-08-2',
        problemId: 'pr-jh-008',
        stage: 'Under Review',
        title: 'Technical Review by Urban Development & Housing Dept',
        description: 'Joint site visit scheduled with Ranchi Municipal Corporation engineers.',
        timestamp: '06 Feb 2026, 03:45 PM',
        completed: true,
      },
      {
        id: 'm-08-3',
        problemId: 'pr-jh-008',
        stage: 'Matched with Institution',
        title: 'Institutional Matching in Progress',
        description: 'Call for proposals open to civil & environmental engineering departments.',
        timestamp: 'Pending',
        completed: false,
      },
      {
        id: 'm-08-4',
        problemId: 'pr-jh-008',
        stage: 'In Progress',
        title: 'Pilot Filtration Installation',
        description: 'Pending',
        timestamp: 'Pending',
        completed: false,
      },
      {
        id: 'm-08-5',
        problemId: 'pr-jh-008',
        stage: 'Solution Implemented',
        title: 'Catchment Riverbank Beautification & Continuous Monitoring',
        description: 'Pending',
        timestamp: 'Pending',
        completed: false,
      },
    ],
    createdAt: '2026-01-28T11:15:00Z',
    updatedAt: '2026-02-06T15:45:00Z',
  },
  {
    id: 'pr-jh-009',
    trackingCode: 'JH-2026-RUR-3319',
    title: 'Lack of Cold Storage & Market Value Addition for Tussar Silk Weavers in Saraikela',
    category: 'Rural Livelihoods',
    description:
      'Over 2,200 traditional Tussar silk cocoon rearers in Kuchai and Kharsawan lose significant cocoon yield during unseasonal cocoon diapause due to ambient temperature fluctuations. Cocoon reeling manually on thigh-reels is slow and causes chronic musculoskeletal pain for women artisans. Need ergonomic motorized solar reeling-cum-twisting machines and climate-controlled community cocoon banks.',
    location: {
      district: 'Seraikela Kharsawan',
      block: 'Kuchai',
      villageOrArea: 'Kuchai Silk Cooperative & Kharsawan',
      pincode: '833216',
      latitude: 22.7145,
      longitude: 85.8712,
      formattedAddress: 'Kuchai Block, Seraikela Kharsawan, Jharkhand - 833216',
    },
    media: [
      {
        id: 'med-10',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=800&q=80',
        name: 'tussar_silk_weaving_kuchai.jpg',
        size: '2.5 MB',
      },
    ],
    status: 'Matched with Institution',
    upvotes: 435,
    submittedBy: {
      id: 'usr-s-09',
      fullName: 'Sumitra Mahato',
      phone: '+91 97714 88390',
      district: 'Seraikela Kharsawan',
      isVerified: true,
    },
    matchedInstitution: {
      name: 'NIFT Ranchi & National Institute of Foundry and Forge Technology (NIFFT Ranchi)',
      type: 'University',
      leadResearcher: 'Prof. Animesh Das (Mechatronics) & Dr. Ritu Sen',
      department: 'Dept. of Textile Tech & Mechanical Engineering',
      projectTitle: 'Solar Ergonomic Multi-Spindle Tussar Reeler & Precision Cocoon Vault',
    },
    solutionSummary:
      'Solar-powered, ergonomic 4-spindle reeling machine increasing yarn output by 350% with uniform denier quality suitable for export-grade organic silk certification.',
    impactMetrics: 'Daily income of women rearers projected to double from ₹220/day to ₹680/day.',
    milestones: [
      {
        id: 'm-09-1',
        problemId: 'pr-jh-009',
        stage: 'Submitted',
        title: 'Petition from Kuchai Silk Weavers Cooperative',
        description: 'Supported by documentation from Jharkhand Silk Board (JHARCRAFT).',
        timestamp: '05 Jan 2026, 09:30 AM',
        completed: true,
      },
      {
        id: 'm-09-2',
        problemId: 'pr-jh-009',
        stage: 'Under Review',
        title: 'Reviewed by Directorate of Handloom & Sericulture',
        description: 'Classified under High-Value Rural Livelihood Innovation priority.',
        timestamp: '14 Jan 2026, 02:15 PM',
        completed: true,
      },
      {
        id: 'm-09-3',
        problemId: 'pr-jh-009',
        stage: 'Matched with Institution',
        title: 'Adopted by NIFFT Ranchi & NIFT Collaborative Studio',
        description: 'Engineering prototype sanctioned with CSR innovation co-sponsorship.',
        timestamp: '02 Feb 2026, 11:30 AM',
        completed: true,
        institution: 'NIFFT Ranchi & NIFT',
      },
      {
        id: 'm-09-4',
        problemId: 'pr-jh-009',
        stage: 'In Progress',
        title: 'Field Validation of Machine Batch 1 with 30 Women Artisans',
        description: 'Ergonomic posture analysis and vibration damping optimization.',
        timestamp: 'Scheduled Mar 2026',
        completed: false,
      },
      {
        id: 'm-09-5',
        problemId: 'pr-jh-009',
        stage: 'Solution Implemented',
        title: 'Scale Deployment to 500 Weaver Households in Seraikela',
        description: 'Full cooperative cluster commissioning.',
        timestamp: 'Target June 2026',
        completed: false,
      },
    ],
    createdAt: '2026-01-05T09:30:00Z',
    updatedAt: '2026-02-02T11:30:00Z',
  },
  {
    id: 'pr-jh-010',
    trackingCode: 'JH-2026-ACC-8910',
    title: 'Lack of Universal Tactile Paving & Audio-Visual Signaling at Ranchi & Dhanbad Railway Hubs',
    category: 'Accessibility',
    description:
      'Visually impaired and orthopedically challenged commuters face severe hazards navigating between suburban bus stands, foot overbridges, and platform ticket concourses in major Jharkhand transit terminals. Missing tactile guide tiles, abrupt level drops, and non-functional acoustic pedestrian lights isolate differently-abled citizens. Need low-cost smart audio beacons and modular tactile guidance infrastructure.',
    location: {
      district: 'Ranchi',
      block: 'Ranchi Railway Station Area',
      villageOrArea: 'Chutia & Station Road Transit Concourse',
      pincode: '834001',
      latitude: 23.3518,
      longitude: 85.3421,
      formattedAddress: 'Station Road, Ranchi Junction, Jharkhand - 834001',
    },
    media: [
      {
        id: 'med-11',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80',
        name: 'station_accessibility_hazard.jpg',
        size: '2.9 MB',
      },
    ],
    status: 'In Progress',
    upvotes: 388,
    submittedBy: {
      id: 'usr-r-10',
      fullName: 'Arunav Sengupta (Jharkhand Divyangjan Manch)',
      phone: '+91 94311 00293',
      district: 'Ranchi',
      isVerified: true,
    },
    matchedInstitution: {
      name: 'BIT Mesra (Civil & IoT Systems Laboratory)',
      type: 'University',
      leadResearcher: 'Dr. Anand Kumar & Assistive Tech Lab',
      department: 'Dept. of Architecture & Civil Engineering',
      projectTitle: 'Divyang-Marg: Smart BLE-Beacon Navigation Grid with High-Contrast Tactile Tiles',
    },
    solutionSummary:
      'Installed 120 Bluetooth Low Energy (BLE) micro-beacons with free voice-guided navigation app in Hindi/English and recycled-rubber high-grip tactile directional pathways.',
    impactMetrics: 'Over 850 differently-abled travelers navigate Ranchi Junction daily with zero recorded slip or disorientation incidents.',
    milestones: [
      {
        id: 'm-10-1',
        problemId: 'pr-jh-010',
        stage: 'Submitted',
        title: 'Accessibility Audit Filed by Divyangjan Manch',
        description: 'Comprehensive photographic and safety hazard audit submitted.',
        timestamp: '11 Dec 2025, 03:00 PM',
        completed: true,
      },
      {
        id: 'm-10-2',
        problemId: 'pr-jh-010',
        stage: 'Under Review',
        title: 'Approved by South Eastern Railway (Ranchi Division) & State Social Welfare',
        description: 'Joint NOC granted for pilot installation.',
        timestamp: '20 Dec 2025, 11:00 AM',
        completed: true,
      },
      {
        id: 'm-10-3',
        problemId: 'pr-jh-010',
        stage: 'Matched with Institution',
        title: 'Adopted by BIT Mesra Assistive Tech Team',
        description: 'Hardware grant disbursed under MoE Innovation Cell.',
        timestamp: '08 Jan 2026, 02:30 PM',
        completed: true,
        institution: 'BIT Mesra',
      },
      {
        id: 'm-10-4',
        problemId: 'pr-jh-010',
        stage: 'In Progress',
        title: 'Phase 1 Concourse Beacon Installation Complete',
        description: 'Testing voice navigation app with 50 visually impaired volunteers.',
        timestamp: '16 Feb 2026, 04:00 PM',
        completed: true,
        institution: 'BIT Mesra & Railway Div',
      },
      {
        id: 'm-10-5',
        problemId: 'pr-jh-010',
        stage: 'Solution Implemented',
        title: 'Full Terminal Commissioning & Dhanbad Expansion',
        description: 'Replication scheduled for Dhanbad and Tatanagar junctions.',
        timestamp: 'Target Apr 2026',
        completed: false,
      },
    ],
    createdAt: '2025-12-11T15:00:00Z',
    updatedAt: '2026-02-16T16:00:00Z',
  },
];

export const SEED_PROBLEMS = INITIAL_PROBLEMS;
