# -*- coding: utf-8 -*-

English = [
"Auto drivers are refusing to enter our street because the road surface is full of deep potholes.",
"The footbridge connecting our colony to the market has had a broken railing for months, and pedestrians hug the opposite side out of caution.",
"Half the streetlight poles on our road have been standing dark for over a year even though the wiring itself looks fine.",
"The main road leading to the village has developed a stretch of craters so deep that two-wheelers regularly topple over during the rains.",
"Our bus stop shelter collapsed during last month's storm and has not been rebuilt, leaving commuters standing in the open.",
"A newly built flyover ramp has started showing cracks less than a year after it opened to traffic.",
"The footpath along the main road has been dug up for a utility project and never properly relaid, forcing pedestrians onto the road.",
"Parking near the market has become chaotic since the designated parking bays were never marked out as promised.",
"The pedestrian subway near the railway station floods with a few inches of water every time it rains, making it unusable.",
"A stretch of road resurfaced last year has already started crumbling at the edges due to poor construction quality.",
"The public parking structure near the bus stand has had its access ramp closed for repairs for over four months.",
"Speed breakers installed without proper markings on our road have caused several accidents at night.",
"The old municipal building in our ward has a portion of its roof that has been collapsing bit by bit for over a year.",
"Our colony road has no proper drainage slope, so every rain leaves puddles that take days to dry out and damage the road surface further.",
"The overpass connecting the two halves of our town has had one lane closed since a support pillar was flagged as unsafe.",
"Streetlight poles along our stretch have their wiring intact but the bulbs themselves have not been replaced in nearly a year, so the road stays dark.",
"The road divider near the school has been damaged in an accident and left unrepaired, causing traffic to swerve dangerously.",
"A pedestrian crossing near the market was painted over a construction site and no longer aligns with the actual crossing point.",
"The retaining wall along the hill road has developed visible cracks after this year's heavy rains.",
"Public benches at the town square have been broken for so long that most have simply been removed, leaving no seating at all.",
"The road connecting our village to the highway turns to slush within an hour of rain, cutting off vehicle access entirely.",
"A footbridge built to help residents cross the railway tracks safely has stairs so steep that elderly residents avoid using it.",
"The municipal market building's roof has been leaking for two monsoons straight, damaging vendor stalls underneath.",
"Our newly widened road narrows suddenly at one stretch where an encroachment was never cleared as planned.",
"The bus stand's waiting area has a caved-in section of flooring that has been fenced off but never actually repaired.",
"A crumbling culvert on the approach road to our village makes it risky for heavier vehicles to cross during the monsoon.",
"The pedestrian zone created near the market has been repeatedly encroached upon by parked vehicles with no enforcement in sight.",
"Cracks in the overhead pedestrian bridge near the college have widened noticeably since last year's inspection.",
"The public parking lot behind the civic centre has potholes so deep that several vehicles have suffered undercarriage damage.",
"A section of the compound wall around the municipal park collapsed during the storm and debris still blocks part of the walking path.",
"The road leading to our ward has been under 'ongoing repair' signage for over a year with no visible construction activity.",
"Multiple manhole covers on the arterial road have sunk below the road surface, creating a hazard for two-wheelers at night.",
"The bus bay outside our colony was never actually constructed despite being marked on the municipal plan for years.",
"A retaining wall failure near the river crossing has narrowed the usable width of the bridge approach significantly.",
"Traffic signals at the main junction have been non-functional for over three weeks, leading to daily congestion.",
"The footpath tiles near the market have come loose in several places, becoming a tripping hazard especially after dark.",
"Our neighbourhood's only pedestrian overbridge has been closed for structural assessment for nearly six months with no update.",
"The road surface near the industrial gate has deteriorated so badly that trucks now take an alternate residential route, damaging that road too.",
"A collapsed section of boundary railing along the elevated road has left a dangerous drop with no barrier in place.",
"The subway connecting the two market blocks has poor lighting and a broken drainage channel that floods after every rain.",
]

Hindi = [
"ऑटो चालक हमारी गली में आने से मना कर रहे हैं क्योंकि सड़क की सतह गहरे गड्ढों से भरी हुई है।",
"हमारी कॉलोनी को बाजार से जोड़ने वाले फुटब्रिज की रेलिंग महीनों से टूटी है, और पैदल यात्री सावधानी से दूसरी तरफ से गुजरते हैं।",
"हमारी सड़क के आधे स्ट्रीटलाइट खंभे एक साल से ज्यादा समय से अंधेरे पड़े हैं, हालांकि वायरिंग खुद ठीक दिखती है।",
"गांव तक जाने वाली मुख्य सड़क पर इतने गहरे गड्ढे बन गए हैं कि बारिश में अक्सर दोपहिया वाहन पलट जाते हैं।",
"पिछले महीने के तूफान में हमारे बस स्टॉप का शेड ढह गया और अभी तक दोबारा नहीं बनाया गया, यात्री खुले में खड़े रहते हैं।",
"एक नया बना फ्लाईओवर रैंप ट्रैफिक के लिए खुलने के एक साल के भीतर ही दरारें दिखाने लगा है।",
"मुख्य सड़क के किनारे का फुटपाथ एक यूटिलिटी प्रोजेक्ट के लिए खोदा गया था और कभी ठीक से दोबारा नहीं बिछाया गया, जिससे पैदल यात्रियों को सड़क पर चलना पड़ता है।",
"बाजार के पास पार्किंग अराजक हो गई है क्योंकि तय किए गए पार्किंग खांचे कभी वादे के मुताबिक चिह्नित नहीं किए गए।",
"रेलवे स्टेशन के पास पैदल यात्री सबवे हर बारिश में कुछ इंच पानी से भर जाता है, जिससे वह इस्तेमाल के लायक नहीं रहता।",
"पिछले साल फिर से बिछाई गई सड़क का एक हिस्सा खराब निर्माण गुणवत्ता के कारण किनारों से पहले ही टूटने लगा है।",
"बस स्टैंड के पास सार्वजनिक पार्किंग स्ट्रक्चर का एक्सेस रैंप मरम्मत के लिए चार महीने से ज्यादा समय से बंद है।",
"हमारी सड़क पर बिना उचित चिह्न के लगाए गए स्पीड ब्रेकर ने रात में कई दुर्घटनाओं का कारण बना है।",
"हमारे वार्ड की पुरानी नगरपालिका इमारत की छत का एक हिस्सा एक साल से ज्यादा समय से धीरे-धीरे ढह रहा है।",
"हमारी कॉलोनी की सड़क में उचित जल निकासी ढलान नहीं है, इसलिए हर बारिश में गड्ढे बनते हैं जो सूखने में दिन लगाते हैं और सड़क की सतह को और नुकसान पहुंचाते हैं।",
"हमारे शहर के दो हिस्सों को जोड़ने वाले ओवरपास की एक लेन बंद है क्योंकि एक सपोर्ट पिलर को असुरक्षित चिह्नित किया गया था।",
"हमारी सड़क के किनारे स्ट्रीटलाइट खंभों की वायरिंग तो सही है लेकिन बल्ब खुद लगभग एक साल से नहीं बदले गए, इसलिए सड़क अंधेरी रहती है।",
"स्कूल के पास सड़क का डिवाइडर एक दुर्घटना में क्षतिग्रस्त हो गया और मरम्मत नहीं हुई, जिससे ट्रैफिक खतरनाक ढंग से मुड़ता है।",
"बाजार के पास पैदल यात्री क्रॉसिंग एक निर्माण स्थल पर फिर से रंगी गई और अब वास्तविक क्रॉसिंग पॉइंट से मेल नहीं खाती।",
"पहाड़ी सड़क के किनारे रिटेनिंग वॉल में इस साल की भारी बारिश के बाद स्पष्ट दरारें आ गई हैं।",
"शहर चौक की सार्वजनिक बेंचें इतने लंबे समय से टूटी हुई थीं कि ज्यादातर को हटा ही दिया गया, अब वहां बैठने की कोई जगह नहीं बची।",
"हमारे गांव को हाईवे से जोड़ने वाली सड़क बारिश के एक घंटे के भीतर कीचड़ में बदल जाती है, जिससे वाहनों की पहुंच पूरी तरह कट जाती है।",
"रेलवे ट्रैक पार करने में निवासियों की मदद के लिए बना फुटब्रिज इतना खड़ी सीढ़ीदार है कि बुजुर्ग निवासी इसका इस्तेमाल करने से बचते हैं।",
"नगरपालिका बाजार भवन की छत लगातार दो मानसूनों से टपक रही है, जिससे नीचे विक्रेताओं के स्टॉल को नुकसान हो रहा है।",
"हमारी नई चौड़ी की गई सड़क अचानक एक हिस्से में संकरी हो जाती है जहां एक अतिक्रमण योजना के मुताबिक कभी साफ नहीं किया गया।",
"बस स्टैंड के प्रतीक्षा क्षेत्र में फर्श का एक धंसा हुआ हिस्सा है जिसे घेर दिया गया है लेकिन कभी वास्तव में मरम्मत नहीं की गई।",
"हमारे गांव की पहुंच सड़क पर एक जर्जर पुलिया है जो मानसून के दौरान भारी वाहनों के गुजरने को जोखिम भरा बना देती है।",
"बाजार के पास बनाए गए पैदल यात्री क्षेत्र पर बिना किसी प्रवर्तन के बार-बार खड़ी गाड़ियों का अतिक्रमण होता रहा है।",
"कॉलेज के पास ओवरहेड पैदल यात्री पुल में दरारें पिछले साल के निरीक्षण के बाद से स्पष्ट रूप से बढ़ी हैं।",
"सिविक सेंटर के पीछे सार्वजनिक पार्किंग स्थल में इतने गहरे गड्ढे हैं कि कई वाहनों के निचले हिस्से को नुकसान हुआ है।",
"नगरपालिका पार्क के चारों ओर की बाउंड्री वॉल का एक हिस्सा तूफान के दौरान ढह गया और मलबा अभी भी वॉकिंग पाथ का हिस्सा रोक रहा है।",
"हमारे वार्ड की ओर जाने वाली सड़क पर एक साल से ज्यादा समय से 'चल रहा मरम्मत कार्य' का बोर्ड लगा है लेकिन कोई निर्माण गतिविधि दिखाई नहीं देती।",
"मुख्य सड़क पर कई मैनहोल ढक्कन सड़क की सतह से नीचे धंस गए हैं, जिससे रात में दोपहिया वाहनों के लिए खतरा बन गया है।",
"हमारी कॉलोनी के बाहर बस बे कभी वास्तव में नहीं बनाई गई, हालांकि यह सालों से नगरपालिका योजना में चिह्नित है।",
"नदी क्रॉसिंग के पास रिटेनिंग वॉल फेल होने से पुल के एप्रोच की इस्तेमाल योग्य चौड़ाई काफी कम हो गई है।",
"मुख्य चौराहे पर ट्रैफिक सिग्नल तीन हफ्तों से ज्यादा समय से काम नहीं कर रहे, जिससे रोजाना जाम लगता है।",
"बाजार के पास फुटपाथ की टाइलें कई जगह ढीली हो गई हैं, जो खासकर अंधेरे में गिरने का खतरा बन गई हैं।",
"हमारे मोहल्ले का इकलौता पैदल यात्री ओवरब्रिज संरचनात्मक आकलन के लिए लगभग छह महीने से बंद है, कोई अपडेट नहीं।",
"औद्योगिक गेट के पास सड़क की सतह इतनी खराब हो गई है कि ट्रक अब वैकल्पिक रिहायशी रास्ता ले रहे हैं, जिससे वह सड़क भी खराब हो रही है।",
"ऊंची सड़क के किनारे बाउंड्री रेलिंग का एक ढहा हुआ हिस्सा एक खतरनाक ढलान छोड़ गया है, बिना किसी बैरियर के।",
"दो बाजार ब्लॉकों को जोड़ने वाले सबवे में रोशनी खराब है और एक टूटा जल निकासी चैनल है जो हर बारिश के बाद डूब जाता है।",
]

Hinglish = [
"Auto drivers hamari gali mein aane se mana kar rahe hain kyunki road surface deep potholes se bhara hua hai.",
"Hamari colony ko market se jodne wale footbridge ki railing mahinon se tooti hai, aur pedestrians caution se doosri side se guzarte hain.",
"Hamari sadak ke aadhe streetlight poles ek saal se zyada time se andhere pade hain, halanki wiring khud theek dikhti hai.",
"Village tak jaane wali main road par itne deep craters ban gaye hain ki baarish mein aksar two-wheelers palat jaate hain.",
"Pichle mahine ke storm mein hamare bus stop ka shelter dhah gaya aur abhi tak dobara nahi banaya gaya, commuters khule mein khade rehte hain.",
"Ek naya bana flyover ramp traffic ke liye khulne ke ek saal ke andar hi cracks dikhane laga hai.",
"Main road ke kinare ka footpath ek utility project ke liye khoda gaya tha aur kabhi theek se dobara nahi bichhaya gaya, jisse pedestrians ko road par chalna padta hai.",
"Market ke paas parking chaotic ho gayi hai kyunki tay kiye gaye parking bays kabhi promise ke mutabik marked nahi kiye gaye.",
"Railway station ke paas pedestrian subway har baarish mein kuch inch paani se bhar jaata hai, jisse woh use ke layak nahi rehta.",
"Pichle saal resurface ki gayi road ka ek hissa poor construction quality ki wajah se kinaron se pehle hi crumble hone laga hai.",
"Bus stand ke paas public parking structure ka access ramp repair ke liye chaar mahine se zyada time se band hai.",
"Hamari sadak par bina proper marking ke lagaye gaye speed breakers ne raat mein kayi accidents ka reason bana hai.",
"Hamare ward ki purani municipal building ki chhat ka ek hissa ek saal se zyada time se dheere-dheere gir raha hai.",
"Hamari colony road mein proper drainage slope nahi hai, isliye har baarish mein puddles bante hain jo sookhne mein din lagate hain aur road surface ko aur nuksaan pahunchate hain.",
"Hamare town ke do halves ko jodne wale overpass ki ek lane band hai kyunki ek support pillar ko unsafe flag kiya gaya tha.",
"Hamari sadak ke kinare streetlight poles ki wiring to sahi hai lekin bulbs khud lagbhag ek saal se change nahi hue, isliye road andheri rehti hai.",
"School ke paas road ka divider ek accident mein damage ho gaya aur repair nahi hua, jisse traffic khatarnak tarike se moodta hai.",
"Market ke paas pedestrian crossing ek construction site par phir se paint ki gayi aur ab actual crossing point se match nahi karti.",
"Hill road ke kinare retaining wall mein is saal ki heavy baarish ke baad clear cracks aa gaye hain.",
"Town square ki public benches itne lambe time se tooti thi ki zyadatar ko hata hi diya gaya, ab wahan baithne ki koi jagah nahi bachi.",
"Hamare village ko highway se jodne wali road baarish ke ek ghante ke andar slush mein badal jaati hai, jisse vehicle access poori tarah cut ho jaata hai.",
"Railway tracks cross karne mein residents ki help ke liye bana footbridge itna steep hai ki elderly residents ise use karne se bachte hain.",
"Municipal market building ki chhat lagatar do monsoons se leak ho rahi hai, jisse neeche vendor stalls ko nuksaan ho raha hai.",
"Hamari nayi widened road achanak ek stretch mein narrow ho jaati hai jahan ek encroachment plan ke mutabik kabhi clear nahi kiya gaya.",
"Bus stand ke waiting area mein flooring ka ek caved-in section hai jise fence kar diya gaya hai lekin kabhi actually repair nahi kiya gaya.",
"Hamare village ki approach road par ek crumbling culvert hai jo monsoon ke dauran heavier vehicles ke cross karne ko risky bana deti hai.",
"Market ke paas banaya gaya pedestrian zone baar-baar parked vehicles se encroach ho raha hai, bina kisi enforcement ke.",
"College ke paas overhead pedestrian bridge mein cracks pichle saal ke inspection ke baad se clearly badhe hain.",
"Civic centre ke peeche public parking lot mein itne deep potholes hain ki kayi vehicles ke undercarriage ko nuksaan hua hai.",
"Municipal park ke chaaron taraf ki compound wall ka ek hissa storm ke dauran dhah gaya aur debris abhi bhi walking path ka hissa block kar raha hai.",
"Hamare ward ki taraf jaane wali road par ek saal se zyada time se 'ongoing repair' ka signage laga hai lekin koi construction activity dikhayi nahi deti.",
"Main road par kayi manhole covers road surface se neeche dhans gaye hain, jisse raat mein two-wheelers ke liye hazard ban gaya hai.",
"Hamari colony ke bahar bus bay kabhi actually construct nahi hui, halanki yeh saalon se municipal plan mein marked hai.",
"River crossing ke paas retaining wall failure se bridge ke approach ki usable width kaafi kam ho gayi hai.",
"Main junction par traffic signals teen hafton se zyada time se non-functional hain, jisse daily congestion ho raha hai.",
"Market ke paas footpath tiles kayi jagah loose ho gayi hain, jo khaaskar andhere mein tripping hazard ban gayi hain.",
"Hamare mohalle ka ikalauta pedestrian overbridge structural assessment ke liye lagbhag chhe mahine se band hai, koi update nahi.",
"Industrial gate ke paas road surface itni bigad gayi hai ki trucks ab alternate residential route le rahe hain, jisse woh road bhi damage ho rahi hai.",
"Elevated road ke kinare boundary railing ka ek collapsed section ek dangerous drop chhod gaya hai, bina kisi barrier ke.",
"Do market blocks ko jodne wale subway mein lighting poor hai aur ek broken drainage channel hai jo har baarish ke baad flood ho jaata hai.",
]
