# -*- coding: utf-8 -*-

English = [
"Power has been going out every evening around dinner time for the past two weeks without any announced schedule.",
"The transformer serving our lane blew out four days ago and there is still no word on when a replacement will arrive.",
"Voltage at our house fluctuates so badly that we have stopped running the refrigerator out of fear of damaging it.",
"Our electricity bill this month shows a reading nearly triple what the meter itself displays.",
"The new connection we applied for eight months ago is still pending, and we continue running on an unofficial line.",
"A live wire has been hanging low over the lane since last week's storm, and no lineman has come to fix it.",
"Load shedding in our area now runs for six hours a day, far longer than the two hours announced by the department.",
"The meter installed last year has been recording usage even on days when we know the connection was completely disconnected upstream.",
"Our streetlight pole itself is fine, but the underground cable feeding it has been cut since the roadwork, so it stays dark every night.",
"A transformer fire two streets away has left our entire block without power for the third day running.",
"Farmers in our area get electricity for irrigation pumps at unpredictable hours, often in the middle of the night.",
"The billing department has been sending notices for a connection that was disconnected and removed over a year ago.",
"Power cuts during exam season have made it difficult for students in our colony to study in the evenings.",
"The solar streetlight units installed last year have stopped charging properly and go dark within an hour of sunset.",
"Our request to shift the sanctioned load for a new borewell connection has been pending at the sub-station office for months.",
"A recurring fault at the local substation causes the power to trip almost every time it rains even slightly.",
"The electric pole outside our house is visibly tilted after the last storm and residents worry it could fall during the next one.",
"Our neighbourhood has had unannounced power cuts nearly every afternoon this month, disrupting work-from-home schedules.",
"The energy meter reading was taken from outside the gate without anyone actually checking the display, and the bill reflects an estimate far higher than usage.",
"A short circuit at the nearby junction box caused sparks that nearly started a fire before anyone responded.",
"The smart meter installed under the new scheme has been showing zero consumption for two months despite the household using power daily.",
"Our area's electricity supply has been suspended for hours at a stretch during the ongoing line maintenance, with no prior notice given.",
"Voltage drops so severely in the evening that even tube lights flicker and barely stay lit until the peak hours pass.",
"The transformer capacity for our expanding colony was never upgraded, so outages have become routine as more households connect.",
"Our application for a subsidised solar rooftop connection has been stuck at the discom office for over five months.",
"Power supply to the agricultural feeder line was cut mid-afternoon without notice, right during peak irrigation hours.",
"A faulty meter box has reportedly been overbilling several households on our street for the past two billing cycles.",
"The electricity department disconnected our supply over a disputed bill despite our having submitted proof of prior payment.",
"Repeated tripping of the local feeder has damaged two refrigerators in our lane this summer alone.",
"An exposed electrical junction near the community well has become a serious safety hazard, especially for children playing nearby.",
"Our request to shift an overhead line that runs dangerously close to a rooftop has been pending with the department for over a year.",
"The billing cycle for our connection appears to have skipped a month entirely, and the next bill arrived with an unexplained lump sum added.",
"During the last heatwave, power to our block was cut for nearly eight hours straight with no update from the helpline.",
"A downed line following heavy winds has been lying uncleared in the open field near our homes for four days now.",
"The new transformer installed after the last failure trips every evening once household load increases past a certain point.",
"Our colony's underground cabling project has been left half-finished, leaving several homes still connected through exposed overhead wires.",
"The energy department's helpline number has not been answered in three attempts over the past week regarding our outage.",
"A recurring low-voltage problem in our lane has damaged the motor of the community borewell twice this year.",
"Power restoration after the recent storm took the department nearly five days for our part of the village, far longer than surrounding areas.",
"The prepaid meter installed under the pilot scheme has been deducting balance at a rate that does not match our actual usage.",
]

Hindi = [
"पिछले दो हफ्तों से हर शाम खाने के समय के आसपास बिना किसी घोषित समय-सारणी के बिजली चली जाती है।",
"हमारी गली की ट्रांसफार्मर चार दिन पहले जल गई और अभी तक यह पता नहीं है कि बदली गई ट्रांसफार्मर कब आएगी।",
"हमारे घर में वोल्टेज इतना उतार-चढ़ाव करता है कि हमने फ्रिज चलाना बंद कर दिया है ताकि वह खराब न हो।",
"इस महीने हमारे बिजली बिल में रीडिंग मीटर पर दिखने वाली रीडिंग से लगभग तीन गुना ज्यादा दिखाई गई है।",
"आठ महीने पहले लगाया गया नया कनेक्शन अभी भी लंबित है, और हम अनौपचारिक लाइन पर काम चला रहे हैं।",
"पिछले हफ्ते के तूफान के बाद से गली में एक लाइव तार नीचे लटका हुआ है, और कोई लाइनमैन इसे ठीक करने नहीं आया।",
"हमारे इलाके में अब लोड शेडिंग रोजाना छह घंटे तक चलती है, जो विभाग द्वारा घोषित दो घंटे से कहीं ज्यादा है।",
"पिछले साल लगाया गया मीटर उन दिनों भी खपत दर्ज कर रहा है जब हमें पता है कि ऊपर की ओर कनेक्शन पूरी तरह डिस्कनेक्ट था।",
"हमारा स्ट्रीटलाइट खंभा तो ठीक है, लेकिन उसे बिजली देने वाली भूमिगत केबल सड़क के काम के बाद से कटी हुई है, इसलिए वह हर रात अंधेरा रहता है।",
"दो गलियां दूर ट्रांसफार्मर में आग लगने से हमारे पूरे ब्लॉक में लगातार तीसरे दिन बिजली गायब है।",
"हमारे इलाके के किसानों को सिंचाई पंप के लिए बिजली अप्रत्याशित समय पर मिलती है, अक्सर आधी रात को।",
"बिलिंग विभाग एक ऐसे कनेक्शन के लिए नोटिस भेज रहा है जो एक साल से ज्यादा पहले डिस्कनेक्ट करके हटाया जा चुका है।",
"परीक्षा के मौसम में बिजली कटौती ने हमारी कॉलोनी के छात्रों के लिए शाम को पढ़ाई करना मुश्किल बना दिया है।",
"पिछले साल लगाई गई सोलर स्ट्रीटलाइट यूनिट ठीक से चार्ज होना बंद हो गई हैं और सूर्यास्त के एक घंटे के भीतर बुझ जाती हैं।",
"नए बोरवेल कनेक्शन के लिए स्वीकृत लोड शिफ्ट करने का हमारा अनुरोध सब-स्टेशन कार्यालय में महीनों से लंबित है।",
"स्थानीय सब-स्टेशन में बार-बार आने वाली खराबी की वजह से थोड़ी सी भी बारिश होने पर बिजली लगभग हर बार ट्रिप हो जाती है।",
"पिछले तूफान के बाद हमारे घर के बाहर बिजली का खंभा साफ तौर पर झुका हुआ दिख रहा है और निवासियों को डर है कि अगली बार यह गिर सकता है।",
"इस महीने लगभग हर दोपहर हमारे मोहल्ले में बिना घोषणा के बिजली कटौती हो रही है, जिससे घर से काम करने का शेड्यूल बिगड़ रहा है।",
"एनर्जी मीटर की रीडिंग गेट के बाहर से ली गई बिना किसी के डिस्प्ले चेक किए, और बिल असली खपत से कहीं ज्यादा अनुमानित राशि दिखाता है।",
"पास के जंक्शन बॉक्स में शॉर्ट सर्किट से चिंगारियां निकलीं जिससे लगभग आग लग जाती, इससे पहले कि कोई प्रतिक्रिया दे पाता।",
"नई योजना के तहत लगाया गया स्मार्ट मीटर दो महीने से शून्य खपत दिखा रहा है जबकि घर में रोजाना बिजली इस्तेमाल हो रही है।",
"चल रहे लाइन रखरखाव के दौरान हमारे इलाके की बिजली आपूर्ति घंटों के लिए निलंबित रही, बिना किसी पूर्व सूचना के।",
"शाम को वोल्टेज इतना गिर जाता है कि ट्यूबलाइट भी झिलमिलाती हैं और पीक ऑवर बीतने तक मुश्किल से जलती रहती हैं।",
"हमारी बढ़ती कॉलोनी के लिए ट्रांसफार्मर की क्षमता कभी अपग्रेड नहीं की गई, इसलिए जैसे-जैसे और घर जुड़ रहे हैं, बिजली कटौती आम हो गई है।",
"सब्सिडी वाले सोलर रूफटॉप कनेक्शन के लिए हमारा आवेदन डिस्कॉम कार्यालय में पांच महीने से ज्यादा समय से अटका हुआ है।",
"कृषि फीडर लाइन में दोपहर के बीच बिना सूचना के बिजली काट दी गई, वह भी सिंचाई के पीक समय के दौरान।",
"एक खराब मीटर बॉक्स कथित तौर पर हमारी गली के कई घरों को पिछले दो बिलिंग चक्रों से ज्यादा बिल भेज रहा है।",
"बिजली विभाग ने विवादित बिल को लेकर हमारी आपूर्ति काट दी, जबकि हमने पहले के भुगतान का प्रमाण जमा किया था।",
"स्थानीय फीडर के बार-बार ट्रिप होने से इस गर्मी में हमारी गली में अकेले दो फ्रिज खराब हो चुके हैं।",
"सामुदायिक कुएं के पास एक खुला बिजली जंक्शन गंभीर सुरक्षा खतरा बन गया है, खासकर पास खेलने वाले बच्चों के लिए।",
"एक छत के बेहद नजदीक से गुजरने वाली खतरनाक ओवरहेड लाइन को शिफ्ट करने का हमारा अनुरोध विभाग में एक साल से ज्यादा समय से लंबित है।",
"हमारे कनेक्शन का बिलिंग चक्र पूरी तरह से एक महीना छोड़ गया लगता है, और अगला बिल बिना किसी स्पष्टीकरण के जोड़ी गई एकमुश्त राशि के साथ आया।",
"पिछली भीषण गर्मी के दौरान, हमारे ब्लॉक की बिजली लगातार लगभग आठ घंटे के लिए काट दी गई और हेल्पलाइन से कोई अपडेट नहीं मिला।",
"तेज हवाओं के बाद गिरी एक लाइन चार दिनों से हमारे घरों के पास खुले मैदान में बिना हटाए पड़ी है।",
"पिछली खराबी के बाद लगाया गया नया ट्रांसफार्मर हर शाम एक निश्चित सीमा से ज्यादा घरेलू लोड बढ़ते ही ट्रिप हो जाता है।",
"हमारी कॉलोनी की भूमिगत केबलिंग परियोजना आधी अधूरी छोड़ दी गई है, जिससे कई घर अभी भी खुली ओवरहेड तारों के जरिए जुड़े हैं।",
"पिछले हफ्ते हमारी बिजली गुल होने को लेकर तीन बार कोशिश करने पर भी ऊर्जा विभाग की हेल्पलाइन का जवाब नहीं मिला।",
"हमारी गली में बार-बार होने वाली लो-वोल्टेज समस्या ने इस साल दो बार सामुदायिक बोरवेल की मोटर को नुकसान पहुंचाया है।",
"हाल के तूफान के बाद हमारे गांव के हिस्से में बिजली बहाल होने में विभाग को लगभग पांच दिन लग गए, जो आस-पास के इलाकों से कहीं ज्यादा है।",
"पायलट योजना के तहत लगाया गया प्रीपेड मीटर हमारी वास्तविक खपत से मेल न खाने वाली दर से बैलेंस काट रहा है।",
]

Hinglish = [
"Pichle do hafton se har shaam khane ke time ke aas-paas bina kisi announced schedule ke bijli chali jaati hai.",
"Hamari gali ka transformer chaar din pehle blow ho gaya aur abhi tak koi word nahi hai ki replacement kab aayega.",
"Hamare ghar mein voltage itna fluctuate karta hai ki humne fridge chalana band kar diya hai taaki woh damage na ho.",
"Is mahine hamare electricity bill mein reading meter par dikhne wali reading se lagbhag teen guna zyada dikhayi gayi hai.",
"Aath mahine pehle apply kiya gaya new connection abhi bhi pending hai, aur hum unofficial line par chala rahe hain.",
"Pichle hafte ke storm ke baad se gali mein ek live wire neeche latka hua hai, aur koi lineman ise theek karne nahi aaya.",
"Hamare ilake mein ab load shedding roz chhe ghante tak chalti hai, jo department dwara announce ki gayi do ghante se kahin zyada hai.",
"Pichle saal lagaya gaya meter un dinon bhi usage record kar raha hai jab humein pata hai ki upar ki taraf connection poori tarah disconnect tha.",
"Hamara streetlight pole to theek hai, lekin use bijli dene wali underground cable roadwork ke baad se kati hui hai, isliye woh har raat andhera rehta hai.",
"Do galiyan door transformer mein aag lagne se hamare poore block mein lagatar teesre din bijli gayab hai.",
"Hamare ilake ke farmers ko irrigation pump ke liye bijli unpredictable time par milti hai, aksar aadhi raat ko.",
"Billing department ek aise connection ke liye notice bhej raha hai jo ek saal se zyada pehle disconnect karke hataya ja chuka hai.",
"Exam season mein power cuts ne hamari colony ke students ke liye shaam ko padhai karna mushkil bana diya hai.",
"Pichle saal lagayi gayi solar streetlight units theek se charge hona band ho gayi hain aur sunset ke ek ghante ke andar bujh jaati hain.",
"Naye borewell connection ke liye sanctioned load shift karne ka hamara request sub-station office mein mahinon se pending hai.",
"Local substation mein baar-baar aane wali kharabi ki wajah se thodi si bhi baarish hone par bijli lagbhag har baar trip ho jaati hai.",
"Pichle storm ke baad hamare ghar ke bahar bijli ka pole saaf taur par tilted dikh raha hai aur residents ko dar hai ki agli baar yeh gir sakta hai.",
"Is mahine lagbhag har afternoon hamare mohalle mein bina announcement ke power cut ho raha hai, jisse work-from-home schedule bigad raha hai.",
"Energy meter ki reading gate ke bahar se li gayi bina kisi ke display check kiye, aur bill actual usage se kahin zyada estimated amount dikhata hai.",
"Paas ke junction box mein short circuit se sparks nikle jisse lagbhag aag lag jaati, isse pehle ki koi react kar paata.",
"Nayi scheme ke tahat lagaya gaya smart meter do mahine se zero consumption dikha raha hai jabki ghar mein roz bijli use ho rahi hai.",
"Chal rahe line maintenance ke dauran hamare ilake ki electricity supply ghanton ke liye suspend rahi, bina kisi prior notice ke.",
"Shaam ko voltage itna gir jaata hai ki tubelights bhi flicker karti hain aur peak hours nikalne tak mushkil se jalti rehti hain.",
"Hamari badhti colony ke liye transformer ki capacity kabhi upgrade nahi ki gayi, isliye jaise-jaise aur ghar connect ho rahe hain, outages routine ho gaye hain.",
"Subsidised solar rooftop connection ke liye hamara application discom office mein paanch mahine se zyada time se atka hua hai.",
"Agricultural feeder line mein afternoon ke beech bina notice ke bijli kaat di gayi, woh bhi irrigation ke peak hours ke dauran.",
"Ek faulty meter box reportedly hamari gali ke kayi households ko pichle do billing cycles se zyada bill bhej raha hai.",
"Electricity department ne disputed bill ko lekar hamari supply kaat di, jabki humne pehle ke payment ka proof submit kiya tha.",
"Local feeder ke baar-baar trip hone se is summer mein hamari gali mein akele do fridge kharab ho chuke hain.",
"Community well ke paas ek exposed electrical junction serious safety hazard ban gaya hai, khaaskar paas khelne wale bachchon ke liye.",
"Ek roof ke bahut nazdeek se guzarne wali khatarnak overhead line ko shift karne ka hamara request department mein ek saal se zyada time se pending hai.",
"Hamare connection ka billing cycle poori tarah se ek mahina skip kar gaya lagta hai, aur agla bill bina kisi explanation ke jodi gayi lump sum amount ke saath aaya.",
"Pichli heatwave ke dauran, hamare block ki bijli lagatar lagbhag aath ghante ke liye kaat di gayi aur helpline se koi update nahi mila.",
"Tez hawaon ke baad giri ek line chaar dinon se hamare gharon ke paas khule maidan mein bina hataye padi hai.",
"Pichli kharabi ke baad lagaya gaya naya transformer har shaam ek certain limit se zyada household load badhte hi trip ho jaata hai.",
"Hamari colony ki underground cabling project aadhi adhuri chhod di gayi hai, jisse kayi ghar abhi bhi exposed overhead wires ke through connected hain.",
"Pichle hafte hamari bijli gul hone ko lekar teen baar koshish karne par bhi energy department ki helpline ka jawab nahi mila.",
"Hamari gali mein baar-baar hone wali low-voltage problem ne is saal do baar community borewell ki motor ko nuksaan pahunchaya hai.",
"Recent storm ke baad hamare gaon ke hisse mein power restoration mein department ko lagbhag paanch din lag gaye, jo aas-paas ke ilakon se kahin zyada hai.",
"Pilot scheme ke tahat lagaya gaya prepaid meter hamari actual usage se match na karne wali rate se balance kaat raha hai.",
]
