# -*- coding: utf-8 -*-

English = [
"The seeds distributed through the government scheme this season resulted in poor germination across most fields in our village.",
"Unseasonal hailstorms flattened nearly half the standing wheat crop, and the loss assessment team still has not visited.",
"The subsidised fertiliser meant for the sowing window arrived at the depot three weeks after most farmers had already sown.",
"A pest outbreak has been spreading through the cotton fields for two weeks and no agricultural officer has come to inspect it.",
"Farmers in our cluster are still waiting for the crop insurance payout from last year's flood damage.",
"The canal that feeds our fields has had almost no water flow for the past ten days during the most critical growth stage.",
"The mandi is refusing to procure our paddy at the announced support price, citing moisture content disputes.",
"Diesel pumps meant for irrigation have gone unused because the promised subsidy on fuel never came through this quarter.",
"A whitefly infestation has damaged the vegetable crop across several plots, and the extension office has not responded to calls.",
"The tractor provided under the equipment-sharing scheme has been under repair at the block office for four months.",
"Our soil testing samples were submitted five months ago and the reports still have not reached any farmer in the cluster.",
"The government seed store sold us treated seeds that turned out to be past their viable sowing period.",
"Sugarcane farmers in our area have not received payment from the mill for the last crushing season.",
"A sudden change in weather advisory came too late for us to protect the standing mustard crop from frost damage.",
"The borewell used for field irrigation collapsed and there is no support programme covering repair costs for farmers.",
"Locust movement was reported nearby, and despite repeated calls, no spraying team has been deployed to our fields.",
"The crop loan sanctioned before sowing has still not been disbursed, and the season is nearly over.",
"Our onion harvest is rotting in open storage because there is no cold storage facility accessible within a reasonable distance.",
"The agricultural extension officer assigned to our block has not visited a single farm this entire season.",
"Excess rainfall has waterlogged the paddy fields and the drainage channels meant for agricultural land have not been cleared in years.",
"The price offered at the procurement centre for our produce is far below what was announced for this season.",
"A batch of hybrid maize seed distributed under the scheme failed to sprout in over sixty percent of the plots we surveyed.",
"The irrigation department has not released water on schedule for the second crop cycle this year.",
"Farmers who lost their entire chilli crop to bacterial wilt are still waiting for the compensation promised after the survey.",
"The pesticide sprayed by a private vendor damaged an adjoining organic plot, and no one has taken responsibility.",
"Our request for a soil-moisture sensor kit under the precision farming pilot has been pending for over a year.",
"The weighbridge at the local mandi has reportedly been giving inconsistent readings, shortchanging farmers on payment.",
"A grasshopper swarm has been damaging groundnut fields and the pesticide stock at the cooperative store has run out.",
"The subsidy for drip irrigation equipment was approved on paper but the actual installation has been delayed for months.",
"Farmers growing turmeric this year say the government procurement centre has stopped accepting fresh stock without explanation.",
"The seed replacement programme skipped our village entirely this cycle despite our applications being submitted on time.",
"A delay in releasing water from the reservoir meant the transplanting window for paddy was missed by nearly two weeks.",
"Storage rats have destroyed a portion of grain kept at the cooperative godown due to poor pest control there.",
"The crop cutting experiment used to determine our insurance claim was conducted on a plot that was not representative of the actual damage.",
"Farmers were promised a demonstration plot for the new drought-resistant variety, but the seeds for it never arrived.",
"The veterinary support for bullocks used in tilling has been unavailable at our block office for the past two months.",
"A fungal disease has spread through the tomato crop this season and samples sent to the lab have had no response in weeks.",
"The kisan credit card renewal for several farmers in our village has been stuck at the bank branch for unclear reasons.",
"Our request to the horticulture department for grafted mango saplings has gone unanswered since the last planting season.",
"The rainfall this year came right after we sowed groundnut, and the subsidised drainage support promised under the scheme never materialised.",
]

Hindi = [
"इस मौसम में सरकारी योजना के तहत बांटे गए बीजों से हमारे गांव के अधिकतर खेतों में अंकुरण बहुत कमजोर रहा।",
"बेमौसम ओलावृष्टि ने खड़ी गेहूं की लगभग आधी फसल को गिरा दिया, और नुकसान का आकलन करने वाली टीम अभी तक नहीं आई।",
"बुवाई के समय के लिए मिलने वाला सब्सिडी वाला खाद डिपो में तीन हफ्ते देर से पहुंचा, जब तक ज्यादातर किसान बुवाई कर चुके थे।",
"कपास के खेतों में दो हफ्तों से कीट प्रकोप फैल रहा है और कोई कृषि अधिकारी निरीक्षण के लिए नहीं आया।",
"हमारे क्लस्टर के किसान अभी भी पिछले साल की बाढ़ से हुए नुकसान के फसल बीमा भुगतान का इंतजार कर रहे हैं।",
"हमारे खेतों तक पानी लाने वाली नहर में सबसे महत्वपूर्ण बढ़वार के समय पिछले दस दिनों से लगभग कोई प्रवाह नहीं है।",
"मंडी नमी की मात्रा को लेकर विवाद बताकर घोषित समर्थन मूल्य पर हमारा धान खरीदने से इनकार कर रही है।",
"सिंचाई के लिए दिए गए डीजल पंप बेकार पड़े हैं क्योंकि ईंधन पर वादा की गई सब्सिडी इस तिमाही में कभी नहीं आई।",
"सफेद मक्खी के प्रकोप ने कई खेतों में सब्जी की फसल को नुकसान पहुंचाया है, और विस्तार कार्यालय ने कॉल का जवाब नहीं दिया।",
"उपकरण-साझाकरण योजना के तहत मिला ट्रैक्टर चार महीने से ब्लॉक कार्यालय में मरम्मत के लिए पड़ा है।",
"हमारे मिट्टी परीक्षण के नमूने पांच महीने पहले जमा किए गए थे और रिपोर्ट अभी तक क्लस्टर के किसी किसान तक नहीं पहुंची।",
"सरकारी बीज भंडार ने हमें उपचारित बीज बेचे जो निकले तो बुवाई की व्यवहार्य अवधि से बाहर के थे।",
"हमारे इलाके के गन्ना किसानों को पिछले पेराई सीजन का भुगतान चीनी मिल से नहीं मिला है।",
"मौसम सलाह में अचानक बदलाव इतनी देर से आया कि हम खड़ी सरसों की फसल को पाले से नहीं बचा सके।",
"खेत की सिंचाई के लिए इस्तेमाल होने वाला बोरवेल ढह गया और किसानों के लिए मरम्मत लागत को कवर करने वाला कोई सहायता कार्यक्रम नहीं है।",
"आस-पास टिड्डी दल की सूचना मिली थी, और बार-बार कॉल करने के बावजूद हमारे खेतों में कोई छिड़काव टीम नहीं भेजी गई।",
"बुवाई से पहले स्वीकृत फसल ऋण अभी तक वितरित नहीं हुआ है, और मौसम लगभग खत्म हो चुका है।",
"हमारी प्याज की फसल खुले भंडारण में सड़ रही है क्योंकि उचित दूरी के भीतर कोई कोल्ड स्टोरेज सुविधा उपलब्ध नहीं है।",
"हमारे ब्लॉक में तैनात कृषि विस्तार अधिकारी इस पूरे मौसम में एक भी खेत पर नहीं गए।",
"अधिक बारिश से धान के खेत जलमग्न हो गए और कृषि भूमि के लिए बनी जल निकासी नालियां सालों से साफ नहीं की गई हैं।",
"खरीद केंद्र पर हमारी उपज के लिए दी जा रही कीमत इस मौसम के लिए घोषित कीमत से बहुत कम है।",
"योजना के तहत बांटे गए हाइब्रिड मक्का बीज के एक बैच में हमारे सर्वेक्षण किए गए साठ प्रतिशत से अधिक खेतों में अंकुरण नहीं हुआ।",
"सिंचाई विभाग ने इस साल दूसरी फसल चक्र के लिए समय पर पानी नहीं छोड़ा है।",
"जिन किसानों की पूरी मिर्च फसल जीवाणु मुरझान से बर्बाद हो गई, वे सर्वेक्षण के बाद वादा किए गए मुआवजे का अभी भी इंतजार कर रहे हैं।",
"एक निजी विक्रेता द्वारा छिड़का गया कीटनाशक बगल के जैविक खेत को नुकसान पहुंचा गया, और किसी ने जिम्मेदारी नहीं ली।",
"सटीक खेती पायलट के तहत मिट्टी-नमी सेंसर किट के लिए हमारा अनुरोध एक साल से ज्यादा समय से लंबित है।",
"स्थानीय मंडी में तौल कांटा कथित तौर पर असंगत रीडिंग दे रहा है, जिससे किसानों को भुगतान में नुकसान हो रहा है।",
"टिड्डा झुंड मूंगफली के खेतों को नुकसान पहुंचा रहा है और सहकारी दुकान में कीटनाशक का स्टॉक खत्म हो चुका है।",
"ड्रिप सिंचाई उपकरण की सब्सिडी कागज पर मंजूर हो गई लेकिन वास्तविक स्थापना महीनों से टल रही है।",
"इस साल हल्दी उगाने वाले किसानों का कहना है कि सरकारी खरीद केंद्र ने बिना कारण बताए ताजा स्टॉक लेना बंद कर दिया है।",
"बीज प्रतिस्थापन कार्यक्रम इस चक्र में हमारे गांव को पूरी तरह छोड़ गया जबकि हमारे आवेदन समय पर जमा किए गए थे।",
"जलाशय से पानी छोड़ने में देरी के कारण धान की रोपाई की अवधि लगभग दो हफ्ते चूक गई।",
"सहकारी गोदाम में खराब कीट नियंत्रण के कारण चूहों ने रखे अनाज का एक हिस्सा बर्बाद कर दिया।",
"हमारे बीमा दावे को तय करने के लिए किया गया क्रॉप कटिंग प्रयोग ऐसे खेत पर किया गया जो वास्तविक नुकसान का प्रतिनिधित्व नहीं करता था।",
"किसानों को नई सूखा-प्रतिरोधी किस्म के लिए प्रदर्शन खेत का वादा किया गया था, लेकिन उसके बीज कभी नहीं पहुंचे।",
"जुताई में इस्तेमाल होने वाले बैलों के लिए पशु चिकित्सा सहायता पिछले दो महीनों से हमारे ब्लॉक कार्यालय में उपलब्ध नहीं है।",
"इस मौसम में टमाटर की फसल में फफूंद रोग फैल गया है और लैब भेजे गए नमूनों का हफ्तों से कोई जवाब नहीं आया।",
"हमारे गांव के कई किसानों का किसान क्रेडिट कार्ड नवीनीकरण अस्पष्ट कारणों से बैंक शाखा में अटका हुआ है।",
"बागवानी विभाग को कलमी आम के पौधों के लिए हमारा अनुरोध पिछले रोपण मौसम से अनुत्तरित है।",
"मूंगफली बोने के तुरंत बाद इस साल बारिश हो गई, और योजना के तहत वादा की गई सब्सिडी वाली जल निकासी सहायता कभी नहीं मिली।",
]

Hinglish = [
"Is season sarkari scheme ke tahat baante gaye seeds se hamare village ke zyadatar kheton mein germination bahut kamzor raha.",
"Bemausam olawrishti ne khadi wheat crop ka lagbhag aadha hissa gira diya, aur loss assessment team abhi tak nahi aayi.",
"Buwai ke time ke liye milne wala subsidised fertiliser depot mein teen hafte late pahuncha, jab tak zyadatar farmers buwai kar chuke the.",
"Cotton ke kheton mein do hafton se pest outbreak fail raha hai aur koi agricultural officer inspection ke liye nahi aaya.",
"Hamare cluster ke farmers abhi bhi pichle saal ki flood se hue nuksaan ke crop insurance payout ka wait kar rahe hain.",
"Hamare kheton tak paani laane wali canal mein sabse important growth stage ke time pichle das dinon se lagbhag koi flow nahi hai.",
"Mandi moisture content ka dispute batakar announced support price par hamara paddy kharidne se mana kar rahi hai.",
"Sinchai ke liye diye gaye diesel pumps bekar pade hain kyunki fuel par promised subsidy is quarter mein kabhi nahi aayi.",
"Whitefly ke prakop ne kayi kheton mein vegetable crop ko nuksaan pahunchaya hai, aur extension office ne calls ka jawab nahi diya.",
"Equipment-sharing scheme ke tahat mila tractor chaar mahine se block office mein repair ke liye pada hai.",
"Hamare soil testing samples paanch mahine pehle submit kiye gaye the aur reports abhi tak cluster ke kisi farmer tak nahi pahunchi.",
"Sarkari seed store ne humein treated seeds beche jo nikle to buwai ki viable period se bahar ke the.",
"Hamare ilake ke sugarcane farmers ko pichle crushing season ka payment mill se nahi mila hai.",
"Weather advisory mein achanak badlaav itni der se aaya ki hum khadi mustard crop ko frost damage se nahi bacha paaye.",
"Field irrigation ke liye use hone wala borewell collapse ho gaya aur farmers ke liye repair cost cover karne wala koi support programme nahi hai.",
"Aas-paas locust movement report hua tha, aur baar-baar call karne ke bawajood hamare kheton mein koi spraying team nahi bheji gayi.",
"Buwai se pehle sanctioned crop loan abhi tak disburse nahi hua hai, aur season lagbhag khatam ho chuka hai.",
"Hamari onion harvest open storage mein sad rahi hai kyunki reasonable distance ke andar koi cold storage facility available nahi hai.",
"Hamare block mein assigned agricultural extension officer is poore season mein ek bhi farm par nahi gaye.",
"Zyada baarish se paddy fields waterlogged ho gaye aur agricultural land ke liye bani drainage channels saalon se saaf nahi ki gayi hain.",
"Procurement centre par hamari produce ke liye di ja rahi price is season ke liye announced price se bahut kam hai.",
"Scheme ke tahat baante gaye hybrid maize seed ke ek batch mein hamare survey kiye gaye saath percent se zyada plots mein sprout hi nahi hua.",
"Irrigation department ne is saal doosre crop cycle ke liye time par paani release nahi kiya hai.",
"Jin farmers ki poori chilli crop bacterial wilt se barbaad ho gayi, woh survey ke baad promise kiye gaye compensation ka abhi bhi wait kar rahe hain.",
"Ek private vendor dwara spray kiya gaya pesticide bagal ke organic plot ko nuksaan pahuncha gaya, aur kisi ne responsibility nahi li.",
"Precision farming pilot ke tahat soil-moisture sensor kit ke liye hamara request ek saal se zyada time se pending hai.",
"Local mandi ka weighbridge reportedly inconsistent readings de raha hai, jisse farmers ko payment mein nuksaan ho raha hai.",
"Grasshopper swarm groundnut ke kheton ko nuksaan pahuncha raha hai aur cooperative store mein pesticide ka stock khatam ho chuka hai.",
"Drip irrigation equipment ki subsidy paper par approve ho gayi lekin actual installation mahinon se delay ho raha hai.",
"Is saal turmeric ugane wale farmers ka kehna hai ki sarkari procurement centre ne bina reason bataye fresh stock lena band kar diya hai.",
"Seed replacement programme is cycle mein hamare village ko poori tarah skip kar gaya jabki hamare applications time par submit kiye gaye the.",
"Reservoir se paani release karne mein delay ki wajah se paddy transplanting ka window lagbhag do hafte miss ho gaya.",
"Cooperative godown mein kharab pest control ki wajah se chuhon ne rakhe anaaj ka ek hissa barbaad kar diya.",
"Hamare insurance claim decide karne ke liye kiya gaya crop cutting experiment aise plot par kiya gaya jo actual damage ko represent nahi karta tha.",
"Farmers ko naye drought-resistant variety ke liye demonstration plot ka wada kiya gaya tha, lekin uske seeds kabhi nahi pahunche.",
"Jutai mein use hone wale bailon ke liye veterinary support pichle do mahinon se hamare block office mein available nahi hai.",
"Is season tomato crop mein fungal disease fail gayi hai aur lab bheje gaye samples ka hafton se koi jawab nahi aaya.",
"Hamare village ke kayi farmers ka kisan credit card renewal unclear reasons ki wajah se bank branch mein atka hua hai.",
"Horticulture department ko grafted mango saplings ke liye hamara request pichle planting season se unanswered hai.",
"Groundnut bone ke turant baad is saal baarish ho gayi, aur scheme ke tahat promise ki gayi subsidised drainage support kabhi nahi mili.",
]
