# -*- coding: utf-8 -*-

English = [
"Workers on our MGNREGA site have not been paid for over two months despite the muster roll showing full attendance.",
"My job card lists only half the days I actually worked last season, and the remaining wages were never paid out.",
"The self-help group loan approved for our women's collective six months ago has still not been disbursed by the bank.",
"No work has been provided under the employment guarantee scheme in our panchayat for nearly three months, and no unemployment allowance has been paid either.",
"The skill training centre in our block promised a stitching course, but it shut down halfway through with no refund of the enrolment fee.",
"Our weavers' cooperative has not received payment for the last consignment supplied to the government emporium four months ago.",
"A poultry rearing subsidy approved under the livelihood mission for our group has been stuck at the block office since last winter.",
"The worksite for the road-building project under the rural employment scheme has no shade or drinking water despite it being mandatory.",
"My husband migrated to the city for work because local employment guarantee days ran out within the first quarter of the year.",
"The e-shram card registration camp promised for our village never actually arrived, leaving many labourers without documentation.",
"Wages for our self-help group's tailoring order from the district administration have been pending for over five months.",
"The Mudra loan application submitted for setting up a small dairy unit has been rejected twice without a clear reason given.",
"Our fishing cooperative's pond lease renewal has been delayed at the block office for nearly a year, halting our main income source.",
"The crèche mandated at our worksite for women labourers with infants has never actually been set up.",
"A batch of goats distributed under the livestock support scheme arrived sick, and several died within weeks with no compensation offered.",
"Our handicraft cluster's showroom allotted under the scheme has remained locked since the caretaker was transferred out.",
"Payments for work done under the rural roads programme are routed through an account that was closed over a year ago, and no one has corrected it.",
"The self-help group federation meeting that decides loan disbursement has not been convened in our block for over four months.",
"Migrant workers returning from the city were promised local job cards on priority, but the panchayat office says the quota has run out.",
"Our silk cocoon rearing unit under the sericulture scheme has been without the promised subsidy for the second season running.",
"The muster roll for our worksite reportedly lists names of people who never actually reported for work that week.",
"A cattle shed construction subsidy sanctioned for our dairy group has been pending disbursement for over eight months.",
"Our village's khadi weaving unit has not received raw cotton allocation for the third month running, halting all production.",
"The unemployment allowance we are entitled to when work is not provided has never once been paid despite repeated written applications.",
"A women's collective running a pickle-making unit has been waiting for its working capital loan for close to a year now.",
"The block-level livelihood mission office has not responded to our request for a market linkage tie-up for our handloom products.",
"Job cards for three families in our hamlet were rejected during the last renewal without any written reason provided.",
"Payment for a completed pond-deepening project under the employment scheme was withheld over a measurement dispute that has dragged on for months.",
"Our self-help group's bank account has been frozen due to a KYC mismatch, and the livelihood mission office has not helped resolve it.",
"The vocational training centre meant to certify masons under the skill development scheme has not conducted a single batch this year.",
"A subsidised piggery unit approved for a group of women in our village has been delayed because the shed construction fund never arrived.",
"Wages owed to workers who repaired the village pond under the guarantee scheme have been pending for nearly four months now.",
"The handloom cluster's electricity connection for power looms was disconnected over a billing dispute, halting work for the whole group.",
"Our cooperative dairy has not received the promised milk collection centre despite the site being marked out over a year ago.",
"A batch of sewing machines sanctioned for our tailoring group under the scheme arrived without the motors, making them unusable.",
"The block office has not updated our attendance on the employment guarantee portal for the last six weeks despite daily site work.",
"Our bamboo craft group's application for a raw material subsidy has been sitting unprocessed at the district office for over a year.",
"Women in our self-help group were asked to repay a loan they say was never actually disbursed to their group account.",
"The fair-price procurement centre for our handicraft products has stopped honouring the rates fixed under the government scheme.",
"Seasonal migration from our village has increased this year because guaranteed work under the rural employment scheme dried up by mid-season.",
]

Hindi = [
"हमारे मनरेगा साइट पर मजदूरों को दो महीने से ज्यादा समय से भुगतान नहीं मिला, जबकि मस्टर रोल में पूरी हाजिरी दिखाई गई है।",
"मेरे जॉब कार्ड में पिछले सीज़न में काम किए गए आधे दिन ही दर्ज हैं, बाकी दिनों की मजदूरी कभी नहीं मिली।",
"हमारे महिला समूह को छह महीने पहले मंजूर हुआ स्वयं सहायता समूह ऋण अभी तक बैंक से नहीं मिला है।",
"हमारी पंचायत में पिछले तीन महीने से रोजगार गारंटी योजना के तहत कोई काम नहीं मिला, और बेरोजगारी भत्ता भी नहीं दिया गया।",
"हमारे ब्लॉक के कौशल विकास केंद्र में सिलाई का कोर्स आधे में ही बंद कर दिया गया, बिना फीस लौटाए।",
"हमारी बुनकर सहकारी समिति को सरकारी एम्पोरियम में चार महीने पहले भेजे गए माल का भुगतान अभी तक नहीं मिला।",
"आजीविका मिशन के तहत हमारे समूह को मंजूर मुर्गीपालन सब्सिडी पिछली सर्दियों से ब्लॉक कार्यालय में अटकी हुई है।",
"सड़क निर्माण की मनरेगा साइट पर छाया और पीने का पानी नहीं है, जबकि यह अनिवार्य होना चाहिए।",
"मेरे पति शहर काम करने चले गए क्योंकि साल की शुरुआत में ही रोजगार गारंटी के दिन खत्म हो गए थे।",
"हमारे गांव में ई-श्रम कार्ड बनाने का कैंप कभी आया ही नहीं, जिससे कई मजदूर बिना दस्तावेज के रह गए।",
"जिला प्रशासन के सिलाई ऑर्डर का भुगतान हमारे स्वयं सहायता समूह को पांच महीने से नहीं मिला है।",
"डेयरी यूनिट लगाने के लिए दिया गया मुद्रा लोन आवेदन बिना स्पष्ट कारण बताए दो बार रिजेक्ट हो चुका है।",
"हमारी मछुआरा सहकारी समिति के तालाब पट्टे का नवीनीकरण एक साल से ब्लॉक कार्यालय में लंबित है, जिससे हमारी मुख्य आमदनी रुक गई है।",
"मनरेगा साइट पर शिशुओं वाली महिला मजदूरों के लिए अनिवार्य पालना घर कभी बनाया ही नहीं गया।",
"पशुधन योजना के तहत मिली बकरियां बीमार निकलीं और कुछ हफ्तों में ही कई मर गईं, कोई मुआवजा नहीं दिया गया।",
"योजना के तहत मिला हमारे शिल्प समूह का शोरूम केयरटेकर के तबादले के बाद से बंद पड़ा है।",
"ग्रामीण सड़क योजना के काम का भुगतान एक ऐसे खाते में भेजा जाता है जो एक साल पहले ही बंद हो चुका है, और कोई सुधार नहीं हुआ।",
"लोन वितरण तय करने वाली स्वयं सहायता समूह संघ की बैठक हमारे ब्लॉक में चार महीने से नहीं हुई।",
"शहर से लौटे प्रवासी मजदूरों को प्राथमिकता पर जॉब कार्ड देने का वादा हुआ था, पर पंचायत कार्यालय कहता है कोटा खत्म हो गया।",
"रेशम कीट पालन योजना के तहत हमारी यूनिट को लगातार दूसरे सीज़न में भी वादा की गई सब्सिडी नहीं मिली।",
"हमारे साइट के मस्टर रोल में उन लोगों के नाम भी दर्ज हैं जो उस हफ्ते काम पर आए ही नहीं थे।",
"हमारे डेयरी समूह को मंजूर पशु शेड निर्माण सब्सिडी आठ महीने से वितरण के लिए लंबित है।",
"हमारी खादी बुनाई इकाई को लगातार तीसरे महीने कपास का आवंटन नहीं मिला, जिससे पूरा उत्पादन रुक गया।",
"काम न मिलने पर हमें मिलने वाला बेरोजगारी भत्ता बार-बार लिखित आवेदन के बावजूद कभी नहीं दिया गया।",
"अचार बनाने वाली महिला समूह को कार्यशील पूंजी ऋण के लिए लगभग एक साल से इंतजार करना पड़ रहा है।",
"ब्लॉक स्तर के आजीविका मिशन कार्यालय ने हमारे हथकरघा उत्पादों के लिए बाजार संपर्क की मांग का जवाब नहीं दिया।",
"हमारे टोले के तीन परिवारों के जॉब कार्ड पिछले नवीनीकरण में बिना किसी लिखित कारण के रद्द कर दिए गए।",
"गारंटी योजना के तहत पूरे हुए तालाब गहरीकरण काम का भुगतान मापन विवाद की वजह से महीनों से रोका गया है।",
"हमारे स्वयं सहायता समूह का बैंक खाता केवाईसी मिसमैच के कारण फ्रीज कर दिया गया, आजीविका मिशन कार्यालय ने इसे सुलझाने में मदद नहीं की।",
"कौशल विकास योजना के तहत राजमिस्त्री प्रमाणित करने वाला प्रशिक्षण केंद्र इस साल एक भी बैच नहीं चला पाया।",
"गांव की महिलाओं के समूह के लिए मंजूर सुअर पालन इकाई शेड निर्माण के फंड न आने से अटकी हुई है।",
"गारंटी योजना के तहत गांव के तालाब की मरम्मत करने वाले मजदूरों की मजदूरी लगभग चार महीने से लंबित है।",
"हथकरघा समूह के पावरलूम का बिजली कनेक्शन बिलिंग विवाद के कारण काट दिया गया, जिससे पूरे समूह का काम रुक गया।",
"हमारी सहकारी डेयरी को वादा किया गया दूध संग्रहण केंद्र एक साल से चिह्नित स्थान पर भी नहीं बना।",
"सिलाई समूह को योजना के तहत मिलीं सिलाई मशीनें बिना मोटर के पहुंचीं, जिससे वे बेकार पड़ी हैं।",
"ब्लॉक कार्यालय ने पिछले छह हफ्तों से रोजगार गारंटी पोर्टल पर हमारी हाजिरी अपडेट नहीं की, जबकि रोज साइट पर काम हुआ।",
"हमारे बांस शिल्प समूह का कच्चा माल सब्सिडी आवेदन जिला कार्यालय में एक साल से बिना कार्रवाई के पड़ा है।",
"हमारे स्वयं सहायता समूह की महिलाओं से एक ऐसा ऋण चुकाने को कहा गया जो उनके समूह खाते में कभी आया ही नहीं।",
"हमारे शिल्प उत्पादों की उचित मूल्य खरीद केंद्र ने सरकारी योजना के तहत तय दरों पर खरीदना बंद कर दिया है।",
"इस साल हमारे गांव से मौसमी पलायन बढ़ गया क्योंकि रोजगार गारंटी योजना के तहत काम सीजन के बीच में ही खत्म हो गया।",
]

Hinglish = [
"Hamare MGNREGA site pe mazdooron ko do mahine se zyada time se payment nahi mila, jabki muster roll mein poori attendance dikhayi gayi hai.",
"Mere job card mein pichle season ke aadhe hi din darj hain, baaki dinon ki mazdoori kabhi nahi mili.",
"Hamare women's group ko chhe mahine pehle sanction hua SHG loan abhi tak bank se nahi mila hai.",
"Hamari panchayat mein pichle teen mahine se employment guarantee scheme ke under koi kaam nahi mila, aur berozgari bhatta bhi nahi diya gaya.",
"Hamare block ke skill training centre mein stitching course aadhe mein hi band kar diya gaya, bina fee wapas kiye.",
"Hamari weavers cooperative ko govt emporium mein chaar mahine pehle bheje gaye maal ka payment abhi tak nahi mila.",
"Livelihood mission ke under hamare group ko sanction hui poultry subsidy pichli sardiyon se block office mein atki hui hai.",
"Road construction wale MGNREGA site pe shade aur peene ka paani nahi hai, jabki yeh mandatory hona chahiye.",
"Mere husband shehar kaam karne chale gaye kyunki saal ki shuruaat mein hi employment guarantee ke din khatam ho gaye the.",
"Hamare gaon mein e-shram card banane wala camp kabhi aaya hi nahi, jisse kai mazdoor bina document ke reh gaye.",
"District administration ke stitching order ka payment hamare SHG ko paanch mahine se nahi mila hai.",
"Dairy unit lagane ke liye diya gaya Mudra loan application bina clear reason bataye do baar reject ho chuka hai.",
"Hamari fishing cooperative ke pond lease ka renewal ek saal se block office mein pending hai, jisse hamari main income ruk gayi hai.",
"MGNREGA site pe chhote bachon wali women labourers ke liye mandatory creche kabhi banaya hi nahi gaya.",
"Livestock scheme ke under mili bakriyan bimar nikli aur kuch hafton mein hi kai mar gayin, koi compensation nahi diya gaya.",
"Scheme ke under mila hamare craft group ka showroom caretaker ke transfer ke baad se band pada hai.",
"Rural roads scheme ke kaam ka payment ek aise account mein jaata hai jo ek saal pehle hi band ho chuka hai, aur koi correction nahi hua.",
"Loan disbursement decide karne wali SHG federation ki meeting hamare block mein chaar mahine se nahi hui.",
"Shehar se laute migrant workers ko priority pe job card dene ka wada hua tha, par panchayat office kehta hai quota khatam ho gaya.",
"Sericulture scheme ke under hamari unit ko lagatar dusre season mein bhi promised subsidy nahi mili.",
"Hamare site ke muster roll mein un logon ke naam bhi darj hain jo us hafte kaam pe aaye hi nahi the.",
"Hamare dairy group ko sanction hui cattle shed construction subsidy aath mahine se distribution ke liye pending hai.",
"Hamari khadi weaving unit ko lagatar teesre mahine cotton allocation nahi mila, jisse pura production ruk gaya.",
"Kaam na milne par milne wala berozgari bhatta baar-baar likhit application ke bawajood kabhi nahi diya gaya.",
"Pickle banane wale women's group ko working capital loan ke liye lagbhag ek saal se wait karna pad raha hai.",
"Block level livelihood mission office ne hamare handloom products ke liye market linkage ki demand ka jawab nahi diya.",
"Hamare tole ke teen parivaron ke job card pichle renewal mein bina kisi likhit reason ke reject kar diye gaye.",
"Guarantee scheme ke under complete hue pond deepening kaam ka payment measurement dispute ki wajah se mahinon se roka gaya hai.",
"Hamare SHG ka bank account KYC mismatch ki wajah se freeze kar diya gaya, livelihood mission office ne isse resolve karne mein madad nahi ki.",
"Skill development scheme ke under masons ko certify karne wala training centre is saal ek bhi batch nahi chala paaya.",
"Gaon ki mahilaon ke group ke liye sanction hui piggery unit shed construction fund na aane se atki hui hai.",
"Guarantee scheme ke under gaon ke pond ki repair karne wale mazdooron ki mazdoori lagbhag chaar mahine se pending hai.",
"Handloom group ke powerloom ka bijli connection billing dispute ki wajah se kaat diya gaya, jisse pure group ka kaam ruk gaya.",
"Hamari cooperative dairy ko promise kiya gaya milk collection centre ek saal se marked site pe bhi nahi bana.",
"Tailoring group ko scheme ke under mili sewing machines bina motor ke pahunchi, jisse woh bekar padi hain.",
"Block office ne pichle chhe hafton se employment guarantee portal pe hamari attendance update nahi ki, jabki roz site pe kaam hua.",
"Hamare bamboo craft group ka raw material subsidy application district office mein ek saal se bina kaarwaai ke pada hai.",
"Hamare SHG ki mahilaon se aisa loan chukane ko kaha gaya jo unke group account mein kabhi aaya hi nahi.",
"Hamare handicraft products ke fair-price procurement centre ne government scheme ke under fix rates pe kharidna band kar diya hai.",
"Is saal hamare gaon se seasonal migration badh gaya kyunki employment guarantee scheme ke under kaam season ke beech mein hi khatam ho gaya.",
]
