# -*- coding: utf-8 -*-

English = [
"Our school has had no teacher for mathematics since the last one retired in July, and none has been sent yet.",
"The mid-day meal at the government school has been the same watery dal for three weeks running.",
"My son's transfer certificate has been pending at the school office for over a month, delaying his admission elsewhere.",
"The roof of the classroom block leaks so badly that classes are shifted to the corridor every time it rains.",
"Despite the school being sanctioned two additional teachers this year, only one has actually reported for duty.",
"The government primary school in our hamlet has been running with a single teacher handling all five grades together.",
"Textbooks for the new academic year still have not arrived even though classes started six weeks ago.",
"The toilet block for girls at our village school has been locked since the tap connection broke last term.",
"Our daughter was left off the merit scholarship exam list at school even though she submitted her application well before the deadline.",
"The boundary wall around the school ground remains half-built, and stray cattle wander into the assembly area every morning.",
"A teacher at the upper primary school has reportedly not shown up for the last three weeks without any substitute arranged.",
"Results for the annual exam were supposed to come out in May, and there is still no update two months later.",
"The government school in our panchayat has no functioning electricity, so the computer lab sits unused all year.",
"My nephew was denied admission under the reserved quota despite meeting all the eligibility criteria on paper.",
"Uniforms promised free of cost under the scheme have not been distributed even though the term is almost over.",
"The library at the block-level school has been locked for over a year since the librarian's post fell vacant.",
"Children in our village walk nearly four kilometres to the nearest school because the promised bus service was never started.",
"A batch of new desks and benches sanctioned for the school has been sitting unused in a locked room for months.",
"The headmaster's post at our middle school has been vacant for over a year, leaving no one to sign urgent documents.",
"Smart class equipment installed under a special grant has not worked since the projector broke six months ago.",
"Our school inspection has not happened even once this academic year despite it being due every term.",
"The drinking water tank at the school ran dry last month and children now bring bottles from home.",
"A teacher assigned to our school for special needs education has never actually reported for duty.",
"My daughter's name was removed from the school rolls by mistake and reinstating it has taken over two months of visits.",
"The bridge course meant for dropout children in our village was announced but never actually started.",
"Exam papers for the district-level test were reportedly leaked, yet no re-examination has been announced.",
"The government school building was declared unsafe after last year's inspection, but classes are still being held there.",
"Fee waiver forms submitted for my son under the economically weaker section quota have been stuck at the school for two terms.",
"There is only one working blackboard for four classrooms that are separated only by a cloth partition.",
"The anganwadi attached to our school has had no worker posted since the last one was transferred out.",
"Our request for an additional section to reduce classroom crowding has been pending with the education department for a year.",
"Sports equipment sanctioned for the annual meet arrived after the event had already been cancelled for lack of the same equipment.",
"A private tuition centre has become unavoidable for most children in our colony because regular classes rarely happen on schedule.",
"The vocational training component promised alongside the regular curriculum was dropped without any explanation to parents.",
"Teachers at our school are frequently pulled for election and census duty, cutting the actual teaching days short each term.",
"My son's admission was delayed because the online portal kept rejecting his caste certificate for reasons the help desk could not explain.",
"The government school kitchen shed used for the mid-day meal collapsed partially last monsoon and has not been repaired.",
"Attendance registers at our school reportedly show full strength even on days when barely half the children were present.",
"The state board result for a batch of students was withheld over a fee discrepancy that predates their enrolment.",
"Night classes for adult literacy that were announced for our village never actually started despite volunteers being listed as ready.",
]

Hindi = [
"हमारे स्कूल में गणित पढ़ाने वाले शिक्षक जुलाई में सेवानिवृत्त हो गए थे, और अब तक कोई नया शिक्षक नहीं भेजा गया।",
"मिड-डे मील में पिछले तीन हफ्तों से बच्चों को केवल पतली दाल और चावल दिया जा रहा है।",
"मेरे बेटे का स्थानांतरण प्रमाण पत्र स्कूल कार्यालय में एक महीने से अटका हुआ है, जिससे दूसरे स्कूल में दाखिला रुका हुआ है।",
"कक्षा की छत से इतना पानी टपकता है कि बारिश के दिनों में बच्चों को बरामदे में बिठाना पड़ता है।",
"इस साल स्कूल को दो नए शिक्षक मिलने थे, लेकिन अभी तक केवल एक ही ड्यूटी पर आया है।",
"हमारे गांव के प्राथमिक स्कूल में एक ही शिक्षक पांचों कक्षाओं को एक साथ पढ़ाते हैं।",
"नए शैक्षणिक सत्र की किताबें छह हफ्ते बीत जाने के बाद भी बच्चों तक नहीं पहुंची हैं।",
"लड़कियों के शौचालय में पानी का कनेक्शन पिछले सत्र से खराब पड़ा है, इसलिए ताला लगा दिया गया है।",
"स्कूल में मेरिट छात्रवृत्ति परीक्षा की सूची में मेरी बेटी का नाम शामिल नहीं किया गया, जबकि उसने समय से पहले ही आवेदन कर दिया था।",
"स्कूल की चारदीवारी अधूरी पड़ी है, जिसकी वजह से हर सुबह आवारा मवेशी प्रांगण में घुस आते हैं।",
"उच्च प्राथमिक स्कूल के एक शिक्षक पिछले तीन हफ्तों से नदारद हैं और कोई विकल्प शिक्षक नहीं भेजा गया।",
"वार्षिक परीक्षा के नतीजे मई में आने थे, लेकिन दो महीने बाद भी कोई सूचना नहीं मिली।",
"हमारी पंचायत के सरकारी स्कूल में बिजली नहीं है, इसलिए कंप्यूटर लैब पूरे साल बंद रहती है।",
"मेरे भतीजे को सभी पात्रता शर्तें पूरी करने के बावजूद आरक्षित कोटे में दाखिला नहीं दिया गया।",
"योजना के तहत मुफ्त मिलने वाली वर्दी सत्र खत्म होने के करीब आने पर भी नहीं बांटी गई है।",
"ब्लॉक स्तर के स्कूल की लाइब्रेरी पिछले एक साल से बंद पड़ी है क्योंकि लाइब्रेरियन का पद खाली है।",
"हमारे गांव के बच्चे लगभग चार किलोमीटर पैदल चलकर स्कूल जाते हैं क्योंकि वादा की गई बस सेवा कभी शुरू ही नहीं हुई।",
"स्कूल के लिए मंजूर हुए नए डेस्क और बेंच महीनों से एक बंद कमरे में बिना इस्तेमाल के पड़े हैं।",
"मध्य विद्यालय में प्रधानाध्यापक का पद एक साल से खाली है, जिससे जरूरी कागजों पर हस्ताक्षर करने वाला कोई नहीं है।",
"विशेष अनुदान के तहत लगाई गई स्मार्ट क्लास की मशीन प्रोजेक्टर खराब होने के बाद से छह महीने से बंद है।",
"इस शैक्षणिक वर्ष में स्कूल का निरीक्षण एक बार भी नहीं हुआ, जबकि यह हर सत्र में होना चाहिए।",
"स्कूल की पानी की टंकी पिछले महीने सूख गई, अब बच्चे घर से बोतल में पानी लेकर आते हैं।",
"विशेष जरूरतों वाले बच्चों के लिए नियुक्त शिक्षक कभी ड्यूटी पर आए ही नहीं।",
"मेरी बेटी का नाम गलती से स्कूल के रजिस्टर से हटा दिया गया, और उसे दोबारा जुड़वाने में दो महीने से ज्यादा लग गए।",
"गांव के स्कूल छोड़ चुके बच्चों के लिए ब्रिज कोर्स की घोषणा हुई थी, लेकिन वह कभी शुरू ही नहीं हुआ।",
"जिला स्तर की परीक्षा का पेपर लीक होने की खबर आई, फिर भी दोबारा परीक्षा की कोई घोषणा नहीं हुई।",
"पिछले साल के निरीक्षण में सरकारी स्कूल की इमारत को असुरक्षित बताया गया था, फिर भी वहीं कक्षाएं चल रही हैं।",
"आर्थिक रूप से कमजोर वर्ग कोटे में मेरे बेटे की फीस माफी का फॉर्म दो सत्रों से स्कूल में अटका पड़ा है।",
"चार कक्षाओं के लिए सिर्फ एक ब्लैकबोर्ड है, और उन्हें केवल एक कपड़े के पर्दे से अलग किया गया है।",
"स्कूल से जुड़ी आंगनवाड़ी में पिछले कार्यकर्ता के तबादले के बाद से कोई नई नियुक्ति नहीं हुई।",
"कक्षा में भीड़ कम करने के लिए एक अतिरिक्त सेक्शन की हमारी मांग शिक्षा विभाग में एक साल से लंबित है।",
"वार्षिक खेल दिवस के लिए मंजूर हुआ खेल सामान आयोजन रद्द होने के बाद पहुंचा, वह भी उसी सामान की कमी के कारण रद्द हुआ था।",
"हमारी कॉलोनी के ज्यादातर बच्चों के लिए ट्यूशन सेंटर जरूरी हो गया है क्योंकि स्कूल में नियमित कक्षाएं शायद ही समय पर होती हैं।",
"नियमित पाठ्यक्रम के साथ वादा किया गया व्यावसायिक प्रशिक्षण अभिभावकों को बिना कोई कारण बताए हटा दिया गया।",
"हमारे स्कूल के शिक्षकों को अक्सर चुनाव और जनगणना ड्यूटी में भेज दिया जाता है, जिससे हर सत्र में पढ़ाई के दिन कम हो जाते हैं।",
"मेरे बेटे का दाखिला इसलिए अटका क्योंकि ऑनलाइन पोर्टल उसका जाति प्रमाण पत्र बार-बार रिजेक्ट कर रहा था, और हेल्प डेस्क कारण नहीं बता पाया।",
"मिड-डे मील बनाने वाला रसोईघर पिछले मानसून में आंशिक रूप से गिर गया था और अभी तक उसकी मरम्मत नहीं हुई।",
"हमारे स्कूल की हाजिरी रजिस्टर में कई बार पूरी उपस्थिति दिखाई जाती है, जबकि उस दिन आधे बच्चे भी मौजूद नहीं होते।",
"एक बैच के छात्रों का बोर्ड परिणाम फीस के एक पुराने विवाद की वजह से रोक दिया गया, जो उनके दाखिले से पहले का मामला था।",
"हमारे गांव में वयस्क साक्षरता के लिए रात्रि कक्षाएं शुरू करने की घोषणा हुई थी, लेकिन स्वयंसेवकों के तैयार रहने के बावजूद वे कभी शुरू नहीं हुईं।",
]

Hinglish = [
"Hamare school mein maths ke teacher retire hue the July mein, tab se koi naya teacher bheja hi nahi gaya.",
"Mid-day meal mein pichle teen hafton se bas patla dal aur chawal mil raha hai bachon ko.",
"Mere bete ka transfer certificate school office mein ek mahine se atka hai, dusre school mein admission rukta ja raha hai.",
"Classroom ki chhat se itna paani tapakta hai ki baarish mein bachon ko corridor mein bithana padta hai.",
"Is saal school ko do naye teachers milne the, par abhi tak sirf ek hi duty pe aaya hai.",
"Hamare gaon ke primary school mein ek hi teacher paanchon classes ko saath mein padhata hai.",
"Naye session ki kitabein chhe hafte ho gaye phir bhi bachon tak nahi pahunchi hain.",
"Girls ke toilet ka paani connection pichle session se hi kharab pada hai, isliye taala laga diya gaya.",
"School mein merit scholarship exam ki list mein meri beti ka naam include hi nahi kiya gaya, jabki usne deadline se pehle hi apply kar diya tha.",
"School ki boundary wall adhuri padi hai, isi wajah se roz subah aawara maveshi ground mein ghus aate hain.",
"Upper primary school ke ek teacher pichle teen hafton se nadaarad hain aur koi substitute nahi bheja gaya.",
"Annual exam ka result May mein aana tha, do mahine ho gaye abhi tak koi update nahi hai.",
"Hamari panchayat ke govt school mein bijli hi nahi hai, isliye computer lab saal bhar band rehta hai.",
"Mere bhatije ko saari eligibility conditions poori karne ke bawajood reserved quota mein admission nahi mila.",
"Scheme ke under free milne wali uniform session khatam hone ke kareeb aane par bhi nahi bati gayi hai.",
"Block level school ki library pichle ek saal se band padi hai kyunki librarian ka post khaali hai.",
"Hamare gaon ke bachche lagbhag chaar kilometer paidal chalke school jaate hain kyunki promised bus service kabhi shuru hi nahi hui.",
"School ke liye sanction hue naye desk aur bench mahinon se ek band kamre mein bina use ke pade hain.",
"Middle school mein headmaster ka post ek saal se khaali hai, isliye zaroori kaagzon pe sign karne wala koi nahi hai.",
"Special grant ke under lagayi gayi smart class projector kharab hone ke baad se chhe mahine se band hai.",
"Is academic year mein school ka inspection ek baar bhi nahi hua, jabki har session mein hona chahiye.",
"School ki paani ki tanki pichle mahine sookh gayi, ab bachche ghar se bottle mein paani leke aate hain.",
"Special needs bachon ke liye appoint kiya gaya teacher kabhi duty pe aaya hi nahi.",
"Meri beti ka naam galti se school register se hata diya gaya, use wapas jodne mein do mahine se zyada lag gaye.",
"Gaon ke dropout bachon ke liye bridge course ka announcement hua tha, par woh kabhi shuru hi nahi hua.",
"District level exam ka paper leak hone ki khabar aayi, phir bhi re-exam ka koi announcement nahi hua.",
"Pichle saal ke inspection mein govt school ki building ko unsafe bataya gaya tha, phir bhi wahi classes chal rahi hain.",
"EWS quota mein mere bete ki fee waiver ka form do session se school mein atka pada hai.",
"Chaar classrooms ke liye sirf ek blackboard hai, aur unhe sirf ek cloth partition se alag kiya gaya hai.",
"School se judi anganwadi mein pichle worker ke transfer ke baad se koi nayi appointment nahi hui.",
"Classroom mein crowding kam karne ke liye extra section ki hamari demand education department mein ek saal se pending hai.",
"Annual sports day ke liye sanction hua sports equipment event cancel hone ke baad pahuncha, wo bhi usi saaman ki kami ki wajah se cancel hua tha.",
"Hamari colony ke zyada tar bachon ke liye tuition center zaroori ho gaya hai kyunki regular classes shaayad hi time pe hoti hain.",
"Regular curriculum ke saath promise kiya gaya vocational training parents ko bina koi reason bataye hata diya gaya.",
"Hamare school ke teachers ko aksar election aur census duty mein bhej diya jaata hai, jisse har session mein padhai ke din kam ho jaate hain.",
"Mere bete ka admission isliye atka kyunki online portal uska caste certificate baar-baar reject kar raha tha, aur help desk reason nahi bata paaya.",
"Mid-day meal banane wala kitchen shed pichle monsoon mein aadha gir gaya tha aur abhi tak uski repair nahi hui.",
"Hamare school ke attendance register mein kai baar poori attendance dikhai jaati hai, jabki us din aadhe bachche bhi maujood nahi hote.",
"Ek batch ke students ka board result ek purane fee dispute ki wajah se rok diya gaya, jo unke admission se pehle ka mamla tha.",
"Hamare gaon mein adult literacy ke liye night classes shuru karne ka announcement hua tha, par volunteers ready hone ke bawajood woh kabhi shuru nahi hui.",
]
