# -*- coding: utf-8 -*-

English = [
"Thick black smoke from the brick kiln on the edge of our village settles over the fields every morning before sunrise.",
"The stream behind our colony has turned a strange grey colour since a new unit opened upstream last year.",
"Noise from the stone crushing unit runs well past midnight, and residents nearest to it can no longer sleep properly.",
"Dozens of old trees along our road were cut down last week without any public notice or replacement planting planned.",
"Ash from the nearby thermal plant settles on our terraces and vegetable patches every few days.",
"A tannery on the outskirts has reportedly been discharging untreated effluent directly into the river we use for irrigation.",
"The air near the industrial belt has become so thick some mornings that visibility drops to barely a hundred metres.",
"Illegal burning of plastic waste behind the market releases acrid smoke into our neighbourhood most evenings.",
"A patch of mangrove forest that protected our coastal hamlet from storm surges has been cleared for a private project.",
"The chemical smell from the factory two kilometres away has become strong enough to cause headaches among residents.",
"Fly ash from a nearby unit has been settling on crops in the fields closest to the boundary wall.",
"Groundwater near the industrial cluster has developed a strange odour that residents say started after a new plant began operations.",
"Continuous flaring from the gas processing unit lights up the night sky and the accompanying noise carries for kilometres.",
"A once-clear pond used by the village for generations has turned foul-smelling since a dyeing unit began operating nearby.",
"The hills behind our town have lost significant tree cover this year due to unregulated quarrying operations.",
"Fumes from an unregulated recycling unit in our neighbourhood have made the air noticeably harder to breathe in the evenings.",
"Fine dust from the cement plant settles on everything in our lane, and respiratory complaints among elderly residents have risen sharply.",
"An unauthorised dumping site near the riverbank has begun leaching a dark liquid into the water during heavy rain.",
"Migratory birds that used to stop at our wetland each winter have stopped coming since the water quality changed two years ago.",
"The paper mill's chimney releases a visible plume every night that settles as a fine residue on nearby rooftops by morning.",
"Excessive honking and unregulated loudspeaker use near the market has pushed noise levels well past what should be tolerable in a residential zone.",
"A quarry blasting schedule that was supposed to be limited to daytime hours has been running late into the evening, cracking walls in nearby homes.",
"The lake in our town, once used for fishing, now has a persistent film on its surface traced back to a nearby workshop cluster.",
"Deforestation on the slope above our village has made the monsoon runoff far more destructive than it used to be.",
"A rendering plant on the town's edge releases an overpowering smell that reaches residential areas whenever the wind shifts.",
"The air quality near the highway construction site has worsened noticeably, with fine dust settling on homes for months now.",
"Chemical foam has been observed floating on the river downstream of the textile cluster after every heavy rain.",
"Noise from generators run continuously by a nearby workshop has made it difficult for residents to have conversations indoors after dark.",
"An old quarry pit left unfilled near our settlement has become a breeding ground for mosquitoes and a hazard for children.",
"The soil in the fields nearest the industrial drain has become visibly discoloured over the last two growing seasons.",
"Cutting of roadside trees for a widening project proceeded without the compensatory plantation that was promised at the public hearing.",
"A sudden fish die-off in our local river coincided with reports of a chemical spill upstream that was never officially confirmed.",
"The smoke from crop residue burning in the surrounding fields has made the air unbearable in our village for weeks each year.",
"An industrial unit near the residential colony has been releasing wastewater with a strong chemical odour into the open field behind it.",
"Vibrations from continuous heavy machinery at a nearby crusher unit have caused visible cracks to appear in several nearby homes.",
"The riverside forest patch that once buffered our village from flooding has been cleared for a private resort project.",
"Air pollution readings near the industrial zone have consistently exceeded safe limits for the past several months according to residents who track it informally.",
"A private company has reportedly been dumping construction debris into the wetland at the edge of our town, filling it in gradually.",
"The smell of burning rubber from an unregulated tyre-recycling operation drifts into our colony almost every afternoon.",
"Noise levels from a nearby DJ and event venue regularly exceed permitted limits late into the night, with no enforcement visible.",
]

Hindi = [
"हमारे गांव के किनारे स्थित ईंट भट्टे से निकलने वाला घना काला धुआं हर सुबह सूर्योदय से पहले खेतों पर छा जाता है।",
"पिछले साल से ऊपर की ओर एक नई यूनिट खुलने के बाद हमारी कॉलोनी के पीछे की धारा अजीब स्लेटी रंग की हो गई है।",
"पत्थर तोड़ने वाली यूनिट से आने वाला शोर आधी रात के बाद तक चलता है, और सबसे नजदीक रहने वाले निवासी अब ठीक से सो नहीं पाते।",
"हमारी सड़क के किनारे लगे दर्जनों पुराने पेड़ पिछले हफ्ते बिना किसी सार्वजनिक सूचना या प्रतिपूरक रोपण योजना के काट दिए गए।",
"पास के थर्मल प्लांट से निकलने वाली राख हर कुछ दिनों में हमारी छतों और सब्जी की क्यारियों पर जम जाती है।",
"बाहरी इलाके में स्थित एक चमड़ा उद्योग कथित तौर पर उस नदी में सीधे अशोधित अपशिष्ट छोड़ रहा है जिसका हम सिंचाई के लिए इस्तेमाल करते हैं।",
"औद्योगिक क्षेत्र के पास हवा कुछ सुबहों में इतनी गाढ़ी हो जाती है कि दृश्यता मुश्किल से सौ मीटर रह जाती है।",
"बाजार के पीछे प्लास्टिक कचरे का अवैध जलाना ज्यादातर शामों को हमारे मोहल्ले में तीखा धुआं छोड़ता है।",
"हमारी तटीय बस्ती को तूफानी लहरों से बचाने वाला मैंग्रोव जंगल का एक टुकड़ा एक निजी परियोजना के लिए साफ कर दिया गया।",
"दो किलोमीटर दूर फैक्ट्री से आने वाली रासायनिक गंध निवासियों में सिरदर्द पैदा करने लायक तेज हो गई है।",
"पास की एक यूनिट से निकलने वाली फ्लाई ऐश सीमा दीवार के सबसे करीब वाले खेतों की फसलों पर जम रही है।",
"औद्योगिक समूह के पास भूजल में एक अजीब गंध आने लगी है, निवासियों का कहना है कि यह एक नया प्लांट शुरू होने के बाद से हुआ है।",
"गैस प्रोसेसिंग यूनिट से लगातार होने वाला फ्लेयरिंग रात के आसमान को रोशन कर देता है और उसके साथ आने वाला शोर किलोमीटर दूर तक सुनाई देता है।",
"पीढ़ियों से गांव द्वारा इस्तेमाल किया जाने वाला एक साफ तालाब पास में एक रंगाई यूनिट शुरू होने के बाद से बदबूदार हो गया है।",
"अनियमित खनन गतिविधियों के कारण हमारे शहर के पीछे की पहाड़ियों ने इस साल काफी पेड़ों का आवरण खो दिया है।",
"हमारे मोहल्ले में एक अनियमित रीसाइक्लिंग यूनिट से निकलने वाला धुआं शाम को सांस लेना काफी मुश्किल बना देता है।",
"सीमेंट प्लांट की महीन धूल हमारी गली में हर चीज पर जमती है, और बुजुर्ग निवासियों में सांस संबंधी शिकायतें तेजी से बढ़ी हैं।",
"नदी किनारे एक अनधिकृत डंपिंग साइट भारी बारिश के दौरान पानी में एक गहरा तरल पदार्थ रिसाना शुरू कर चुकी है।",
"हमारी वेटलैंड पर हर सर्दी में रुकने वाले प्रवासी पक्षी पानी की गुणवत्ता बदलने के बाद से दो साल से आना बंद कर चुके हैं।",
"पेपर मिल की चिमनी हर रात एक साफ दिखने वाला धुआं छोड़ती है जो सुबह तक आस-पास की छतों पर महीन अवशेष के रूप में जम जाता है।",
"बाजार के पास अत्यधिक हॉर्न बजाना और अनियमित लाउडस्पीकर इस्तेमाल शोर के स्तर को रिहायशी क्षेत्र के लिए सहनीय सीमा से कहीं ज्यादा बढ़ा चुका है।",
"जो खदान ब्लास्टिंग शेड्यूल केवल दिन के समय तक सीमित होना था, वह अब शाम तक चल रहा है, जिससे आस-पास के घरों की दीवारों में दरारें आ रही हैं।",
"हमारे शहर की झील, जो कभी मछली पकड़ने के लिए इस्तेमाल होती थी, अब उसकी सतह पर एक स्थायी परत जमी रहती है जिसका स्रोत पास का एक वर्कशॉप समूह बताया जा रहा है।",
"हमारे गांव के ऊपर की ढलान पर वनों की कटाई ने मानसून के बहाव को पहले से कहीं ज्यादा विनाशकारी बना दिया है।",
"शहर के किनारे स्थित एक रेंडरिंग प्लांट से निकलने वाली तीखी गंध हवा की दिशा बदलते ही रिहायशी इलाकों तक पहुंच जाती है।",
"हाईवे निर्माण स्थल के पास हवा की गुणवत्ता स्पष्ट रूप से बिगड़ गई है, महीन धूल महीनों से घरों पर जम रही है।",
"हर भारी बारिश के बाद टेक्सटाइल समूह के नीचे की ओर नदी में रासायनिक झाग तैरता हुआ देखा जा रहा है।",
"पास की एक वर्कशॉप द्वारा लगातार चलाए जाने वाले जनरेटरों के शोर ने अंधेरा होने के बाद निवासियों के लिए घर के अंदर बातचीत करना मुश्किल बना दिया है।",
"हमारी बस्ती के पास बिना भरे छोड़ा गया एक पुराना खदान गड्ढा मच्छरों के प्रजनन स्थल और बच्चों के लिए खतरा बन गया है।",
"औद्योगिक नाले के सबसे करीब खेतों की मिट्टी पिछले दो फसल मौसमों में स्पष्ट रूप से रंग बदल चुकी है।",
"चौड़ीकरण परियोजना के लिए सड़क किनारे के पेड़ों की कटाई सार्वजनिक सुनवाई में वादा किए गए प्रतिपूरक रोपण के बिना ही आगे बढ़ गई।",
"हमारी स्थानीय नदी में अचानक मछलियों की मौत ऊपर की ओर एक रासायनिक रिसाव की रिपोर्ट के साथ मेल खाती है जिसकी कभी आधिकारिक पुष्टि नहीं हुई।",
"आस-पास के खेतों में फसल अवशेष जलाने से निकलने वाला धुआं हर साल हफ्तों तक हमारे गांव में हवा को असहनीय बना देता है।",
"रिहायशी कॉलोनी के पास एक औद्योगिक यूनिट तेज रासायनिक गंध वाला अपशिष्ट जल उसके पीछे के खुले मैदान में छोड़ रही है।",
"पास की एक क्रशर यूनिट में लगातार चलने वाली भारी मशीनरी से आने वाले कंपन ने कई पास के घरों में दरारें दिखाई देनी शुरू कर दी हैं।",
"नदी किनारे का जंगल का वह टुकड़ा जो कभी हमारे गांव को बाढ़ से बचाता था, एक निजी रिसॉर्ट परियोजना के लिए साफ कर दिया गया है।",
"निवासियों के अनौपचारिक रूप से किए गए ट्रैकिंग के अनुसार, औद्योगिक क्षेत्र के पास वायु प्रदूषण की रीडिंग पिछले कई महीनों से लगातार सुरक्षित सीमा पार कर रही है।",
"एक निजी कंपनी कथित तौर पर हमारे शहर के किनारे वेटलैंड में निर्माण मलबा डालकर उसे धीरे-धीरे भर रही है।",
"एक अनियमित टायर-रीसाइक्लिंग संचालन से जलते रबर की गंध लगभग हर दोपहर हमारी कॉलोनी में आ जाती है।",
"पास के एक डीजे और इवेंट वेन्यू से निकलने वाला शोर नियमित रूप से देर रात तक अनुमत सीमा से अधिक रहता है, बिना किसी दिखाई देने वाले प्रवर्तन के।",
]

Hinglish = [
"Hamare village ke kinare sthit brick kiln se nikalne wala ghana kaala dhuaan har subah sunrise se pehle kheton par chha jaata hai.",
"Pichle saal se upar ki taraf ek nayi unit khulne ke baad hamari colony ke peeche ki stream ajeeb grey color ki ho gayi hai.",
"Stone crushing unit se aane wala noise aadhi raat ke baad tak chalta hai, aur sabse nazdeek rehne wale residents ab theek se so nahi paate.",
"Hamari sadak ke kinare lage dozens purane ped pichle hafte bina kisi public notice ya replacement planting plan ke kaat diye gaye.",
"Paas ke thermal plant se nikalne wali ash har kuch dinon mein hamari terraces aur vegetable patches par jam jaati hai.",
"Bahri ilake mein sthit ek tannery reportedly us river mein seedha untreated effluent chhod rahi hai jise hum irrigation ke liye use karte hain.",
"Industrial belt ke paas hawa kuch subaho mein itni thick ho jaati hai ki visibility mushkil se sau meter reh jaati hai.",
"Market ke peeche plastic waste ka illegal burning zyadatar shaamon ko hamare mohalle mein tez dhuaan chhodta hai.",
"Hamari coastal basti ko storm surges se bachane wala mangrove forest ka ek patch ek private project ke liye clear kar diya gaya.",
"Do kilometer door factory se aane wali chemical smell residents mein headache paida karne layak strong ho gayi hai.",
"Paas ki ek unit se nikalne wali fly ash boundary wall ke sabse kareeb wale kheton ki crops par jam rahi hai.",
"Industrial cluster ke paas groundwater mein ek ajeeb odour aane lagi hai, residents ka kehna hai ki yeh ek naya plant shuru hone ke baad se hua hai.",
"Gas processing unit se lagatar hone wala flaring raat ke aasmaan ko roshan kar deta hai aur uske saath aane wala noise kilometers door tak sunayi deta hai.",
"Peedhiyon se village dwara use kiya jaane wala ek saaf pond paas mein ek dyeing unit shuru hone ke baad se badbudaar ho gaya hai.",
"Unregulated quarrying operations ki wajah se hamare town ke peeche ki hills ne is saal kaafi tree cover kho diya hai.",
"Hamare mohalle mein ek unregulated recycling unit se nikalne wala fumes shaam ko saans lena kaafi mushkil bana deta hai.",
"Cement plant ki fine dust hamari gali mein har cheez par jamti hai, aur elderly residents mein respiratory complaints tezi se badhi hain.",
"River ke kinare ek unauthorised dumping site heavy rain ke dauran paani mein ek dark liquid leach karna shuru kar chuki hai.",
"Hamari wetland par har sardi ruknay wale migratory birds water quality badalne ke baad se do saal se aana band kar chuke hain.",
"Paper mill ki chimney har raat ek visible plume chhodti hai jo subah tak aas-paas ki chhaton par fine residue ki tarah jam jaata hai.",
"Market ke paas excessive honking aur unregulated loudspeaker use ne noise levels ko residential zone ke liye tolerable limit se kahin zyada badha diya hai.",
"Jo quarry blasting schedule sirf daytime hours tak limited hona tha, woh ab shaam tak chal raha hai, jisse aas-paas ke gharon ki deewaron mein cracks aa rahe hain.",
"Hamare town ki lake, jo kabhi fishing ke liye use hoti thi, ab uski surface par ek persistent film rehti hai jiska source paas ka ek workshop cluster bataya ja raha hai.",
"Hamare village ke upar ki slope par deforestation ne monsoon runoff ko pehle se kahin zyada destructive bana diya hai.",
"Town ke edge par sthit ek rendering plant se nikalne wali overpowering smell wind shift hote hi residential areas tak pahunch jaati hai.",
"Highway construction site ke paas air quality clearly bigad gayi hai, fine dust mahinon se gharon par jam rahi hai.",
"Har heavy rain ke baad textile cluster ke neeche ki taraf river mein chemical foam tairta hua dekha ja raha hai.",
"Paas ki ek workshop dwara continuously chalaye jaane wale generators ke noise ne andhera hone ke baad residents ke liye ghar ke andar baat karna mushkil bana diya hai.",
"Hamari basti ke paas bina bhare chhoda gaya ek purana quarry pit machharon ka breeding ground aur bachchon ke liye hazard ban gaya hai.",
"Industrial drain ke sabse kareeb kheton ki soil pichle do growing seasons mein clearly discolour ho chuki hai.",
"Widening project ke liye roadside trees ki cutting public hearing mein promise ki gayi compensatory plantation ke bina hi aage badh gayi.",
"Hamari local river mein achanak fish die-off ek chemical spill ki reports ke saath match karta hai jo upar ki taraf hua tha aur kabhi officially confirm nahi hua.",
"Aas-paas ke kheton mein crop residue burning se nikalne wala dhuaan har saal hafton tak hamare village mein hawa ko unbearable bana deta hai.",
"Residential colony ke paas ek industrial unit strong chemical odour wala wastewater uske peeche ke open field mein chhod rahi hai.",
"Paas ki ek crusher unit mein continuously chalne wali heavy machinery se aane wale vibrations ne kayi paas ke gharon mein visible cracks dikhayi deni shuru kar di hain.",
"Riverside forest ka woh patch jo kabhi hamare village ko flooding se bachata tha, ek private resort project ke liye clear kar diya gaya hai.",
"Residents ke informally kiye gaye tracking ke mutabik, industrial zone ke paas air pollution readings pichle kayi mahinon se lagatar safe limit paar kar rahi hain.",
"Ek private company reportedly hamare town ke edge par wetland mein construction debris daalkar use dheere-dheere bhar rahi hai.",
"Ek unregulated tyre-recycling operation se jalte rubber ki smell lagbhag har afternoon hamari colony mein aa jaati hai.",
"Paas ke ek DJ aur event venue se nikalne wala noise regularly late night tak permitted limit se zyada rehta hai, bina kisi visible enforcement ke.",
]
