# -*- coding: utf-8 -*-

English = [
"My mother waited six hours at the district hospital before anyone even looked at her chart.",
"The PHC in our block has not had a doctor present on Tuesdays or Wednesdays for the last two months.",
"We were sent from one counter to another for an hour before someone told us the X-ray machine has been down since April.",
"The ambulance took over ninety minutes to reach our village even though the base is barely twelve kilometres away.",
"There were no painkillers or basic antibiotics in stock when we went to the sub-centre for my father's fever.",
"A woman in labour had to be carried on a cot for two kilometres because no vehicle was available at the health centre.",
"The nurse on night duty at the community health centre told us to come back in the morning for an emergency case.",
"My grandmother's cataract surgery has been postponed four times at the government eye camp without explanation.",
"Vaccination day at our anganwadi came and went with no vials delivered, and no one informed the mothers in advance.",
"The government hospital charged us for gloves and syringes that are supposed to be free under the scheme.",
"There is a single working ventilator for the entire ICU ward, shared across critical patients.",
"We were told to buy the prescribed injection ourselves from a private pharmacy because the hospital stock had run out weeks ago.",
"The dialysis unit at the district hospital only runs two days a week, forcing patients to travel to another town.",
"My uncle's diabetes test results took eleven days to come back from the lab, by which point his condition had worsened.",
"The maternity ward has two beds shared among five expecting mothers on busy nights.",
"No doctor has visited the PHC in our hamlet in over three weeks, only a compounder attends to patients.",
"The blood bank at the civil hospital turned us away saying the required group was unavailable, with no alternative suggested.",
"Children brought in for the routine immunisation drive were sent home because the cold chain box had not arrived that day.",
"The government dispensary ran out of insulin midway through the month and patients were asked to wait for the next supply.",
"An elderly patient collapsed in the waiting area and it took over twenty minutes for any staff member to respond.",
"The physiotherapy unit at the rehabilitation centre has been non-functional since the therapist was transferred out.",
"We paid for an ambulance privately because the government one assigned to our zone was reportedly being used elsewhere.",
"The ANM did not visit our hamlet for the scheduled antenatal checkup this month.",
"My father was discharged the same day as a minor surgery despite visible complications, and readmitted two days later.",
"The mental health outpatient clinic at the district hospital only operates for two hours once a week.",
"There is no functioning oxygen cylinder backup at the PHC, which becomes dangerous during power cuts.",
"A relative was asked to arrange his own stretcher because none were available at the emergency entrance.",
"The government hospital pharmacy counter shuts an hour before the OPD itself closes, leaving prescriptions unfilled.",
"Post-natal checkups for new mothers in our ward have been skipped entirely for the past two cycles.",
"The TB medication supply at our health sub-centre has been irregular, with patients missing doses some weeks.",
"We waited in the emergency queue for forty minutes while a case that clearly needed immediate attention was pushed to the back.",
"The government hospital's maternity records for my sister were mixed up with another patient's file.",
"There is only one gynaecologist covering three PHCs in our taluka, visiting each just once a week.",
"The health worker who conducts door-to-door screening in our colony has not shown up in over a month.",
"My son's follow-up appointment after his surgery was cancelled twice without any replacement date offered.",
"The community health centre's generator has not worked in over a year, so surgeries are avoided after dark.",
"Our village health camp promised free eye checkups, but the ophthalmologist never arrived on the scheduled day.",
"The government hospital billing counter charged a consultation fee that patients say is not supposed to apply here.",
"An infant with high fever was turned away from the PHC at night because there was no pediatric staff on call.",
"The ambulance driver for our zone reportedly demands cash before agreeing to make the trip.",
]

Hindi = [
"मेरी मां जिला अस्पताल में छह घंटे इंतजार करती रहीं इससे पहले कि किसी ने उनकी फाइल तक देखी।",
"हमारे ब्लॉक के पीएचसी में पिछले दो महीने से मंगलवार और बुधवार को कोई डॉक्टर मौजूद नहीं रहता।",
"एक घंटे तक हमें एक काउंटर से दूसरे काउंटर भेजा जाता रहा जब तक किसी ने बताया कि एक्स-रे मशीन अप्रैल से खराब पड़ी है।",
"हमारे गांव में एम्बुलेंस को पहुंचने में नब्बे मिनट से ज्यादा लग गए जबकि बेस मुश्किल से बारह किलोमीटर दूर है।",
"जब हम अपने पिता के बुखार के लिए सब-सेंटर गए तो वहां न दर्द निवारक थी न कोई सामान्य एंटीबायोटिक।",
"प्रसव पीड़ा में एक महिला को दो किलोमीटर तक चारपाई पर उठाकर ले जाना पड़ा क्योंकि स्वास्थ्य केंद्र पर कोई वाहन उपलब्ध नहीं था।",
"सामुदायिक स्वास्थ्य केंद्र में रात की ड्यूटी पर मौजूद नर्स ने आपातकालीन मामले में सुबह आने को कह दिया।",
"सरकारी नेत्र शिविर में मेरी दादी के मोतियाबिंद के ऑपरेशन को बिना किसी कारण के चार बार टाल दिया गया।",
"हमारे आंगनवाड़ी में टीकाकरण का दिन आया और चला गया, कोई शीशी नहीं पहुंची, और माताओं को पहले से कोई सूचना नहीं दी गई।",
"सरकारी अस्पताल ने हमसे दस्तानों और सिरिंज के पैसे लिए जो योजना के तहत मुफ्त मिलने चाहिए थे।",
"पूरे आईसीयू वार्ड के लिए सिर्फ एक वेंटिलेटर काम कर रहा है, जिसे गंभीर मरीजों के बीच बांटा जा रहा है।",
"हमें बताया गया कि निर्धारित इंजेक्शन खुद निजी दवा दुकान से खरीद लें क्योंकि अस्पताल का स्टॉक हफ्तों पहले खत्म हो चुका था।",
"जिला अस्पताल में डायलिसिस यूनिट हफ्ते में सिर्फ दो दिन चलती है, जिससे मरीजों को दूसरे शहर जाना पड़ता है।",
"मेरे चाचा की डायबिटीज जांच की रिपोर्ट लैब से आने में ग्यारह दिन लग गए, तब तक उनकी हालत बिगड़ चुकी थी।",
"व्यस्त रातों में प्रसूति वार्ड के दो बिस्तर पांच गर्भवती महिलाओं के बीच साझा किए जा रहे हैं।",
"हमारे मोहल्ले के पीएचसी में तीन हफ्तों से कोई डॉक्टर नहीं आया, सिर्फ एक कंपाउंडर ही मरीजों को देखता है।",
"सिविल अस्पताल के ब्लड बैंक ने हमें यह कहकर लौटा दिया कि जरूरी ग्रुप उपलब्ध नहीं है, बिना कोई विकल्प सुझाए।",
"नियमित टीकाकरण अभियान के लिए लाए गए बच्चों को वापस भेज दिया गया क्योंकि कोल्ड चेन बॉक्स उस दिन नहीं पहुंचा था।",
"सरकारी डिस्पेंसरी में महीने के बीच में ही इंसुलिन खत्म हो गया और मरीजों से अगली आपूर्ति का इंतजार करने को कहा गया।",
"वेटिंग एरिया में एक बुजुर्ग मरीज गिर पड़ा और किसी स्टाफ सदस्य को प्रतिक्रिया देने में बीस मिनट से ज्यादा लग गए।",
"पुनर्वास केंद्र की फिजियोथेरेपी यूनिट थेरेपिस्ट के स्थानांतरण के बाद से काम नहीं कर रही है।",
"हमने निजी तौर पर एम्बुलेंस के लिए पैसे दिए क्योंकि हमारे क्षेत्र में तय सरकारी एम्बुलेंस कहीं और इस्तेमाल हो रही थी।",
"एएनएम इस महीने निर्धारित प्रसवपूर्व जांच के लिए हमारे मोहल्ले में नहीं आईं।",
"एक छोटे ऑपरेशन के बावजूद स्पष्ट जटिलताएं होने पर भी मेरे पिता को उसी दिन छुट्टी दे दी गई, और दो दिन बाद फिर भर्ती करना पड़ा।",
"जिला अस्पताल में मानसिक स्वास्थ्य ओपीडी हफ्ते में एक बार सिर्फ दो घंटे के लिए ही चलती है।",
"पीएचसी में ऑक्सीजन सिलेंडर का कोई बैकअप काम नहीं करता, जो बिजली कटौती के दौरान खतरनाक हो जाता है।",
"एक रिश्तेदार को अपनी खुद की स्ट्रेचर की व्यवस्था करने को कहा गया क्योंकि आपातकालीन प्रवेश द्वार पर कोई उपलब्ध नहीं थी।",
"सरकारी अस्पताल की फार्मेसी काउंटर ओपीडी बंद होने से एक घंटा पहले ही बंद हो जाती है, जिससे पर्चे अधूरे रह जाते हैं।",
"हमारे वार्ड में नई माताओं की प्रसवोत्तर जांच पिछले दो चक्रों से पूरी तरह छूट गई है।",
"हमारे स्वास्थ्य उप-केंद्र में टीबी की दवाओं की आपूर्ति अनियमित रही है, कुछ हफ्तों में मरीजों की खुराक छूट जाती है।",
"हम आपातकालीन कतार में चालीस मिनट तक खड़े रहे जबकि साफ तौर पर तुरंत ध्यान की जरूरत वाले एक मामले को पीछे धकेल दिया गया।",
"सरकारी अस्पताल में मेरी बहन के प्रसव संबंधी रिकॉर्ड किसी और मरीज की फाइल से मिल गए।",
"हमारे तालुके में तीन पीएचसी के लिए सिर्फ एक स्त्री रोग विशेषज्ञ हैं, जो हर एक में हफ्ते में सिर्फ एक बार आती हैं।",
"हमारी कॉलोनी में घर-घर जाकर जांच करने वाली स्वास्थ्य कार्यकर्ता एक महीने से ज्यादा समय से नहीं आई हैं।",
"मेरे बेटे के ऑपरेशन के बाद की फॉलो-अप अपॉइंटमेंट बिना किसी नई तारीख के दो बार रद्द कर दी गई।",
"सामुदायिक स्वास्थ्य केंद्र का जनरेटर एक साल से ज्यादा समय से खराब है, इसलिए अंधेरा होने के बाद ऑपरेशन टाले जाते हैं।",
"हमारे गांव के स्वास्थ्य शिविर में मुफ्त आंखों की जांच का वादा किया गया था, लेकिन तय दिन नेत्र विशेषज्ञ कभी नहीं आए।",
"सरकारी अस्पताल के बिलिंग काउंटर ने एक परामर्श शुल्क लिया जो मरीजों के अनुसार यहां लागू ही नहीं होना चाहिए।",
"रात में तेज बुखार वाले एक शिशु को पीएचसी से वापस भेज दिया गया क्योंकि वहां कोई बाल रोग विशेषज्ञ ड्यूटी पर नहीं था।",
"हमारे क्षेत्र का एम्बुलेंस चालक कथित तौर पर यात्रा के लिए राजी होने से पहले नकद मांगता है।",
]

Hinglish = [
"Meri maa district hospital mein chhe ghante wait karti rahin, isse pehle ki koi unki file tak dekhta.",
"Hamare block ke PHC mein pichle do mahine se Tuesday aur Wednesday ko koi doctor present nahi rehta.",
"Ek ghante tak humein ek counter se doosre counter bheja jaata raha jab tak kisi ne bataya ki X-ray machine April se kharab padi hai.",
"Hamare village mein ambulance ko pahunchne mein nabbe minute se zyada lag gaye jabki base mushkil se barah kilometer door hai.",
"Jab hum apne father ke fever ke liye sub-centre gaye to wahan na painkiller thi na koi basic antibiotic.",
"Labour pain mein ek mahila ko do kilometer tak khatiya par utha kar le jaana pada kyunki health centre par koi vehicle available nahi tha.",
"Community health centre mein night duty par maujood nurse ne emergency case mein subah aane ko keh diya.",
"Sarkari eye camp mein meri dadi ke cataract operation ko bina kisi reason ke chaar baar postpone kar diya gaya.",
"Hamare anganwadi mein vaccination ka din aaya aur chala gaya, koi vial nahi pahunchi, aur mothers ko pehle se koi info nahi di gayi.",
"Sarkari hospital ne humse gloves aur syringe ke paise liye jo scheme ke tahat free milne chahiye the.",
"Poore ICU ward ke liye sirf ek ventilator kaam kar raha hai, jise critical patients ke beech baanta ja raha hai.",
"Humein bataya gaya ki prescribed injection khud private pharmacy se khareed lein kyunki hospital ka stock hafton pehle khatam ho chuka tha.",
"District hospital mein dialysis unit hafte mein sirf do din chalti hai, jisse patients ko doosre shehar jaana padta hai.",
"Mere chacha ki diabetes test report lab se aane mein gyarah din lag gaye, tab tak unki condition bigad chuki thi.",
"Busy raaton mein maternity ward ke do bed paanch pregnant mahilaon ke beech share kiye ja rahe hain.",
"Hamare mohalle ke PHC mein teen hafton se koi doctor nahi aaya, sirf ek compounder hi patients ko dekhta hai.",
"Civil hospital ke blood bank ne humein yeh kehkar laut diya ki zaroori group available nahi hai, bina koi alternative suggest kiye.",
"Routine immunisation drive ke liye laaye gaye bachchon ko wapas bhej diya gaya kyunki cold chain box us din nahi pahuncha tha.",
"Sarkari dispensary mein mahine ke beech mein hi insulin khatam ho gaya aur patients se agli supply ka wait karne ko kaha gaya.",
"Waiting area mein ek buzurg patient gir gaye aur kisi staff member ko react karne mein bees minute se zyada lag gaye.",
"Rehabilitation centre ki physiotherapy unit therapist ke transfer ke baad se kaam nahi kar rahi.",
"Humne privately ambulance ke liye paise diye kyunki hamare zone ke liye tay sarkari ambulance kahin aur use ho rahi thi.",
"ANM is mahine scheduled antenatal checkup ke liye hamare mohalle mein nahi aayi.",
"Ek chhote operation ke bawajood clear complications hone par bhi mere father ko usi din discharge kar diya gaya, aur do din baad phir admit karna pada.",
"District hospital mein mental health OPD hafte mein ek baar sirf do ghante ke liye hi chalti hai.",
"PHC mein oxygen cylinder ka koi backup kaam nahi karta, jo power cut ke dauran khatarnak ho jaata hai.",
"Ek relative ko apna khud ka stretcher arrange karne ko kaha gaya kyunki emergency entrance par koi available nahi tha.",
"Sarkari hospital ka pharmacy counter OPD band hone se ek ghanta pehle hi band ho jaata hai, jisse prescriptions adhoore reh jaate hain.",
"Hamare ward mein naye maaon ki post-natal checkup pichle do cycles se poori tarah miss ho gayi hai.",
"Hamare health sub-centre mein TB ki dawaiyon ki supply irregular rahi hai, kuch hafton mein patients ki dose miss ho jaati hai.",
"Hum emergency queue mein chaalis minute khade rahe jabki saaf taur par turant attention chahiye wale ek case ko peeche dhakel diya gaya.",
"Sarkari hospital mein meri behen ke maternity records kisi aur patient ki file se mix ho gaye.",
"Hamare taluka mein teen PHC ke liye sirf ek gynaecologist hain, jo har ek mein hafte mein sirf ek baar aati hain.",
"Hamari colony mein door-to-door screening karne wali health worker ek mahine se zyada time se nahi aayi hain.",
"Mere bete ke operation ke baad ki follow-up appointment bina kisi nayi date ke do baar cancel kar di gayi.",
"Community health centre ka generator ek saal se zyada time se kharab hai, isliye andhera hone ke baad operations avoid kiye jaate hain.",
"Hamare village ke health camp mein free eye checkup ka wada kiya gaya tha, lekin tay din ophthalmologist kabhi nahi aaye.",
"Sarkari hospital ke billing counter ne ek consultation fee li jo patients ke mutabik yahan apply hi nahi honi chahiye.",
"Raat mein tez fever wale ek infant ko PHC se wapas bhej diya gaya kyunki wahan koi pediatric staff on-call nahi tha.",
"Hamare zone ka ambulance driver reportedly trip ke liye maanne se pehle cash maangta hai.",
]
