import 'package:flutter/material.dart';

class LanguageOption {
  final String code;
  final String nativeName;
  final String englishName;
  final String greeting;

  const LanguageOption({
    required this.code,
    required this.nativeName,
    required this.englishName,
    required this.greeting,
  });
}

class LanguageService extends ChangeNotifier {
  static final LanguageService instance = LanguageService._internal();

  LanguageService._internal();

  String _currentLanguageCode = 'en';

  String get currentLanguageCode => _currentLanguageCode;

  static const List<LanguageOption> supportedLanguages = [
    LanguageOption(
      code: 'en',
      nativeName: 'English',
      englishName: 'English',
      greeting: 'Welcome',
    ),
    LanguageOption(
      code: 'hi',
      nativeName: 'हिन्दी',
      englishName: 'Hindi',
      greeting: 'स्वागत है',
    ),
    LanguageOption(
      code: 'ta',
      nativeName: 'தமிழ்',
      englishName: 'Tamil',
      greeting: 'வணக்கம்',
    ),
    LanguageOption(
      code: 'te',
      nativeName: 'తెలుగు',
      englishName: 'Telugu',
      greeting: 'స్వాగతం',
    ),
    LanguageOption(
      code: 'kn',
      nativeName: 'ಕನ್ನಡ',
      englishName: 'Kannada',
      greeting: 'ಸ್ವಾಗತ',
    ),
    LanguageOption(
      code: 'ml',
      nativeName: 'മലയാളം',
      englishName: 'Malayalam',
      greeting: 'സ്വാഗതം',
    ),
    LanguageOption(
      code: 'mr',
      nativeName: 'मराठी',
      englishName: 'Marathi',
      greeting: 'स्वागत आहे',
    ),
    LanguageOption(
      code: 'bn',
      nativeName: 'বাংলা',
      englishName: 'Bengali',
      greeting: 'স্বাগতম',
    ),
    LanguageOption(
      code: 'gu',
      nativeName: 'ગુજરાતી',
      englishName: 'Gujarati',
      greeting: 'સ્વાગત છે',
    ),
    LanguageOption(
      code: 'pa',
      nativeName: 'ਪੰਜਾਬੀ',
      englishName: 'Punjabi',
      greeting: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    ),
  ];

  LanguageOption get currentLanguage => supportedLanguages.firstWhere(
        (lang) => lang.code == _currentLanguageCode,
        orElse: () => supportedLanguages.first,
      );

  void setLanguage(String code) {
    if (_currentLanguageCode != code) {
      _currentLanguageCode = code;
      notifyListeners();
    }
  }

  static String t(String key) {
    return instance.translate(key);
  }

  String translate(String key) {
    final langDict = _translations[_currentLanguageCode] ?? _translations['en']!;
    return langDict[key] ?? _translations['en']![key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'welcome_title': 'Welcome to Social Serve',
      'welcome_sub': 'Select your preferred language to continue.',
      'choose_language': 'Choose Language',
      'continue_btn': 'Continue',
      'enter_phone': 'Enter your phone number',
      'phone_sub': "We'll send you a verification code",
      'enter_otp': 'Enter verification code',
      'otp_sub': 'Enter the 6-digit code sent to your phone number',
      'verify': 'Verify',
      'resend': 'Resend code',
      'didnt_receive': "Didn't receive the code?",
      'nav_home': 'Home',
      'nav_issues': 'My Issues',
      'nav_file': 'File Grievance',
      'nav_profile': 'Profile',
      'welcome_back': 'Welcome Back',
      'hi_user': 'Hi Dhyan',
      'search_hint': 'Search',
      'welcome_card_title': 'Welcome!',
      'welcome_card_sub': "Let's schedule your civic grievance resolution.",
      'ongoing_issues': 'Ongoing Issues',
      'view_all': 'View all',
      'no_issues_found': 'No Ongoing Issues',
      'no_issues_sub': 'No active grievances found in this area. Notice a problem in your neighborhood?',
      'file_grievance_btn': 'File a Grievance',
      'filter_grievances': 'Filter Grievances',
      'reset_all': 'Reset All',
      'status': 'Status',
      'location_ward': 'Location / Ward',
      'dept_category': 'Department Category',
      'apply_filters': 'Apply Filters',
      'search_grievances_hint': 'Search grievances, ID, location...',
      'status_all': 'All',
      'status_issued': 'Issued',
      'status_in_progress': 'In Progress',
      'status_resolved': 'Resolved',
      'all_locations': 'All Locations',
      'all_reported_locations': 'All Reported Locations',
      'issues_count': 'issues',
      'step1_title': 'Contact Information',
      'step2_title': 'Location Details',
      'step3_title': 'Issue Details',
      'step4_title': 'Upload or Click Photo (Optional)',
      'select_file': 'Select file',
      'or_text': 'or',
      'open_camera': 'Open Camera & Take Photo',
      'submit_grievance': 'Submit Grievance',
      'profile_title': 'Citizen Profile',
      'verified_citizen': 'Verified Citizen • Chennai, TN',
      'reported': 'Reported',
      'in_progress_count': 'In Progress',
      'resolved_count': 'Resolved',
      'phone_number': 'Phone Number',
      'email_address': 'Email Address',
      'settings_notif': 'Settings & Notifications',
      'logout': 'Logout',
      'success_title': 'Successfully Filed Issue',
      'file_another_btn': 'File Another Grievance',
      'home_btn': 'Home',
      'view_my_issues': 'View My Issues',
      'reference_id': 'TICKET REFERENCE',
      'category_label': 'CATEGORY',
      'status_label': 'STATUS',
    },
    'hi': {
      'welcome_title': 'सोशल सर्व में आपका स्वागत है',
      'welcome_sub': 'आगे बढ़ने के लिए अपनी पसंदीदा भाषा चुनें।',
      'choose_language': 'भाषा चुनें',
      'continue_btn': 'आगे बढ़ें',
      'enter_phone': 'अपना फोन नंबर दर्ज करें',
      'phone_sub': 'हम आपको एक सत्यापन कोड भेजेंगे',
      'enter_otp': 'सत्यापन कोड दर्ज करें',
      'otp_sub': 'अपने फोन नंबर पर भेजा गया 6-अंकीय कोड दर्ज करें',
      'verify': 'सत्यापित करें',
      'resend': 'कोड पुनः भेजें',
      'didnt_receive': 'कोड प्राप्त नहीं हुआ?',
      'nav_home': 'होम',
      'nav_issues': 'मेरी समस्याएं',
      'nav_file': 'शिकायत दर्ज करें',
      'nav_profile': 'प्रोफ़ाइल',
      'welcome_back': 'वापसी पर स्वागत है',
      'hi_user': 'नमस्ते ध्यान',
      'search_hint': 'खोजें',
      'welcome_card_title': 'स्वागत है!',
      'welcome_card_sub': 'आइए आपके नागरिक निवारण का समाधान करें।',
      'ongoing_issues': 'चल रही समस्याएं',
      'view_all': 'सभी देखें',
      'no_issues_found': 'कोई सक्रिय समस्या नहीं',
      'no_issues_sub': 'इस क्षेत्र में कोई सक्रिय शिकायत नहीं मिली। क्या आपके पड़ोस में कोई समस्या है?',
      'file_grievance_btn': 'शिकायत दर्ज करें',
      'filter_grievances': 'शिकायतों को फ़िल्टर करें',
      'reset_all': 'सभी रीसेट करें',
      'status': 'स्थिति',
      'location_ward': 'स्थान / वार्ड',
      'dept_category': 'विभाग श्रेणी',
      'apply_filters': 'फ़िल्टर लागू करें',
      'search_grievances_hint': 'शिकायतें, आईडी, स्थान खोजें...',
      'status_all': 'सभी',
      'status_issued': 'जारी',
      'status_in_progress': 'प्रगति पर',
      'status_resolved': 'हल किया गया',
      'all_locations': 'सभी स्थान',
      'all_reported_locations': 'सभी रिपोर्ट किए गए स्थान',
      'issues_count': 'समस्याएं',
      'step1_title': 'संपर्क जानकारी',
      'step2_title': 'स्थान का विवरण',
      'step3_title': 'समस्या का विवरण',
      'step4_title': 'फोटो अपलोड करें या खींचें (वैकल्पिक)',
      'select_file': 'फ़ाइल चुनें',
      'or_text': 'या',
      'open_camera': 'कैमरा खोलें और फोटो लें',
      'submit_grievance': 'शिकायत जमा करें',
      'profile_title': 'नागरिक प्रोफ़ाइल',
      'verified_citizen': 'सत्यापित नागरिक • चेन्नई, टीएन',
      'reported': 'रिपोर्ट किया गया',
      'in_progress_count': 'प्रगति पर',
      'resolved_count': 'हल किया गया',
      'phone_number': 'फोन नंबर',
      'email_address': 'ईमेल पता',
      'settings_notif': 'सेटिंग्स और सूचनाएं',
      'logout': 'लॉग आउट',
      'success_title': 'समस्या सफलतापूर्वक दर्ज की गई',
      'file_another_btn': 'एक और शिकायत दर्ज करें',
      'home_btn': 'होम',
      'view_my_issues': 'मेरी समस्याएं देखें',
      'reference_id': 'टिकट संदर्भ संख्या',
      'category_label': 'श्रेणी',
      'status_label': 'स्थिति',
    },
    'ta': {
      'welcome_title': 'சோஷியல் சர்வுக்கு நல்வரவு',
      'welcome_sub': 'தொடர உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.',
      'choose_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'continue_btn': 'தொடரவும்',
      'enter_phone': 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
      'phone_sub': 'நாங்கள் உங்களுக்கு சரிபார்ப்புக் குறியீட்டை அனுப்புவோம்',
      'enter_otp': 'சரிபார்ப்புக் குறியீட்டை உள்ளிடவும்',
      'otp_sub': 'உங்கள் தொலைபேசிக்கு அனுப்பப்பட்ட 6 இலக்கக் குறியீட்டை உள்ளிடவும்',
      'verify': 'சரிபார்க்கவும்',
      'resend': 'குறியீட்டை மீண்டும் அனுப்புக',
      'didnt_receive': 'குறியீடு கிடைக்கவில்லையா?',
      'nav_home': 'முகப்பு',
      'nav_issues': 'என் புகார்கள்',
      'nav_file': 'புகார் பதிவு',
      'nav_profile': 'சுயவிவரம்',
      'welcome_back': 'மீண்டும் நல்வரவு',
      'hi_user': 'வணக்கம் தியான்',
      'search_hint': 'தேடவும்',
      'welcome_card_title': 'நல்வரவு!',
      'welcome_card_sub': 'உங்கள் குடிமைப் பிரச்சனைக்கான தீர்வை திட்டமிடுவோம்.',
      'ongoing_issues': 'நடப்பு புகார்கள்',
      'view_all': 'அனைத்தையும் பார்',
      'no_issues_found': 'செயலில் உள்ள புகார்கள் இல்லை',
      'no_issues_sub': 'இந்தப் பகுதியில் புகார்கள் ஏதுமில்லை. உங்கள் பகுதியில் ஏதேனும் பிரச்சனையா?',
      'file_grievance_btn': 'புகார் பதிவு செய்க',
      'filter_grievances': 'வடிகட்டவும்',
      'reset_all': 'அனைத்தையும் மீட்டமை',
      'status': 'நிலை',
      'location_ward': 'இடம் / வார்டு',
      'dept_category': 'துறை வகை',
      'apply_filters': 'பயன்படுத்துக',
      'search_grievances_hint': 'புகார்கள், எண், இருப்பிடம் தேடுக...',
      'status_all': 'அனைத்தும்',
      'status_issued': 'பதிவுசெய்யப்பட்டது',
      'status_in_progress': 'செயலில்',
      'status_resolved': 'தீர்க்கப்பட்டது',
      'all_locations': 'அனைத்து இடங்கள்',
      'all_reported_locations': 'அறிவிக்கப்பட்ட அனைத்து இடங்கள்',
      'issues_count': 'புகார்கள்',
      'step1_title': 'தொடர்பு தகவல்',
      'step2_title': 'இட விவரங்கள்',
      'step3_title': 'பிரச்சனை விவரங்கள்',
      'step4_title': 'புகைப்படம் பதிவேற்றவும் (விருப்பத்தேர்வு)',
      'select_file': 'கோப்பைத் தேர்ந்தெடுக்கவும்',
      'or_text': 'அல்லது',
      'open_camera': 'கேமரா திறந்து படம் எடுக்கவும்',
      'submit_grievance': 'புகாரைச் சமர்ப்பிக்கவும்',
      'profile_title': 'குடிமகன் சுயவிவரம்',
      'verified_citizen': 'சரிபார்க்கப்பட்ட குடிமகன் • சென்னை',
      'reported': 'பதிவானவை',
      'in_progress_count': 'செயலில்',
      'resolved_count': 'தீர்க்கப்பட்டது',
      'phone_number': 'தொலைபேசி எண்',
      'email_address': 'மின்னஞ்சல் முகவரி',
      'settings_notif': 'அமைப்புகள் & அறிவிப்புகள்',
      'logout': 'வெளியேறு',
      'success_title': 'புகார் வெற்றிகரமாக பதிவு செய்யப்பட்டது',
      'file_another_btn': 'மற்றொரு புகாரைப் பதிவுசெய்க',
      'home_btn': 'முகப்பு',
      'view_my_issues': 'என் புகார்களைப் பார்',
      'reference_id': 'குறிப்பு எண்',
      'category_label': 'துறை',
      'status_label': 'நிலை',
    },
    'te': {
      'welcome_title': 'సోషల్ సర్వ్‌కు స్వాగతం',
      'welcome_sub': 'కొనసాగించడానికి మీ ప్రాధాన్యత గల భాషను ఎంచుకోండి.',
      'choose_language': 'భాషను ఎంచుకోండి',
      'continue_btn': 'కొనసాగించండి',
      'enter_phone': 'మీ ఫోన్ నంబర్‌ను నమోదు చేయండి',
      'phone_sub': 'మేము మీకు ధృవీకరణ కోడ్‌ను పంపుతాము',
      'enter_otp': 'ధృవీకరణ కోడ్‌ను నమోదు చేయండి',
      'otp_sub': 'మీ ఫోన్‌కు పంపిన 6 అంకెల కోడ్‌ను నమోదు చేయండి',
      'verify': 'ధృవీకరించండి',
      'resend': 'కోడ్‌ను మళ్లీ పంపండి',
      'didnt_receive': 'కోడ్ రాలేదా?',
      'nav_home': 'హోమ్',
      'nav_issues': 'నా సమస్యలు',
      'nav_file': 'ఫిర్యాదు చేయండి',
      'nav_profile': 'ప్రొఫైల్',
      'welcome_back': 'తిరిగి స్వాగతం',
      'hi_user': 'నమస్తే ధ్యాన్',
      'search_hint': 'శోధించండి',
      'welcome_card_title': 'స్వాగతం!',
      'welcome_card_sub': 'మీ పౌర సమస్య పరిష్కారాన్ని షెడ్యూల్ చేద్దాం.',
      'ongoing_issues': 'ప్రస్తుత సమస్యలు',
      'view_all': 'అన్నీ చూడండి',
      'no_issues_found': 'చురుకైన సమస్యలు లేవు',
      'no_issues_sub': 'ఈ ప్రాంతంలో సమస్యలు ఏవీ లేవు.',
      'file_grievance_btn': 'ఫిర్యాదు చేయండి',
      'filter_grievances': 'ఫిల్టర్ చేయండి',
      'reset_all': 'అన్నీ రీసెట్ చేయండి',
      'status': 'స్థితి',
      'location_ward': 'ప్రాంతం / వార్డు',
      'dept_category': 'విభాగ వర్గం',
      'apply_filters': 'ఫిల్టర్లు వర్తించు',
      'search_grievances_hint': 'ఫిర్యాదులు, ఐడి, స్థానాన్ని శోధించండి...',
      'status_all': 'అన్నీ',
      'status_issued': 'జారీ చేయబడింది',
      'status_in_progress': 'పురోగతిలో ఉంది',
      'status_resolved': 'పరిష్కరించబడింది',
      'all_locations': 'అన్ని స్థానాలు',
      'all_reported_locations': 'నివేదించబడిన అన్ని స్థానాలు',
      'issues_count': 'సమస్యలు',
      'step1_title': 'సంప్రదింపు సమాచారం',
      'step2_title': 'స్థాన వివరాలు',
      'step3_title': 'సమస్య వివరాలు',
      'step4_title': 'ఫోటో అప్‌లోడ్ చేయండి (ఐచ్ఛికం)',
      'select_file': 'ఫైల్‌ను ఎంచుకోండి',
      'or_text': 'లేదా',
      'open_camera': 'కెమెరా తెరిచి ఫోటో తీయండి',
      'submit_grievance': 'ఫిర్యాదును సమర్పించండి',
      'profile_title': 'పౌరుడి ప్రొఫైల్',
      'verified_citizen': 'ధృవీకరించబడిన పౌరుడు • చెన్నై',
      'reported': 'నివేదించబడింది',
      'in_progress_count': 'పురోగతిలో ఉంది',
      'resolved_count': 'పరిష్కరించబడింది',
      'phone_number': 'ఫోన్ నంబర్',
      'email_address': 'ఇమెయిల్ చిరునామా',
      'settings_notif': 'సెట్టింగ్‌లు & నోటిఫికేషన్‌లు',
      'logout': 'లాగ్ అవుట్',
      'success_title': 'సమస్య విజయవంతంగా నమోదైంది',
      'file_another_btn': 'మరొక ఫిర్యాదు చేయండి',
      'home_btn': 'హోమ్',
      'view_my_issues': 'నా సమస్యలను చూడండి',
      'reference_id': 'రిఫరెన్స్ ఐడి',
      'category_label': 'విభాగం',
      'status_label': 'స్థితి',
    },
    'kn': {
      'welcome_title': 'ಸೋಷಿಯಲ್ ಸರ್ವ್‌ಗೆ ಸ್ವಾಗತ',
      'welcome_sub': 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
      'choose_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'continue_btn': 'ಮುಂದುವರಿಯಿರಿ',
      'enter_phone': 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'phone_sub': 'ನಾವು ನಿಮಗೆ ಪರಿಶೀಲನಾ ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ',
      'enter_otp': 'ಪರಿಶೀಲನಾ ಕೋಡ್ ನಮೂದಿಸಿ',
      'otp_sub': 'ನಿಮ್ಮ ಫೋನ್‌ಗೆ ಕಳುಹಿಸಲಾದ 6 ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ',
      'verify': 'ಪರಿಶೀಲಿಸಿ',
      'resend': 'ಕೋಡ್ ಮರುಕಳುಹಿಸಿ',
      'didnt_receive': 'ಕೋಡ್ ಸ್ವೀಕರಿಸಲಿಲ್ಲವೇ?',
      'nav_home': 'ಮುಖಪುಟ',
      'nav_issues': 'ನನ್ನ ಸಮಸ್ಯೆಗಳು',
      'nav_file': 'ದೂರು ದಾಖಲಿಸಿ',
      'nav_profile': 'ಪ್ರೊಫೈಲ್',
      'welcome_back': 'ಮರಳಿ ಸ್ವಾಗತ',
      'hi_user': 'ನಮಸ್ಕಾರ ಧ್ಯಾನ್',
      'search_hint': 'ಹುಡುಕಿ',
      'welcome_card_title': 'ಸ್ವಾಗತ!',
      'welcome_card_sub': 'ನಿಮ್ಮ ನಾಗರಿಕ ಸಮಸ್ಯೆಯ ಪರಿಹಾರವನ್ನು ಯೋಜಿಸೋಣ.',
      'ongoing_issues': 'ಪ್ರಸ್ತುತ ಸಮಸ್ಯೆಗಳು',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
      'no_issues_found': 'ಯಾವುದೇ ಸಮಸ್ಯೆಗಳಿಲ್ಲ',
      'no_issues_sub': 'ಈ ಪ್ರದೇಶದಲ್ಲಿ ಯಾವುದೇ ಸಮಸ್ಯೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
      'file_grievance_btn': 'ದೂರು ದಾಖಲಿಸಿ',
      'filter_grievances': 'ಫಿಲ್ಟರ್ ಮಾಡಿ',
      'reset_all': 'ಎಲ್ಲವನ್ನೂ ಮರುಹೊಂದಿಸಿ',
      'status': 'ಸ್ಥಿತಿ',
      'location_ward': 'ಸ್ಥಳ / ವಾರ್ಡ್',
      'dept_category': 'ಇಲಾಖೆಯ ವರ್ಗ',
      'apply_filters': 'ಅನ್ವಯಿಸಿ',
      'search_grievances_hint': 'ದೂರುಗಳು, ಐಡಿ, ಸ್ಥಳ ಹುಡುಕಿ...',
      'status_all': 'ಎಲ್ಲಾ',
      'status_issued': 'ನೀಡಲಾಗಿದೆ',
      'status_in_progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
      'status_resolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ',
      'all_locations': 'ಎಲ್ಲಾ ಸ್ಥಳಗಳು',
      'all_reported_locations': 'ವರದಿ ಮಾಡಲಾದ ಎಲ್ಲಾ ಸ್ಥಳಗಳು',
      'issues_count': 'ಸಮಸ್ಯೆಗಳು',
      'step1_title': 'ಸಂಪರ್ಕ ಮಾಹಿತಿ',
      'step2_title': 'ಸ್ಥಳದ ವಿವರಗಳು',
      'step3_title': 'ಸಮಸ್ಯೆಯ ವಿವರಗಳು',
      'step4_title': 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (ಐಚ್ಛಿಕ)',
      'select_file': 'ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ',
      'or_text': 'ಅಥವಾ',
      'open_camera': 'ಕ್ಯಾಮೆರಾ ತೆರೆದು ಫೋಟೋ ತೆಗೆಯಿರಿ',
      'submit_grievance': 'ದೂರು ಸಲ್ಲಿಸಿ',
      'profile_title': 'ನಾಗರಿಕ ಪ್ರೊಫೈಲ್',
      'verified_citizen': 'ಪರಿಶೀಲಿಸಿದ ನಾಗರಿಕ • ಚೆನ್ನೈ',
      'reported': 'ವರದಿ ಮಾಡಲಾಗಿದೆ',
      'in_progress_count': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
      'resolved_count': 'ಪರಿಹರಿಸಲಾಗಿದೆ',
      'phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
      'email_address': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'settings_notif': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಅಧಿಸೂಚನೆಗಳು',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'success_title': 'ಸಮಸ್ಯೆ ಯಶಸ್ವಿಯಾಗಿ ದಾಖಲಾಗಿದೆ',
      'file_another_btn': 'ಮತ್ತೊಂದು ದೂರು ದಾಖಲಿಸಿ',
      'home_btn': 'ಮುಖಪುಟ',
      'view_my_issues': 'ನನ್ನ ಸಮಸ್ಯೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      'reference_id': 'ಉಲ್ಲೇಖ ಐಡಿ',
      'category_label': 'ವರ್ಗ',
      'status_label': 'ಸ್ಥಿತಿ',
    },
    'ml': {
      'welcome_title': 'സോഷ്യൽ സെർവിലേക്ക് സ്വാഗതം',
      'welcome_sub': 'തുടരുന്നതിന് നിങ്ങളുടെ ഇഷ്ടപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക.',
      'choose_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'continue_btn': 'തുടരുക',
      'enter_phone': 'നിങ്ങളുടെ ഫോൺ നമ്പർ നൽകുക',
      'phone_sub': 'ഞങ്ങൾ നിങ്ങൾക്ക് ഒരു സ്ഥിരീകരണ കോഡ് അയയ്ക്കും',
      'enter_otp': 'സ്ഥിരീകരണ കോഡ് നൽകുക',
      'otp_sub': 'നിങ്ങളുടെ ഫോണിലേക്ക് അയച്ച 6 അക്ക കോഡ് നൽകുക',
      'verify': 'സ്ഥിരീകരിക്കുക',
      'resend': 'കോഡ് വീണ്ടും അയക്കുക',
      'didnt_receive': 'കോഡ് ലഭിച്ചില്ലേ?',
      'nav_home': 'ഹോം',
      'nav_issues': 'എന്റെ പരാതികൾ',
      'nav_file': 'പരാതി നൽകുക',
      'nav_profile': 'പ്രൊഫൈൽ',
      'welcome_back': 'വീണ്ടും സ്വാഗതം',
      'hi_user': 'ഹലോ ധ്യാൻ',
      'search_hint': 'തിരയുക',
      'welcome_card_title': 'സ്വാഗതം!',
      'welcome_card_sub': 'നിങ്ങളുടെ പൗര പരാതി പരിഹാരം ഷെഡ്യൂൾ ചെയ്യാം.',
      'ongoing_issues': 'നിലവിലുള്ള പരാതികൾ',
      'view_all': 'എല്ലാം കാണുക',
      'no_issues_found': 'പരാതികളൊന്നുമില്ല',
      'no_issues_sub': 'ഈ പ്രദേശത്ത് സജീവമായ പരാതികളൊന്നും കണ്ടെത്തിയില്ല.',
      'file_grievance_btn': 'പരാതി നൽകുക',
      'filter_grievances': 'ഫിൽട്ടർ ചെയ്യുക',
      'reset_all': 'എല്ലാം റീസെറ്റ് ചെയ്യുക',
      'status': 'നില',
      'location_ward': 'സ്ഥലം / വാർഡ്',
      'dept_category': 'വകുപ്പ് വിഭാഗം',
      'apply_filters': 'ഫിൽട്ടറുകൾ പ്രയോഗിക്കുക',
      'search_grievances_hint': 'പരാതികൾ, ഐഡി, സ്ഥലം തിരയുക...',
      'status_all': 'എല്ലാം',
      'status_issued': 'നൽകി',
      'status_in_progress': 'പുരോഗമിക്കുന്നു',
      'status_resolved': 'പരിഹരിച്ചു',
      'all_locations': 'എല്ലാ സ്ഥലങ്ങളും',
      'all_reported_locations': 'റിപ്പോർട്ട് ചെയ്ത എല്ലാ സ്ഥലങ്ങളും',
      'issues_count': 'പരാതികൾ',
      'step1_title': 'ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ',
      'step2_title': 'സ്ഥല വിവരങ്ങൾ',
      'step3_title': 'പരാതിയുടെ വിവരങ്ങൾ',
      'step4_title': 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക (ഓപ്ഷണൽ)',
      'select_file': 'ഫയൽ തിരഞ്ഞെടുക്കുക',
      'or_text': 'അല്ലെങ്കിൽ',
      'open_camera': 'ക്യാമറ തുറന്ന് ഫോട്ടോ എടുക്കുക',
      'submit_grievance': 'പരാതി സമർപ്പിക്കുക',
      'profile_title': 'പൗര പ്രൊഫൈൽ',
      'verified_citizen': 'സ്ഥിരീകരിച്ച പൗരൻ • ചെന്നൈ',
      'reported': 'റിപ്പോർട്ട് ചെയ്തത്',
      'in_progress_count': 'പുരോഗമിക്കുന്നു',
      'resolved_count': 'പരിഹരിച്ചു',
      'phone_number': 'ഫോൺ നമ്പർ',
      'email_address': 'ഇമെയിൽ വിലാസം',
      'settings_notif': 'ക്രമീകരണങ്ങളും അറിയിപ്പുകളും',
      'logout': 'ലോഗ് ഔട്ട്',
      'success_title': 'പരാതി വിജയകരമായി ഫയൽ ചെയ്തു',
      'file_another_btn': 'മറ്റൊരു പരാതി നൽകുക',
      'home_btn': 'ഹോം',
      'view_my_issues': 'എന്റെ പരാതികൾ കാണുക',
      'reference_id': 'റഫറൻസ് ഐഡി',
      'category_label': 'വിഭാഗം',
      'status_label': 'നില',
    },
    'mr': {
      'welcome_title': 'सोशल सर्व मध्ये आपले स्वागत आहे',
      'welcome_sub': 'पुढे जाण्यासाठी तुमची पसंतीची भाषा निवडा.',
      'choose_language': 'भाषा निवडा',
      'continue_btn': 'पुढे जा',
      'enter_phone': 'तुमचा फोन नंबर प्रविष्ट करा',
      'phone_sub': 'आम्ही तुम्हाला पडताळणी कोड पाठवू',
      'enter_otp': 'पडताळणी कोड प्रविष्ट करा',
      'otp_sub': 'तुमच्या फोनवर पाठवलेला 6-अंकी कोड प्रविष्ट करा',
      'verify': 'पडताळणी करा',
      'resend': 'कोड पुन्हा पाठवा',
      'didnt_receive': 'कोड मिळाला नाही?',
      'nav_home': 'मुख्यपृष्ठ',
      'nav_issues': 'माझ्या तक्रारी',
      'nav_file': 'तक्रार नोंदवा',
      'nav_profile': 'प्रोफाइल',
      'welcome_back': 'पुन्हा स्वागत आहे',
      'hi_user': 'नमस्कार ध्यान',
      'search_hint': 'शोधा',
      'welcome_card_title': 'स्वागत आहे!',
      'welcome_card_sub': 'आपल्या नागरी तक्रारीचे निराकरण करूया.',
      'ongoing_issues': 'सध्याच्या तक्रारी',
      'view_all': 'सर्व पहा',
      'no_issues_found': 'सध्या कोणतीही तक्रार नाही',
      'no_issues_sub': 'या भागात कोणतीही तक्रार आढळली नाही.',
      'file_grievance_btn': 'तक्रार नोंदवा',
      'filter_grievances': 'तक्रारी फिल्टर करा',
      'reset_all': 'सर्व रीसेट करा',
      'status': 'स्थिती',
      'location_ward': 'स्थान / प्रभाग',
      'dept_category': 'विभाग श्रेणी',
      'apply_filters': 'फिल्टर लागू करा',
      'search_grievances_hint': 'तक्रारी, आयडी, स्थान शोधा...',
      'status_all': 'सर्व',
      'status_issued': 'नोंदणीकृत',
      'status_in_progress': 'प्रगतीपथावर',
      'status_resolved': 'निराकरण झाले',
      'all_locations': 'सर्व स्थाने',
      'all_reported_locations': 'सर्व नोंदवलेली स्थाने',
      'issues_count': 'तक्रारी',
      'step1_title': 'संपर्क माहिती',
      'step2_title': 'स्थानाचा तपशील',
      'step3_title': 'तक्रारीचा तपशील',
      'step4_title': 'फोटो अपलोड करा (पर्यायी)',
      'select_file': 'फाइल निवडा',
      'or_text': 'किंवा',
      'open_camera': 'कॅमेरा उघडा आणि फोटो काढा',
      'submit_grievance': 'तक्रार सबमिट करा',
      'profile_title': 'नागरिक प्रोफाइल',
      'verified_citizen': 'सत्यापित नागरिक • चेन्नई',
      'reported': 'नोंदवलेले',
      'in_progress_count': 'प्रगतीपथावर',
      'resolved_count': 'निराकरण झाले',
      'phone_number': 'फोन नंबर',
      'email_address': 'ईमेल पत्ता',
      'settings_notif': 'सेटिंग्ज आणि सूचना',
      'logout': 'लॉग आउट',
      'success_title': 'समस्या यशस्वीरित्या नोंदवली गेली',
      'file_another_btn': 'दुसरी तक्रार नोंदवा',
      'home_btn': 'मुख्यपृष्ठ',
      'view_my_issues': 'माझ्या तक्रारी पहा',
      'reference_id': 'संदर्भ आयडी',
      'category_label': 'श्रेणी',
      'status_label': 'स्थिती',
    },
    'bn': {
      'welcome_title': 'সোশ্যাল সার্ভে আপনাকে স্বাগতম',
      'welcome_sub': 'চালিয়ে যেতে আপনার পছন্দের ভাষা নির্বাচন করুন।',
      'choose_language': 'ভাষা বেছে নিন',
      'continue_btn': 'চালিয়ে যান',
      'enter_phone': 'আপনার ফোন নম্বর লিখুন',
      'phone_sub': 'আমরা আপনাকে একটি যাচাইকরণ কোড পাঠাব',
      'enter_otp': 'যাচাইকরণ কোড লিখুন',
      'otp_sub': 'আপনার ফোনে পাঠানো ৬-সংখ্যার কোডটি লিখুন',
      'verify': 'যাচাই করুন',
      'resend': 'কোড পুনরায় পাঠান',
      'didnt_receive': 'কোড পাননি?',
      'nav_home': 'হোম',
      'nav_issues': 'আমার সমস্যাগুলি',
      'nav_file': 'অভিযোগ দায়ের করুন',
      'nav_profile': 'প্রোফাইল',
      'welcome_back': 'আবার স্বাগতম',
      'hi_user': 'নমস্কার ধ্যান',
      'search_hint': 'অনুসন্ধান',
      'welcome_card_title': 'স্বাগতম!',
      'welcome_card_sub': 'আসুন আপনার নাগরিক অভিযোগের সমাধান নির্ধারণ করি।',
      'ongoing_issues': 'চলমান সমস্যাগুলি',
      'view_all': 'সব দেখুন',
      'no_issues_found': 'কোনো সক্রিয় সমস্যা নেই',
      'no_issues_sub': 'এই এলাকায় কোনো সক্রিয় অভিযোগ পাওয়া যায়নি।',
      'file_grievance_btn': 'অভিযোগ দায়ের করুন',
      'filter_grievances': 'ফিল্টার করুন',
      'reset_all': 'সব রিসেট করুন',
      'status': 'অবস্থা',
      'location_ward': 'অবস্থান / ওয়ার্ড',
      'dept_category': 'বিভাগীয় বিভাগ',
      'apply_filters': 'ফিল্টার প্রয়োগ করুন',
      'search_grievances_hint': 'অভিযোগ, আইডি, অবস্থান অনুসন্ধান করুন...',
      'status_all': 'সব',
      'status_issued': 'জারি করা হয়েছে',
      'status_in_progress': 'চলমান',
      'status_resolved': 'সমাধান হয়েছে',
      'all_locations': 'সব অবস্থান',
      'all_reported_locations': 'সব রিপোর্ট করা অবস্থান',
      'issues_count': 'সমস্যাগুলি',
      'step1_title': 'যোগাযোগের তথ্য',
      'step2_title': 'অবস্থানের বিবরণ',
      'step3_title': 'সমস্যার বিবরণ',
      'step4_title': 'ছবি আপলোড করুন (ঐচ্ছিক)',
      'select_file': 'ফাইল নির্বাচন করুন',
      'or_text': 'অথবা',
      'open_camera': 'ক্যামেরা খুলুন এবং ছবি তুলুন',
      'submit_grievance': 'অভিযোগ জমা দিন',
      'profile_title': 'নাগরিক প্রোফাইল',
      'verified_citizen': 'যাচাইকৃত নাগরিক • চেন্নাই',
      'reported': 'রিপোর্ট করা হয়েছে',
      'in_progress_count': 'চলমান',
      'resolved_count': 'সমাধান হয়েছে',
      'phone_number': 'ফোন নম্বর',
      'email_address': 'ইমেল ঠিকানা',
      'settings_notif': 'সেটিংস এবং বিজ্ঞপ্তি',
      'logout': 'লগ আউট',
      'success_title': 'সমস্যা সফলভাবে দায়ের করা হয়েছে',
      'file_another_btn': 'আরেকটি অভিযোগ দায়ের করুন',
      'home_btn': 'হোম',
      'view_my_issues': 'আমার সমস্যাগুলি দেখুন',
      'reference_id': 'রেফারেন্স আইডি',
      'category_label': 'বিভাগ',
      'status_label': 'অবস্থা',
    },
    'gu': {
      'welcome_title': 'સોશિયલ સર્વમાં આપનું સ્વાગત છે',
      'welcome_sub': 'આગળ વધવા માટે તમારી પસંદગીની ભાષા પસંદ કરો.',
      'choose_language': 'ભાષા પસંદ કરો',
      'continue_btn': 'આગળ વધો',
      'enter_phone': 'તમારો ફોન નંબર દાખલ કરો',
      'phone_sub': 'અમે તમને ચકાસણી કોડ મોકલીશું',
      'enter_otp': 'ચકાસણી કોડ દાખલ કરો',
      'otp_sub': 'તમારા ફોન પર મોકલેલ 6-અંકનો કોડ દાખલ કરો',
      'verify': 'ચકાસો',
      'resend': 'કોડ ફરીથી મોકલો',
      'didnt_receive': 'કોડ મળ્યો નથી?',
      'nav_home': 'હોમ',
      'nav_issues': 'મારી ફરિયાદો',
      'nav_file': 'ફરિયાદ નોંધાવો',
      'nav_profile': 'પ્રોફાઇલ',
      'welcome_back': 'પુનઃ સ્વાગત છે',
      'hi_user': 'નમસ્તે ધ્યાન',
      'search_hint': 'શોધો',
      'welcome_card_title': 'સ્વાગત છે!',
      'welcome_card_sub': 'ચાલો તમારી નાગરિક ફરિયાદ નિવારણ શેડ્યૂલ કરીએ.',
      'ongoing_issues': 'ચાલુ ફરિયાદો',
      'view_all': 'બધું જુઓ',
      'no_issues_found': 'કોઈ સક્રિય ફરિયાદ નથી',
      'no_issues_sub': 'આ વિસ્તારમાં કોઈ સક્રિય ફરિયાદ મળી નથી.',
      'file_grievance_btn': 'ફરિયાદ નોંધાવો',
      'filter_grievances': 'ફિલ્ટર કરો',
      'reset_all': 'બધું રીસેટ કરો',
      'status': 'સ્થિતિ',
      'location_ward': 'સ્થળ / વોર્ડ',
      'dept_category': 'વિભાગ કેટેગરી',
      'apply_filters': 'ફિલ્ટર લાગુ કરો',
      'search_grievances_hint': 'ફરિયાદો, આઈડી, સ્થાન શોધો...',
      'status_all': 'બધા',
      'status_issued': 'નોંધાયેલ',
      'status_in_progress': 'પ્રગતિમાં',
      'status_resolved': 'ઉકેલાયેલ',
      'all_locations': 'બધા સ્થળો',
      'all_reported_locations': 'બધા નોંધાયેલા સ્થળો',
      'issues_count': 'ફરિયાદો',
      'step1_title': 'સંપર્ક માહિતી',
      'step2_title': 'સ્થળની વિગતો',
      'step3_title': 'ફરિયાદની વિગતો',
      'step4_title': 'ફોટો અપલોડ કરો (વૈકલ્પિક)',
      'select_file': 'ફાઇલ પસંદ કરો',
      'or_text': 'અથવા',
      'open_camera': 'કૅમેરા ખોલો અને ફોટો લો',
      'submit_grievance': 'ફરિયાદ સબમિટ કરો',
      'profile_title': 'નાગરિક પ્રોફાઇલ',
      'verified_citizen': 'ચકાસાયેલ નાગરિક • ચેન્નાઈ',
      'reported': 'નોંધાયેલ',
      'in_progress_count': 'પ્રગતિમાં',
      'resolved_count': 'ઉકેલાયેલ',
      'phone_number': 'ફોન નંબર',
      'email_address': 'ઈમેલ સરનામું',
      'settings_notif': 'સેટિંગ્સ અને સૂચનાઓ',
      'logout': 'લૉગ આઉટ',
      'success_title': 'સમસ્યા સફળતાપૂર્વક નોંધાઈ',
      'file_another_btn': 'બીજી ફરિયાદ નોંધાવો',
      'home_btn': 'હોમ',
      'view_my_issues': 'મારી ફરિયાદો જુઓ',
      'reference_id': 'સંદર્ભ આઈડી',
      'category_label': 'કેટેગરી',
      'status_label': 'સ્થિતિ',
    },
    'pa': {
      'welcome_title': 'ਸੋਸ਼ਲ ਸਰਵ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
      'welcome_sub': 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ।',
      'choose_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'continue_btn': 'ਜਾਰੀ ਰੱਖੋ',
      'enter_phone': 'ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ',
      'phone_sub': 'ਅਸੀਂ ਤੁਹਾਨੂੰ ਇੱਕ ਪੁਸ਼ਟੀਕਰਨ ਕੋਡ ਭੇਜਾਂਗੇ',
      'enter_otp': 'ਪੁਸ਼ਟੀਕਰਨ ਕੋਡ ਦਰਜ ਕਰੋ',
      'otp_sub': 'ਆਪਣੇ ਫ਼ੋਨ ਤੇ ਭੇਜਿਆ 6-ਅੰਕਾਂ ਦਾ ਕੋਡ ਦਰਜ ਕਰੋ',
      'verify': 'ਪੁਸ਼ਟੀ ਕਰੋ',
      'resend': 'ਕੋਡ ਦੁਬਾਰਾ ਭੇਜੋ',
      'didnt_receive': 'ਕੋਡ ਨਹੀਂ ਮਿਲਿਆ?',
      'nav_home': 'ਹੋਮ',
      'nav_issues': 'ਮੇਰੀਆਂ ਸਮੱਸਿਆਵਾਂ',
      'nav_file': 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
      'nav_profile': 'ਪ੍ਰੋਫਾਈਲ',
      'welcome_back': 'ਜੀ ਆਇਆਂ ਨੂੰ',
      'hi_user': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਧਿਆਨ',
      'search_hint': 'ਖੋਜ ਕਰੋ',
      'welcome_card_title': 'ਜੀ ਆਇਆਂ ਨੂੰ!',
      'welcome_card_sub': 'ਆਓ ਤੁਹਾਡੇ ਨਾਗਰਿਕ ਮਸਲੇ ਦਾ ਹੱਲ ਤਹਿ ਕਰੀਏ।',
      'ongoing_issues': 'ਚੱਲ ਰਹੀਆਂ ਸਮੱਸਿਆਵਾਂ',
      'view_all': 'ਸਾਰੇ ਦੇਖੋ',
      'no_issues_found': 'ਕੋਈ ਚੱਲ ਰਹੀ ਸਮੱਸਿਆ ਨਹੀਂ',
      'no_issues_sub': 'ਇਸ ਖੇਤਰ ਵਿੱਚ ਕੋਈ ਸ਼ਿਕਾਇਤ ਨਹੀਂ ਮਿਲੀ।',
      'file_grievance_btn': 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
      'filter_grievances': 'ਫਿਲਟਰ ਕਰੋ',
      'reset_all': 'ਸਾਰੇ ਰੀਸੈੱਟ ਕਰੋ',
      'status': 'ਸਥਿਤੀ',
      'location_ward': 'ਸਥਾਨ / ਵਾਰਡ',
      'dept_category': 'ਵਿਭਾਗ ਸ਼੍ਰੇਣੀ',
      'apply_filters': 'ਫਿਲਟਰ ਲਾਗੂ ਕਰੋ',
      'search_grievances_hint': 'ਸ਼ਿਕਾਇਤਾਂ, ਆਈਡੀ, ਸਥਾਨ ਖੋਜੋ...',
      'status_all': 'ਸਾਰੇ',
      'status_issued': 'ਦਰਜ',
      'status_in_progress': 'ਜਾਰੀ ਹੈ',
      'status_resolved': 'ਹੱਲ ਹੋ ਗਿਆ',
      'all_locations': 'ਸਾਰੇ ਸਥਾਨ',
      'all_reported_locations': 'ਸਾਰੇ ਦਰਜ ਕੀਤੇ ਸਥਾਨ',
      'issues_count': 'ਸਮੱਸਿਆਵਾਂ',
      'step1_title': 'ਸੰਪਰਕ ਜਾਣਕਾਰੀ',
      'step2_title': 'ਸਥਾਨ ਦਾ ਵੇਰਵਾ',
      'step3_title': 'ਮਸਲੇ ਦਾ ਵੇਰਵਾ',
      'step4_title': 'ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ (ਵਿਕਲਪਿਕ)',
      'select_file': 'ਫਾਈਲ ਚੁਣੋ',
      'or_text': 'ਜਾਂ',
      'open_camera': 'ਕੈਮਰਾ ਖੋਲ੍ਹੋ ਅਤੇ ਫੋਟੋ ਖਿੱਚੋ',
      'submit_grievance': 'ਸ਼ਿਕਾਇਤ ਜਮ੍ਹਾਂ ਕਰੋ',
      'profile_title': 'ਨਾਗਰਿਕ ਪ੍ਰੋਫਾਈਲ',
      'verified_citizen': 'ਪੁਸ਼ਟੀ ਕੀਤਾ ਨਾਗਰਿਕ • ਚੇਨਈ',
      'reported': 'ਦਰਜ ਕੀਤਾ',
      'in_progress_count': 'ਜਾਰੀ ਹੈ',
      'resolved_count': 'ਹੱਲ ਹੋ ਗਿਆ',
      'phone_number': 'ਫ਼ੋਨ ਨੰਬਰ',
      'email_address': 'ਈਮੇਲ ਪਤਾ',
      'settings_notif': 'ਸੈਟਿੰਗਾਂ ਅਤੇ ਸੂਚਨਾਵਾਂ',
      'logout': 'ਲੌਗ ਆਉਟ',
      'success_title': 'ਸਮੱਸਿਆ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਕੀਤੀ ਗਈ',
      'file_another_btn': 'ਇੱਕ ਹੋਰ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
      'home_btn': 'ਹੋਮ',
      'view_my_issues': 'ਮੇਰੀਆਂ ਸਮੱਸਿਆਵਾਂ ਦੇਖੋ',
      'reference_id': 'ਹਵਾਲਾ ਆਈਡੀ',
      'category_label': 'ਸ਼੍ਰੇਣੀ',
      'status_label': 'ਸਥਿਤੀ',
    },
  };
}
