"""initial schema

Revision ID: 929cadbb3720
Revises: 
Create Date: 2026-08-22 21:39:27.233095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '929cadbb3720'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_areas',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Enum('state', 'district', 'block', 'gp', 'village', name='administrative_level'), nullable=False),
    sa.Column('lgd_code', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['administrative_areas.id'], name=op.f('fk_administrative_areas_parent_id_administrative_areas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administrative_areas')),
    sa.UniqueConstraint('lgd_code', name=op.f('uq_administrative_areas_lgd_code'))
    )
    op.create_index(op.f('ix_administrative_areas_level'), 'administrative_areas', ['level'], unique=False)
    op.create_index(op.f('ix_administrative_areas_parent_id'), 'administrative_areas', ['parent_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('university', 'industry', name='organization_type'), nullable=False),
    sa.Column('domain_tags', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_type'), 'organizations', ['type'], unique=False)
    op.create_table('otp_codes',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('themes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_themes')),
    sa.UniqueConstraint('name', name=op.f('uq_themes_name'))
    )
    op.create_table('clusters',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'resolved', name='cluster_status'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_clusters_theme_id_themes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clusters'))
    )
    op.create_index(op.f('ix_clusters_theme_id'), 'clusters', ['theme_id'], unique=False)
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('citizen', 'officer', 'analyst', 'admin', name='user_role'), nullable=False),
    sa.Column('administrative_area_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['administrative_area_id'], ['administrative_areas.id'], name=op.f('fk_users_administrative_area_id_administrative_areas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_administrative_area_id'), 'users', ['administrative_area_id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('challenges',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'open', 'duplicate', 'resolved', name='challenge_status'), nullable=False),
    sa.Column('submitted_by_id', sa.Uuid(), nullable=False),
    sa.Column('administrative_area_id', sa.Uuid(), nullable=False),
    sa.Column('pin_code', sa.String(length=6), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['administrative_area_id'], ['administrative_areas.id'], name=op.f('fk_challenges_administrative_area_id_administrative_areas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_challenges_cluster_id_clusters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['challenges.id'], name=op.f('fk_challenges_duplicate_of_id_challenges'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_challenges_submitted_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    op.create_index(op.f('ix_challenges_administrative_area_id'), 'challenges', ['administrative_area_id'], unique=False)
    op.create_index(op.f('ix_challenges_cluster_id'), 'challenges', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_challenges_duplicate_of_id'), 'challenges', ['duplicate_of_id'], unique=False)
    op.create_index(op.f('ix_challenges_status'), 'challenges', ['status'], unique=False)
    op.create_index(op.f('ix_challenges_submitted_by_id'), 'challenges', ['submitted_by_id'], unique=False)
    op.create_table('projects',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='project_status'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_projects_cluster_id_clusters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_cluster_id'), 'projects', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('consortiums',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'confirmed', 'dissolved', name='consortium_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_consortiums_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consortiums'))
    )
    op.create_index(op.f('ix_consortiums_project_id'), 'consortiums', ['project_id'], unique=True)
    op.create_table('duplicate_candidates',
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_challenge_id', sa.Uuid(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_challenge_id'], ['challenges.id'], name=op.f('fk_duplicate_candidates_candidate_challenge_id_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_duplicate_candidates_challenge_id_challenges'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_candidates')),
    sa.UniqueConstraint('challenge_id', 'candidate_challenge_id', name='uq_duplicate_candidate_pair')
    )
    op.create_index(op.f('ix_duplicate_candidates_candidate_challenge_id'), 'duplicate_candidates', ['candidate_challenge_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_challenge_id'), 'duplicate_candidates', ['challenge_id'], unique=False)
    op.create_table('duplicate_decisions',
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_challenge_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('duplicate', 'not_duplicate', name='duplicate_decision_type'), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_challenge_id'], ['challenges.id'], name=op.f('fk_duplicate_decisions_candidate_challenge_id_challenges'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_duplicate_decisions_challenge_id_challenges'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_duplicate_decisions_reviewer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_decisions'))
    )
    op.create_index(op.f('ix_duplicate_decisions_candidate_challenge_id'), 'duplicate_decisions', ['candidate_challenge_id'], unique=False)
    op.create_index(op.f('ix_duplicate_decisions_challenge_id'), 'duplicate_decisions', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_duplicate_decisions_reviewer_id'), 'duplicate_decisions', ['reviewer_id'], unique=False)
    op.create_table('solutions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_solutions_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solutions'))
    )
    op.create_index(op.f('ix_solutions_project_id'), 'solutions', ['project_id'], unique=False)
    op.create_table('consortium_members',
    sa.Column('consortium_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['consortium_id'], ['consortiums.id'], name=op.f('fk_consortium_members_consortium_id_consortiums'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_consortium_members_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consortium_members')),
    sa.UniqueConstraint('consortium_id', 'organization_id', name='uq_consortium_member_pair')
    )
    op.create_index(op.f('ix_consortium_members_consortium_id'), 'consortium_members', ['consortium_id'], unique=False)
    op.create_index(op.f('ix_consortium_members_organization_id'), 'consortium_members', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    # HNSW indexes for vector similarity search (cosine distance).
    op.execute(
        "CREATE INDEX ix_challenges_embedding_hnsw ON challenges "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_clusters_embedding_hnsw ON clusters "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_organizations_embedding_hnsw ON organizations "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_organizations_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_clusters_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_challenges_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consortium_members_organization_id'), table_name='consortium_members')
    op.drop_index(op.f('ix_consortium_members_consortium_id'), table_name='consortium_members')
    op.drop_table('consortium_members')
    op.drop_index(op.f('ix_solutions_project_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_duplicate_decisions_reviewer_id'), table_name='duplicate_decisions')
    op.drop_index(op.f('ix_duplicate_decisions_challenge_id'), table_name='duplicate_decisions')
    op.drop_index(op.f('ix_duplicate_decisions_candidate_challenge_id'), table_name='duplicate_decisions')
    op.drop_table('duplicate_decisions')
    op.drop_index(op.f('ix_duplicate_candidates_challenge_id'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_candidate_challenge_id'), table_name='duplicate_candidates')
    op.drop_table('duplicate_candidates')
    op.drop_index(op.f('ix_consortiums_project_id'), table_name='consortiums')
    op.drop_table('consortiums')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_cluster_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_challenges_submitted_by_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_status'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_duplicate_of_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_cluster_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_administrative_area_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_administrative_area_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clusters_theme_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_table('themes')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_organizations_type'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_administrative_areas_parent_id'), table_name='administrative_areas')
    op.drop_index(op.f('ix_administrative_areas_level'), table_name='administrative_areas')
    op.drop_table('administrative_areas')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS vector")
