# -*- coding: utf-8 -*-

English = [
"The drain running behind our houses has been clogged for weeks and now overflows onto the lane every time it rains.",
"Sewage from the main line has been backing up into the ground floor of two houses on our street.",
"The community toilet block in our basti has had no water connection for flushing since last month.",
"A broken sewer pipe near the market has been leaking wastewater onto the road for over ten days.",
"Our colony's septic tank was supposed to be desludged six months ago and the request is still pending with the municipality.",
"Stagnant wastewater has been collecting behind the row of shops, breeding mosquitoes for the whole neighbourhood.",
"The public toilet near the bus stand has been locked for repairs for over two months with no alternative provided.",
"Open drains along our street have not been covered despite repeated requests, and children have to jump over them to reach school.",
"The underground sewer line serving our block collapsed last monsoon and has only been patched temporarily since.",
"Wastewater from the nearby factory outlet has been mixing with the open drain that passes right through our residential lane.",
"Our lane's manhole cover has been missing for weeks, and at night it has become a real hazard for pedestrians.",
"The sewage treatment plant serving our town has reportedly been operating at a fraction of its capacity, causing overflow downstream.",
"Households in the older part of the colony still practice open defecation because the promised community toilets were never completed.",
"A blocked storm drain outside our house means every rain now floods the ground floor with dirty water.",
"The septic tank truck we called through the municipal helpline never showed up despite three separate bookings.",
"Toilets built under the sanitation scheme in our village lack any functioning water supply to actually use them.",
"The sewer line connecting our street to the main network has never been laid, so waste simply collects in an open pit.",
"Residents near the drainage outfall say the smell has become unbearable, especially during the evenings.",
"The community toilet complex has only two functioning stalls out of ten, and both lack proper doors.",
"A cracked sewage pipe beneath the road has been seeping into the adjoining well used by nearby households.",
"Our ward's sanitation worker has stopped visiting the open drains for desilting since the contract changeover.",
"The public urinal near the market has no drainage connection at all, so waste simply pools on the ground around it.",
"Children in our lane play near an open sewage channel because there is no barrier or covering of any kind.",
"The school toilet block built two years ago has never been connected to any sewer line or septic system.",
"Our housing block's shared toilet facility has had a broken door and no functioning flush for over a month.",
"Sewage overflow from a nearby residential complex has been entering our lane's open drain for the past few weeks.",
"The desludging vehicle assigned to our zone reportedly skipped our colony three cleaning cycles in a row.",
"A collapsed drain cover near the temple has left an open pit that fills with wastewater after every rain.",
"The community toilet built for our slum has been shut since the caretaker responsible for cleaning left the job.",
"Wastewater from the dairy behind our lane flows directly into the open drain without any treatment.",
"Our village still lacks a functioning underground drainage system, so all wastewater runs along open channels through the settlement.",
"The sewer connection application for our newly built house has been pending at the municipal office for nearly a year.",
"A broken sanitary line near the school has been a source of foul smell and mosquito breeding for the entire term.",
"The public toilet complex charges a fee but has not had running water for cleaning in over three weeks.",
"Our street's drainage has been redirected by an unauthorised construction next door, causing wastewater to pool outside our gate.",
"The vacuum tanker meant to clear the choked sewer near the market has not been dispatched despite repeated complaints.",
"Open defecation persists in the outskirts of our village because the nearest functioning toilet is nearly half a kilometre away.",
"A drainage pipe running under the road has cracked, letting sewage seep into the soil near the handpump used by residents.",
"The municipal sweeper responsible for our lane has stopped clearing the open drain, and it is now overflowing after every rain.",
"Our building's shared septic system has not been serviced in years, and the overflow now seeps into the compound.",
]

Hindi = [
"हमारे घरों के पीछे बहने वाला नाला हफ्तों से जाम है और अब हर बारिश में गली में बहकर आ जाता है।",
"मुख्य लाइन से सीवेज हमारी गली के दो घरों की ग्राउंड फ्लोर में वापस आने लगा है।",
"हमारी बस्ती के सामुदायिक शौचालय ब्लॉक में पिछले महीने से फ्लशिंग के लिए पानी का कनेक्शन नहीं है।",
"बाजार के पास एक टूटी सीवर पाइप से दस दिनों से ज्यादा समय से गंदा पानी सड़क पर बह रहा है।",
"हमारी कॉलोनी के सेप्टिक टैंक की सफाई छह महीने पहले होनी थी और नगरपालिका के पास यह अनुरोध अभी भी लंबित है।",
"दुकानों की कतार के पीछे जमा गंदा पानी पूरे मोहल्ले के लिए मच्छर पैदा कर रहा है।",
"बस स्टैंड के पास सार्वजनिक शौचालय मरम्मत के लिए दो महीने से ज्यादा समय से बंद है, बिना किसी विकल्प के।",
"बार-बार अनुरोध के बावजूद हमारी गली में खुले नाले ढके नहीं गए हैं, और बच्चों को स्कूल पहुंचने के लिए उन्हें फांदना पड़ता है।",
"हमारे ब्लॉक की भूमिगत सीवर लाइन पिछले मानसून में ढह गई थी और तब से सिर्फ अस्थायी तौर पर पैच की गई है।",
"पास की फैक्ट्री के आउटलेट से निकलने वाला गंदा पानी उस खुले नाले में मिल रहा है जो सीधे हमारी रिहायशी गली से होकर गुजरता है।",
"हमारी गली का मैनहोल ढक्कन हफ्तों से गायब है, और रात में यह राहगीरों के लिए एक वास्तविक खतरा बन गया है।",
"हमारे शहर का सीवेज ट्रीटमेंट प्लांट कथित तौर पर अपनी क्षमता के एक छोटे हिस्से पर ही चल रहा है, जिससे नीचे की ओर ओवरफ्लो हो रहा है।",
"कॉलोनी के पुराने हिस्से के घर अभी भी खुले में शौच करते हैं क्योंकि वादा किए गए सामुदायिक शौचालय कभी पूरे नहीं हुए।",
"हमारे घर के बाहर एक बंद तूफानी नाला है, जिसकी वजह से अब हर बारिश में ग्राउंड फ्लोर गंदे पानी से भर जाता है।",
"नगरपालिका हेल्पलाइन के जरिए बुलाई गई सेप्टिक टैंक की गाड़ी तीन अलग-अलग बुकिंग के बावजूद कभी नहीं आई।",
"हमारे गांव में स्वच्छता योजना के तहत बनाए गए शौचालयों में उपयोग के लिए कोई काम करता पानी कनेक्शन ही नहीं है।",
"हमारी गली को मुख्य नेटवर्क से जोड़ने वाली सीवर लाइन कभी बिछाई ही नहीं गई, इसलिए कचरा एक खुले गड्ढे में जमा होता रहता है।",
"जल निकासी के आउटफॉल के पास रहने वाले निवासियों का कहना है कि खासकर शाम के समय बदबू असहनीय हो गई है।",
"सामुदायिक शौचालय परिसर में दस में से सिर्फ दो शौचालय काम कर रहे हैं, और दोनों में ठीक से दरवाजे भी नहीं हैं।",
"सड़क के नीचे एक फटी सीवेज पाइप पास के उस कुएं में रिस रही है जिसका इस्तेमाल आसपास के घर करते हैं।",
"हमारे वार्ड का सफाई कर्मचारी ठेका बदलने के बाद से खुले नालों की सफाई के लिए आना बंद कर चुका है।",
"बाजार के पास सार्वजनिक मूत्रालय का जल निकासी से कोई कनेक्शन ही नहीं है, इसलिए कचरा उसके चारों ओर जमीन पर ही जमा होता रहता है।",
"हमारी गली के बच्चे एक खुले सीवेज चैनल के पास खेलते हैं क्योंकि वहां किसी तरह की कोई बैरियर या ढकाव नहीं है।",
"दो साल पहले बना स्कूल का शौचालय ब्लॉक कभी किसी सीवर लाइन या सेप्टिक सिस्टम से जुड़ा ही नहीं गया।",
"हमारे हाउसिंग ब्लॉक की साझा शौचालय सुविधा का दरवाजा टूटा है और एक महीने से ज्यादा समय से फ्लश काम नहीं कर रहा।",
"पास के एक रिहायशी परिसर से सीवेज ओवरफ्लो पिछले कुछ हफ्तों से हमारी गली के खुले नाले में आ रहा है।",
"हमारे क्षेत्र के लिए तय की गई सफाई गाड़ी लगातार तीन सफाई चक्रों में हमारी कॉलोनी को छोड़ गई।",
"मंदिर के पास एक धंसा हुआ नाला ढक्कन एक खुला गड्ढा छोड़ गया है जो हर बारिश के बाद गंदे पानी से भर जाता है।",
"हमारी झुग्गी के लिए बना सामुदायिक शौचालय तब से बंद है जब से सफाई की जिम्मेदारी संभालने वाला केयरटेकर नौकरी छोड़ गया।",
"हमारी गली के पीछे स्थित डेयरी से निकलने वाला गंदा पानी बिना किसी उपचार के सीधे खुले नाले में बहता है।",
"हमारे गांव में अभी भी कोई काम करता भूमिगत जल निकासी सिस्टम नहीं है, इसलिए सारा गंदा पानी बस्ती के खुले चैनलों से होकर बहता है।",
"हमारे नए बने घर के लिए सीवर कनेक्शन का आवेदन लगभग एक साल से नगरपालिका कार्यालय में लंबित है।",
"स्कूल के पास एक टूटी हुई सैनिटरी लाइन पूरे सत्र के दौरान बदबू और मच्छर पैदा करने का स्रोत बनी रही।",
"सार्वजनिक शौचालय परिसर शुल्क तो लेता है लेकिन तीन हफ्तों से ज्यादा समय से सफाई के लिए बहता पानी नहीं है।",
"पड़ोस में एक अनधिकृत निर्माण ने हमारी गली की जल निकासी को मोड़ दिया है, जिससे गंदा पानी हमारे गेट के बाहर जमा हो रहा है।",
"बाजार के पास जाम सीवर को साफ करने वाला वैक्यूम टैंकर बार-बार शिकायत के बावजूद नहीं भेजा गया।",
"हमारे गांव के बाहरी इलाके में खुले में शौच अब भी जारी है क्योंकि नजदीकी काम करता शौचालय लगभग आधा किलोमीटर दूर है।",
"सड़क के नीचे से गुजरने वाली एक जल निकासी पाइप में दरार आ गई है, जिससे सीवेज उस हैंडपंप के पास की मिट्टी में रिस रहा है जिसका निवासी इस्तेमाल करते हैं।",
"हमारी गली की जिम्मेदारी संभालने वाला नगरपालिका सफाईकर्मी खुले नाले की सफाई बंद कर चुका है, और अब हर बारिश के बाद यह ओवरफ्लो हो जाता है।",
"हमारी इमारत का साझा सेप्टिक सिस्टम सालों से सर्विस नहीं हुआ, और अब इसका ओवरफ्लो परिसर में रिसने लगा है।",
]

Hinglish = [
"Hamare ghar ke peeche behne wala naala hafton se jam hai aur ab har baarish mein gali mein behkar aa jaata hai.",
"Main line se sewage hamari gali ke do gharon ki ground floor mein wapas aane laga hai.",
"Hamari basti ke community toilet block mein pichle mahine se flushing ke liye paani ka connection nahi hai.",
"Market ke paas ek tooti sewer pipe se das dinon se zyada time se ganda paani sadak par beh raha hai.",
"Hamari colony ke septic tank ki safai chhe mahine pehle honi thi aur municipality ke paas yeh request abhi bhi pending hai.",
"Dukano ki queue ke peeche jama ganda paani poore mohalle ke liye machhar paida kar raha hai.",
"Bus stand ke paas public toilet repair ke liye do mahine se zyada time se band hai, bina kisi alternative ke.",
"Baar-baar request ke bawajood hamari gali mein khule naale dhake nahi gaye hain, aur bachchon ko school pahunchne ke liye unhe phaandna padta hai.",
"Hamare block ki underground sewer line pichle monsoon mein dhah gayi thi aur tab se sirf temporary tarike se patch ki gayi hai.",
"Paas ki factory ke outlet se nikalne wala ganda paani us khule naale mein mil raha hai jo seedha hamari residential gali se hokar guzarta hai.",
"Hamari gali ka manhole cover hafton se gayab hai, aur raat mein yeh pedestrians ke liye ek real hazard ban gaya hai.",
"Hamare shehar ka sewage treatment plant reportedly apni capacity ke ek chhote hisse par hi chal raha hai, jisse neeche ki taraf overflow ho raha hai.",
"Colony ke purane hisse ke ghar abhi bhi khule mein shauch karte hain kyunki promise kiye gaye community toilets kabhi complete nahi hue.",
"Hamare ghar ke bahar ek band storm drain hai, jiski wajah se ab har baarish mein ground floor ganda paani se bhar jaata hai.",
"Municipality helpline ke through bulayi gayi septic tank ki gaadi teen alag-alag bookings ke bawajood kabhi nahi aayi.",
"Hamare gaon mein sanitation scheme ke tahat banaye gaye toilets mein use ke liye koi functioning water connection hi nahi hai.",
"Hamari gali ko main network se jodne wali sewer line kabhi bichhayi hi nahi gayi, isliye waste ek khule gaddhe mein jama hota rehta hai.",
"Drainage outfall ke paas rehne wale residents ka kehna hai ki khaaskar shaam ke time smell unbearable ho gayi hai.",
"Community toilet complex mein das mein se sirf do stalls kaam kar rahe hain, aur dono mein theek se doors bhi nahi hain.",
"Sadak ke neeche ek phati sewage pipe us paas wale kuen mein rees rahi hai jise aas-paas ke ghar use karte hain.",
"Hamare ward ka safai worker contract change hone ke baad se khule naalon ki desilting ke liye aana band kar chuka hai.",
"Market ke paas public urinal ka drainage se koi connection hi nahi hai, isliye waste uske aas-paas zameen par hi jama hota rehta hai.",
"Hamari gali ke bachche ek khule sewage channel ke paas khelte hain kyunki wahan kisi tarah ka koi barrier ya covering nahi hai.",
"Do saal pehle bana school ka toilet block kabhi kisi sewer line ya septic system se juda hi nahi gaya.",
"Hamare housing block ki shared toilet facility ka darwaza toota hai aur ek mahine se zyada time se flush kaam nahi kar raha.",
"Paas ke ek residential complex se sewage overflow pichle kuch hafton se hamari gali ke khule naale mein aa raha hai.",
"Hamare zone ke liye assign ki gayi desludging vehicle lagatar teen cleaning cycles mein hamari colony ko skip kar gayi.",
"Mandir ke paas ek dhansa hua naala cover ek khula gaddha chhod gaya hai jo har baarish ke baad ganda paani se bhar jaata hai.",
"Hamari slum ke liye bana community toilet tab se band hai jab se safai ki responsibility sambhalne wala caretaker job chhod gaya.",
"Hamari gali ke peeche sthit dairy se nikalne wala ganda paani bina kisi treatment ke seedha khule naale mein behta hai.",
"Hamare gaon mein abhi bhi koi functioning underground drainage system nahi hai, isliye saara ganda paani basti ke khule channels se hokar behta hai.",
"Hamare naye bane ghar ke liye sewer connection ka application lagbhag ek saal se municipal office mein pending hai.",
"School ke paas ek tooti hui sanitary line poore session ke dauran badbu aur machhar paida karne ka source bani rahi.",
"Public toilet complex fee to leta hai lekin teen hafton se zyada time se safai ke liye behta paani nahi hai.",
"Pados mein ek unauthorised construction ne hamari gali ki drainage ko mod diya hai, jisse ganda paani hamare gate ke bahar jama ho raha hai.",
"Market ke paas jam sewer ko saaf karne wala vacuum tanker baar-baar complaint ke bawajood nahi bheja gaya.",
"Hamare gaon ke bahri ilake mein khule mein shauch ab bhi jaari hai kyunki nazdeeki functioning toilet lagbhag aadha kilometer door hai.",
"Sadak ke neeche se guzarne wali ek drainage pipe mein crack aa gaya hai, jisse sewage us handpump ke paas ki mitti mein rees raha hai jise residents use karte hain.",
"Hamari gali ki responsibility sambhalne wala municipal sweeper khule naale ki safai band kar chuka hai, aur ab har baarish ke baad yeh overflow ho jaata hai.",
"Hamari building ka shared septic system saalon se serviced nahi hua, aur ab uska overflow compound mein reesne laga hai.",
]
