# -*- coding: utf-8 -*-

English = [
"Our taps have remained dry since Monday even though the neighbouring street is receiving water on schedule.",
"The tanker that used to visit our colony twice a week has not come in over ten days.",
"Water from the pipeline has turned a faint yellow colour for the past few days, and we are still using it to cook.",
"Pressure at the community tap has dropped so low that filling one bucket now takes nearly twenty minutes.",
"The borewell that our hamlet depends on has run dry earlier than usual this year.",
"Households at the far end of our lane get barely a trickle while those near the main road get full supply.",
"The overhead tank serving our block has not been cleaned in what residents say is at least three years.",
"Water supply now comes for only forty minutes in the early morning, down from the two hours we used to get.",
"A new connection application submitted six months ago has still not resulted in a functioning pipeline reaching our house.",
"The well that several families in our basti rely on has started tasting distinctly salty since the summer.",
"Water tankers meant for our ward have reportedly been diverted to a neighbouring, more influential area.",
"The pipeline burst near the main road three weeks ago and water has been leaking out ever since instead of reaching homes.",
"Our village has had no reliable source of drinking water since the nearest handpump broke down last month.",
"There has been visible sediment in the water coming from the tap for over a week, and it does not settle even after boiling.",
"The public water point installed under the scheme has never actually been connected to a functioning line.",
"Summer supply timings were cut without any notice, and elderly residents now queue before dawn to fill containers.",
"The desalination unit installed in our coastal village has been non-functional for months, forcing us back to buying water.",
"Water in our area smells strongly of chlorine some days and of nothing at all on others, with no consistency in treatment.",
"The new housing colony has grown but the water pipeline network was never extended to cover the additional houses.",
"A private tanker mafia reportedly controls water access in our slum, charging rates far above what the municipal supply should cost.",
"Our hillside hamlet has to fetch water from a spring nearly two kilometres away since the pipeline scheme stalled midway.",
"The water quality testing that was supposed to happen after complaints of a metallic taste never took place.",
"Three of the five public handpumps in our ward have been non-functional for over a year with no repair visit scheduled.",
"The tap connection meter appears to be running even on days when water pressure barely reaches our house.",
"Groundwater levels in our village have dropped so much that even functioning borewells now yield water for only an hour a day.",
"The municipal supply line running through our colony was damaged during roadwork and has not been restored since.",
"Water tastes different depending on which part of our street you draw it from, suggesting contamination somewhere along the line.",
"Our request for a new borewell to replace the collapsed one has been pending at the panchayat for eight months.",
"The reservoir supplying our town has been running low and the rationing schedule keeps shifting without prior announcement.",
"Residents in the older part of the colony still rely on a single shared standpipe that serves nearly forty households.",
"Since the treatment plant upgrade, the water reaching our tap has an unusual smell that was not there before.",
"The tanker driver assigned to our route has been skipping our lane and only serving the main road households.",
"There is no water connection at all in the newly resettled part of our village despite promises made two years ago.",
"The check dam meant to recharge our aquifer was never completed, and wells nearby have started drying faster each summer.",
"Our school and the surrounding homes share one borewell, which has started giving intermittent supply this month.",
"A leak in the underground pipeline near the market has been running for weeks, wasting water while our taps stay dry.",
"The water supply schedule posted by the municipality does not match what actually happens at our tap most days.",
"Iron content in our tap water has stained clothes and containers for months without any explanation from the water department.",
"Our hamlet's only source, a hand-dug well, has become unusable after debris fell into it during the last storm.",
"Water carts promised for the dry season have not been deployed even though the tanker route map lists our village.",
]

Hindi = [
"सोमवार से हमारे नल सूखे पड़े हैं जबकि पड़ोस की गली में तय समय पर पानी आ रहा है।",
"जो टैंकर हमारी कॉलोनी में हफ्ते में दो बार आता था, वह दस दिनों से ज्यादा समय से नहीं आया।",
"पिछले कुछ दिनों से पाइपलाइन का पानी हल्का पीला दिख रहा है, फिर भी हम उसी से खाना बना रहे हैं।",
"सामुदायिक नल पर दबाव इतना कम हो गया है कि अब एक बाल्टी भरने में लगभग बीस मिनट लग जाते हैं।",
"हमारे मोहल्ले का बोरवेल इस साल हमेशा से पहले सूख गया है।",
"हमारी गली के अंत में बसे घरों को मुश्किल से बूंद-बूंद पानी मिलता है जबकि मुख्य सड़क के पास पूरा सप्लाई मिलता है।",
"हमारे ब्लॉक की ओवरहेड टंकी निवासियों के अनुसार कम से कम तीन साल से साफ नहीं की गई है।",
"अब पानी की आपूर्ति सुबह सिर्फ चालीस मिनट के लिए आती है, जबकि पहले दो घंटे मिलते थे।",
"छह महीने पहले जमा किए गए नए कनेक्शन के आवेदन के बावजूद अभी तक हमारे घर तक कोई काम करती पाइपलाइन नहीं पहुंची है।",
"हमारी बस्ती के कई परिवार जिस कुएं पर निर्भर हैं, उसका पानी गर्मियों से काफी नमकीन स्वाद देने लगा है।",
"हमारे वार्ड के लिए तय टैंकर कथित तौर पर एक पड़ोसी, ज्यादा प्रभावशाली इलाके में मोड़ दिए गए हैं।",
"मुख्य सड़क के पास पाइपलाइन तीन हफ्ते पहले फट गई थी और तब से पानी घरों तक पहुंचने के बजाय बहता जा रहा है।",
"पिछले महीने नजदीकी हैंडपंप खराब होने के बाद से हमारे गांव में पीने के पानी का कोई भरोसेमंद स्रोत नहीं बचा।",
"नल से आने वाले पानी में एक हफ्ते से साफ दिखने वाला तलछट है, जो उबालने के बाद भी नहीं बैठता।",
"योजना के तहत लगाया गया सार्वजनिक जल बिंदु कभी किसी काम करती लाइन से जुड़ा ही नहीं गया।",
"बिना किसी सूचना के गर्मियों की आपूर्ति का समय घटा दिया गया, और अब बुजुर्ग निवासी बर्तन भरने के लिए भोर से पहले कतार में लगते हैं।",
"हमारे तटीय गांव में लगाई गई डिसैलिनेशन यूनिट महीनों से बंद पड़ी है, जिससे हमें फिर से पानी खरीदना पड़ रहा है।",
"हमारे इलाके का पानी कुछ दिन क्लोरीन की तेज गंध देता है और कुछ दिन बिल्कुल गंधहीन, ट्रीटमेंट में कोई एकरूपता नहीं दिखती।",
"नई हाउसिंग कॉलोनी तो बस गई लेकिन पाइपलाइन नेटवर्क को कभी अतिरिक्त घरों तक बढ़ाया ही नहीं गया।",
"हमारी झुग्गी में कथित तौर पर एक निजी टैंकर माफिया पानी की पहुंच को नियंत्रित करता है, जो नगरपालिका आपूर्ति की कीमत से कहीं ज्यादा दर वसूलता है।",
"पाइपलाइन योजना बीच में अटक जाने के बाद हमारे पहाड़ी मोहल्ले को लगभग दो किलोमीटर दूर एक झरने से पानी लाना पड़ता है।",
"धातु जैसे स्वाद की शिकायतों के बाद जो पानी की गुणवत्ता जांच होनी थी, वह कभी हुई ही नहीं।",
"हमारे वार्ड के पांच में से तीन सार्वजनिक हैंडपंप एक साल से ज्यादा समय से खराब पड़े हैं और मरम्मत का कोई दौरा तय नहीं है।",
"नल कनेक्शन का मीटर उन दिनों भी चलता दिखता है जब पानी का दबाव मुश्किल से हमारे घर तक पहुंचता है।",
"हमारे गांव में भूजल स्तर इतना गिर गया है कि चालू बोरवेल भी अब दिन में सिर्फ एक घंटे के लिए पानी दे रहे हैं।",
"हमारी कॉलोनी से गुजरने वाली नगरपालिका आपूर्ति लाइन सड़क के काम के दौरान क्षतिग्रस्त हो गई थी और तब से बहाल नहीं हुई।",
"हमारी गली के किस हिस्से से पानी भरा जाए, इसके आधार पर उसका स्वाद अलग होता है, जो कहीं न कहीं संदूषण का संकेत देता है।",
"ढह गए बोरवेल की जगह नया बोरवेल लगाने का हमारा अनुरोध पंचायत में आठ महीने से लंबित है।",
"हमारे शहर को पानी देने वाला जलाशय कम हो गया है और राशनिंग का समय बिना पूर्व सूचना के लगातार बदलता रहता है।",
"कॉलोनी के पुराने हिस्से के निवासी अब भी एक ही साझा स्टैंडपाइप पर निर्भर हैं जो लगभग चालीस घरों को सेवा देता है।",
"ट्रीटमेंट प्लांट के अपग्रेड के बाद से हमारे नल तक पहुंचने वाले पानी में एक अजीब गंध आ रही है जो पहले नहीं थी।",
"हमारे रूट पर तैनात टैंकर चालक हमारी गली को छोड़कर सिर्फ मुख्य सड़क के घरों को ही पानी दे रहा है।",
"दो साल पहले किए गए वादों के बावजूद हमारे गांव के नए पुनर्वासित हिस्से में अभी तक कोई जल कनेक्शन ही नहीं है।",
"हमारे जलभृत को रिचार्ज करने वाला चेक डैम कभी पूरा नहीं हुआ, और आस-पास के कुएं हर गर्मी में जल्दी सूखने लगे हैं।",
"हमारा स्कूल और आस-पास के घर एक ही बोरवेल साझा करते हैं, जिसने इस महीने से रुक-रुक कर आपूर्ति देनी शुरू कर दी है।",
"बाजार के पास भूमिगत पाइपलाइन में हफ्तों से रिसाव हो रहा है, जिससे पानी बर्बाद हो रहा है जबकि हमारे नल सूखे पड़े हैं।",
"नगरपालिका द्वारा जारी जल आपूर्ति का समय-सारणी ज्यादातर दिनों में हमारे नल पर वास्तव में जो होता है उससे मेल नहीं खाती।",
"हमारे नल के पानी में आयरन की मात्रा ने महीनों से कपड़ों और बर्तनों पर दाग छोड़े हैं, जल विभाग की ओर से कोई स्पष्टीकरण नहीं आया।",
"हमारे मोहल्ले का इकलौता स्रोत, एक हाथ से खोदा गया कुआं, पिछले तूफान में मलबा गिरने के बाद अनुपयोगी हो गया है।",
"सूखे मौसम के लिए वादा किए गए वाटर कार्ट अभी तक तैनात नहीं किए गए हैं, हालांकि टैंकर रूट मैप में हमारे गांव का नाम दर्ज है।",
]

Hinglish = [
"Monday se hamare taps dry pade hain jabki pados ki gali mein tay time par paani aa raha hai.",
"Jo tanker hamari colony mein hafte mein do baar aata tha, woh das dinon se zyada time se nahi aaya.",
"Pichle kuch dinon se pipeline ka paani halka yellow dikh raha hai, phir bhi hum usi se khana bana rahe hain.",
"Community tap par pressure itna kam ho gaya hai ki ab ek bucket bharne mein lagbhag bees minute lag jaate hain.",
"Hamare mohalle ka borewell is saal hamesha se pehle sookh gaya hai.",
"Hamari gali ke aakhir mein base ghar walon ko mushkil se boond-boond paani milta hai jabki main road ke paas poora supply milta hai.",
"Hamare block ki overhead tank residents ke mutabik kam se kam teen saal se clean nahi hui hai.",
"Ab paani ki supply subah sirf chaalis minute ke liye aati hai, jabki pehle do ghante milte the.",
"Chhe mahine pehle submit kiye gaye new connection application ke bawajood abhi tak hamare ghar tak koi functioning pipeline nahi pahunchi hai.",
"Hamari basti ke kayi families jis kuen par depend karte hain, uska paani garmiyon se kaafi namkeen taste dene laga hai.",
"Hamare ward ke liye tay tankers reportedly ek pados ke zyada influential ilake mein divert kar diye gaye hain.",
"Main road ke paas pipeline teen hafte pehle phat gayi thi aur tab se paani ghar tak pahunchne ke bajaye behta ja raha hai.",
"Pichle mahine nazdeeki handpump kharab hone ke baad se hamare gaon mein drinking water ka koi reliable source nahi bacha.",
"Tap se aane wale paani mein ek hafte se saaf dikhne wala sediment hai, jo ubalne ke baad bhi nahi baithta.",
"Scheme ke tahat lagaya gaya public water point kabhi kisi functioning line se connect hi nahi hua.",
"Bina kisi notice ke summer supply ka time ghata diya gaya, aur ab elderly residents bartan bharne ke liye subah se pehle queue mein lagte hain.",
"Hamare coastal village mein lagayi gayi desalination unit mahinon se band padi hai, jisse humein phir se paani kharidna pad raha hai.",
"Hamare ilake ka paani kuch din chlorine ki tez smell deta hai aur kuch din bilkul odourless, treatment mein koi consistency nahi dikhti.",
"Nayi housing colony to bas gayi lekin pipeline network ko kabhi extra houses tak badhaya hi nahi gaya.",
"Hamari slum mein reportedly ek private tanker mafia paani ki access ko control karta hai, jo municipal supply ki cost se kahin zyada rate vasoolta hai.",
"Pipeline scheme beech mein atak jaane ke baad hamare hillside mohalle ko lagbhag do kilometer door ek spring se paani laana padta hai.",
"Metallic taste ki complaints ke baad jo water quality testing honi thi, woh kabhi hui hi nahi.",
"Hamare ward ke paanch mein se teen public handpumps ek saal se zyada time se kharab pade hain aur repair ka koi visit tay nahi hai.",
"Tap connection ka meter un dinon bhi chalta dikhta hai jab paani ka pressure mushkil se hamare ghar tak pahuncha hai.",
"Hamare gaon mein groundwater level itna gir gaya hai ki chalu borewells bhi ab din mein sirf ek ghante ke liye paani de rahe hain.",
"Hamari colony se guzarne wali municipal supply line roadwork ke dauran damage ho gayi thi aur tab se restore nahi hui.",
"Hamari gali ke kis hisse se paani bhara jaaye, uske hisaab se uska taste alag hota hai, jo kahin na kahin contamination ka signal deta hai.",
"Gir gaye borewell ki jagah naya borewell lagane ka hamara request panchayat mein aath mahine se pending hai.",
"Hamare shehar ko paani dene wala reservoir kam ho gaya hai aur rationing ka schedule bina prior announcement ke lagatar badalta rehta hai.",
"Colony ke purane hisse ke residents ab bhi ek hi shared standpipe par depend karte hain jo lagbhag chaalis households ko serve karta hai.",
"Treatment plant ke upgrade ke baad se hamare tap tak pahunchne wale paani mein ek ajeeb smell aa rahi hai jo pehle nahi thi.",
"Hamare route par assigned tanker driver hamari gali ko skip karke sirf main road ke households ko hi paani de raha hai.",
"Do saal pehle kiye gaye promises ke bawajood hamare village ke naye resettled hisse mein abhi tak koi water connection hi nahi hai.",
"Hamare aquifer ko recharge karne wala check dam kabhi complete nahi hua, aur aas-paas ke kuen har garmi mein jaldi sookhne lage hain.",
"Hamara school aur aas-paas ke ghar ek hi borewell share karte hain, jisne is mahine se intermittent supply deni shuru kar di hai.",
"Market ke paas underground pipeline mein hafton se leak ho raha hai, jisse paani waste ho raha hai jabki hamare taps sookhe pade hain.",
"Municipality dwara jaari water supply ka schedule zyadatar dinon mein hamare tap par actually jo hota hai usse match nahi karta.",
"Hamare tap ke paani mein iron content ne mahinon se kapdon aur bartano par daag chhode hain, water department ki taraf se koi explanation nahi aaya.",
"Hamare mohalle ka ikalauta source, ek haath se khoda gaya kuaan, pichle storm mein debris girne ke baad unusable ho gaya hai.",
"Sookhe mausam ke liye promise kiye gaye water carts abhi tak deploy nahi kiye gaye hain, halanki tanker route map mein hamare gaon ka naam darj hai.",
]
