# -*- coding: utf-8 -*-

English = [
"I submitted my income certificate application over two months ago and it still shows as under process on the portal.",
"The government office has not updated my land record despite three separate visits and all documents being in order.",
"My scholarship application was verified by the school weeks ago, but the department portal still shows it pending disbursement.",
"The tehsil office keeps asking for the same set of documents I have already submitted twice before.",
"My father's pension file has been stuck at the treasury office for four months with no clear reason given.",
"A caste certificate application filed in April has neither been approved nor rejected, just left without any status update.",
"The birth certificate for my daughter, born last year, still has not been issued despite repeated visits to the registrar's office.",
"We were told our ration card correction request would take two weeks, and it has now been over three months.",
"An official at the block office reportedly asked for an unofficial payment to process our domicile certificate faster.",
"My application for a duplicate driving licence has been stuck at the RTO for weeks without any update on the portal.",
"The death certificate for my grandfather was issued with a spelling error, and correcting it has taken over a month of visits.",
"Our family's Aadhaar update request, submitted to correct an address, has been pending processing for nearly two months.",
"The government scheme benefit approved on paper for my mother has still not been credited due to a mismatch in her bank details that no one has helped resolve.",
"An application for an income tax refund related to a government scheme has been stuck in verification for months.",
"The property mutation we applied for after my father's passing has been delayed at the revenue office without explanation.",
"My request to update my name on the electoral roll after marriage has been pending at the local office for over four months.",
"A government job application form was rejected weeks after submission for a formatting reason that was never mentioned as a requirement.",
"The passport application submitted through the local seva kendra has been stuck in police verification for far longer than the standard timeline.",
"Our society's registration renewal has been delayed at the registrar's office despite all fees being paid on time.",
"A widow pension application filed six months ago is still listed as pending at the block office with no update given to the applicant.",
"The certificate of encumbrance for our land was issued with an error, and getting it corrected has meant four separate visits so far.",
"An application to change the category listed in my ration card has been sitting unprocessed at the office for over three months.",
"The government office staff reportedly ask visitors to come back "next week" repeatedly without ever actually processing the file.",
"My income certificate renewal, needed for a scholarship deadline, has been delayed at the tehsildar's office beyond the promised timeline.",
"The domicile certificate portal shows my application as approved, but the physical copy has still not been issued after a month.",
"A land record correction requested after a survey error has been pending at the revenue department for nearly a year.",
"The RTI response to our query about pending certificates has itself been delayed well beyond the legally mandated period.",
"Our building's occupancy certificate application has been stuck at the municipal office for over five months with conflicting information from different clerks.",
"The government office responsible for verifying our OBC certificate has requested the same affidavit three separate times.",
"A retired employee's provident fund settlement has been delayed at the department office for over six months without explanation.",
"The marriage certificate we applied for after our court marriage has been delayed at the registrar's office for unclear reasons.",
"My application to transfer my ration card to our new address has been pending processing for over two months.",
"A government subsidy application approved in principle has not been disbursed because the department says the file is still "under review."
",
"The office handling disability certificate renewals asked us to resubmit medical documents that were already verified last year.",
"Our application for a No Objection Certificate needed for a bank loan has been delayed at the local office for weeks.",
"The staff at the district administrative office reportedly misplaced our original documents during a recent office relocation.",
"A senior citizen ID card application has been pending at the welfare office for over four months despite the applicant visiting personally each week.",
"The government office responsible for processing our compensation claim after a land acquisition has given no update in over six months.",
"My request to correct an error in my father's death record has bounced between two different offices for months.",
"The public grievance portal shows our complaint as "resolved" even though no officer has actually contacted us about it.",
]

Hindi = [
"मैंने अपना आय प्रमाण पत्र आवेदन दो महीने पहले जमा किया था और पोर्टल पर अभी भी वह प्रक्रियाधीन दिखा रहा है।",
"सरकारी कार्यालय ने तीन अलग-अलग यात्राओं और सभी दस्तावेज सही होने के बावजूद मेरा भूमि रिकॉर्ड अपडेट नहीं किया।",
"मेरी छात्रवृत्ति आवेदन को हफ्तों पहले स्कूल ने सत्यापित कर दिया था, लेकिन विभाग का पोर्टल अभी भी इसे वितरण के लिए लंबित दिखा रहा है।",
"तहसील कार्यालय बार-बार वही दस्तावेज मांग रहा है जो मैं पहले ही दो बार जमा कर चुका हूं।",
"मेरे पिता की पेंशन फाइल चार महीने से खजाना कार्यालय में अटकी हुई है, बिना किसी स्पष्ट कारण के।",
"अप्रैल में दाखिल किया गया जाति प्रमाण पत्र आवेदन न तो मंजूर हुआ है न ही खारिज, बिना किसी स्टेटस अपडेट के छोड़ दिया गया है।",
"पिछले साल जन्मी मेरी बेटी का जन्म प्रमाण पत्र रजिस्ट्रार कार्यालय के बार-बार दौरे के बावजूद अभी तक जारी नहीं हुआ।",
"हमें बताया गया था कि हमारा राशन कार्ड सुधार अनुरोध दो हफ्तों में हो जाएगा, और अब तीन महीने से ज्यादा हो चुके हैं।",
"ब्लॉक कार्यालय के एक अधिकारी ने कथित तौर पर हमारा डोमिसाइल प्रमाण पत्र जल्दी बनाने के लिए अनौपचारिक भुगतान मांगा।",
"डुप्लिकेट ड्राइविंग लाइसेंस के लिए मेरा आवेदन आरटीओ में हफ्तों से अटका हुआ है, पोर्टल पर कोई अपडेट नहीं है।",
"मेरे दादाजी का मृत्यु प्रमाण पत्र एक स्पेलिंग गलती के साथ जारी हुआ, और उसे सुधारने में एक महीने से ज्यादा की यात्राएं लग गईं।",
"पते को सुधारने के लिए जमा किया गया हमारे परिवार का आधार अपडेट अनुरोध लगभग दो महीने से प्रक्रिया में लंबित है।",
"मेरी मां के लिए कागज पर स्वीकृत सरकारी योजना का लाभ अभी तक जमा नहीं हुआ क्योंकि उनके बैंक विवरण में एक बेमेल है जिसे सुलझाने में किसी ने मदद नहीं की।",
"एक सरकारी योजना से संबंधित आयकर रिफंड के लिए आवेदन महीनों से सत्यापन में अटका हुआ है।",
"मेरे पिता के निधन के बाद हमने जो संपत्ति म्यूटेशन के लिए आवेदन किया, वह राजस्व कार्यालय में बिना किसी स्पष्टीकरण के देरी से चल रहा है।",
"शादी के बाद मतदाता सूची में अपना नाम अपडेट करने का मेरा अनुरोध स्थानीय कार्यालय में चार महीने से ज्यादा समय से लंबित है।",
"एक सरकारी नौकरी का आवेदन जमा करने के हफ्तों बाद एक फॉर्मेटिंग कारण से खारिज कर दिया गया जिसका कभी आवश्यकता के रूप में उल्लेख ही नहीं किया गया था।",
"स्थानीय सेवा केंद्र के जरिए जमा किया गया पासपोर्ट आवेदन पुलिस सत्यापन में मानक समय-सीमा से कहीं ज्यादा समय से अटका हुआ है।",
"हमारी सोसाइटी के पंजीकरण नवीनीकरण में रजिस्ट्रार कार्यालय में देरी हो रही है, हालांकि सारी फीस समय पर जमा कर दी गई थी।",
"छह महीने पहले दाखिल विधवा पेंशन आवेदन अभी भी ब्लॉक कार्यालय में लंबित सूचीबद्ध है, आवेदक को कोई अपडेट नहीं दिया गया।",
"हमारी जमीन के भार-मुक्ति प्रमाण पत्र में गलती के साथ जारी हुआ, और उसे सुधरवाने के लिए अब तक चार अलग-अलग यात्राएं करनी पड़ी हैं।",
"मेरे राशन कार्ड में सूचीबद्ध श्रेणी बदलने का आवेदन तीन महीने से ज्यादा समय से कार्यालय में अप्रसंस्कृत पड़ा है।",
"सरकारी कार्यालय का स्टाफ कथित तौर पर आगंतुकों से बार-बार अगले हफ्ते आने को कहता है, बिना फाइल को वास्तव में कभी प्रोसेस किए।",
"छात्रवृत्ति की समय-सीमा के लिए जरूरी मेरा आय प्रमाण पत्र नवीनीकरण तहसीलदार कार्यालय में वादा की गई समय-सीमा से आगे निकल गया है।",
"डोमिसाइल प्रमाण पत्र पोर्टल मेरे आवेदन को स्वीकृत दिखाता है, लेकिन एक महीने बाद भी भौतिक प्रति जारी नहीं हुई है।",
"सर्वेक्षण की गलती के बाद अनुरोधित भूमि रिकॉर्ड सुधार राजस्व विभाग में लगभग एक साल से लंबित है।",
"लंबित प्रमाण पत्रों के बारे में हमारी आरटीआई क्वेरी का जवाब खुद कानूनी रूप से तय अवधि से काफी आगे निकल गया है।",
"हमारी इमारत का अधिभोग प्रमाण पत्र आवेदन नगरपालिका कार्यालय में पांच महीने से ज्यादा समय से अटका हुआ है, विभिन्न क्लर्कों से परस्पर विरोधी जानकारी मिल रही है।",
"हमारे ओबीसी प्रमाण पत्र को सत्यापित करने के जिम्मेदार सरकारी कार्यालय ने वही हलफनामा तीन अलग-अलग बार मांगा है।",
"एक सेवानिवृत्त कर्मचारी का भविष्य निधि निपटान विभागीय कार्यालय में छह महीने से ज्यादा समय से बिना स्पष्टीकरण के देरी से चल रहा है।",
"कोर्ट मैरिज के बाद हमने जो विवाह प्रमाण पत्र के लिए आवेदन किया, वह रजिस्ट्रार कार्यालय में अस्पष्ट कारणों से देरी से चल रहा है।",
"मेरा राशन कार्ड नए पते पर स्थानांतरित करने का आवेदन दो महीने से ज्यादा समय से प्रक्रिया में लंबित है।",
"सैद्धांतिक रूप से स्वीकृत एक सरकारी सब्सिडी आवेदन वितरित नहीं किया गया क्योंकि विभाग का कहना है कि फाइल अभी भी 'समीक्षाधीन' है।",
"विकलांगता प्रमाण पत्र नवीनीकरण संभालने वाले कार्यालय ने हमसे उन मेडिकल दस्तावेजों को फिर से जमा करने को कहा जो पिछले साल ही सत्यापित हो चुके थे।",
"बैंक लोन के लिए जरूरी नो ऑब्जेक्शन सर्टिफिकेट के लिए हमारा आवेदन स्थानीय कार्यालय में हफ्तों से देरी से चल रहा है।",
"जिला प्रशासनिक कार्यालय के स्टाफ ने कथित तौर पर हाल की कार्यालय शिफ्टिंग के दौरान हमारे मूल दस्तावेज गुम कर दिए।",
"एक वरिष्ठ नागरिक पहचान पत्र आवेदन कल्याण कार्यालय में चार महीने से ज्यादा समय से लंबित है, हालांकि आवेदक हर हफ्ते व्यक्तिगत रूप से जाता है।",
"भूमि अधिग्रहण के बाद हमारे मुआवजे के दावे को संसाधित करने के लिए जिम्मेदार सरकारी कार्यालय ने छह महीने से ज्यादा समय में कोई अपडेट नहीं दिया।",
"मेरे पिता के मृत्यु रिकॉर्ड में गलती सुधारने का मेरा अनुरोध महीनों से दो अलग-अलग कार्यालयों के बीच घूम रहा है।",
"सार्वजनिक शिकायत पोर्टल हमारी शिकायत को 'हल' दिखाता है, हालांकि किसी अधिकारी ने वास्तव में इसके बारे में हमसे संपर्क ही नहीं किया।",
]

Hinglish = [
"Maine apna income certificate application do mahine pehle submit kiya tha aur portal par abhi bhi woh under-process dikha raha hai.",
"Sarkari office ne teen alag-alag visits aur saare documents sahi hone ke bawajood mera land record update nahi kiya.",
"Meri scholarship application ko hafton pehle school ne verify kar diya tha, lekin department ka portal abhi bhi ise disbursement ke liye pending dikha raha hai.",
"Tehsil office baar-baar wahi documents maang raha hai jo main pehle hi do baar submit kar chuka hoon.",
"Mere father ki pension file chaar mahine se treasury office mein atki hui hai, bina kisi clear reason ke.",
"April mein file kiya gaya caste certificate application na to approve hua hai na hi reject, bina kisi status update ke chhod diya gaya hai.",
"Pichle saal paida hui meri beti ka birth certificate registrar office ke baar-baar visits ke bawajood abhi tak issue nahi hua.",
"Humein bataya gaya tha ki hamara ration card correction request do hafton mein ho jaayega, aur ab teen mahine se zyada ho chuke hain.",
"Block office ke ek official ne reportedly hamara domicile certificate jaldi banane ke liye unofficial payment maanga.",
"Duplicate driving licence ke liye mera application RTO mein hafton se atka hua hai, portal par koi update nahi hai.",
"Mere dादाji ka death certificate ek spelling mistake ke saath issue hua, aur use correct karne mein ek mahine se zyada ki visits lag gayin.",
"Address correct karne ke liye submit kiya gaya hamare family ka Aadhaar update request lagbhag do mahine se process mein pending hai.",
"Meri maa ke liye paper par sanctioned sarkari scheme ka benefit abhi tak credit nahi hua kyunki unke bank details mein ek mismatch hai jise resolve karne mein kisi ne madad nahi ki.",
"Ek sarkari scheme se related income tax refund ke liye application mahinon se verification mein atka hua hai.",
"Mere father ke passing ke baad humne jo property mutation ke liye apply kiya, woh revenue office mein bina kisi explanation ke delay ho raha hai.",
"Shaadi ke baad electoral roll mein apna naam update karne ka mera request local office mein chaar mahine se zyada time se pending hai.",
"Ek sarkari job application submit karne ke hafton baad ek formatting reason se reject kar diya gaya jiska kabhi requirement ke taur par mention hi nahi kiya gaya tha.",
"Local seva kendra ke through submit kiya gaya passport application police verification mein standard timeline se kahin zyada time se atka hua hai.",
"Hamari society ka registration renewal registrar office mein delay ho raha hai, halanki saari fees time par jama ki gayi thi.",
"Chhe mahine pehle file ki gayi vidhwa pension application abhi bhi block office mein pending listed hai, applicant ko koi update nahi diya gaya.",
"Hamari zameen ka encumbrance certificate ek galti ke saath issue hua, aur use correct karwane ke liye ab tak chaar alag-alag visits karni padi hain.",
"Mere ration card mein listed category badalne ka application teen mahine se zyada time se office mein unprocessed pada hai.",
"Sarkari office ka staff reportedly visitors se baar-baar agle hafte aane ko kehta hai, bina file ko actually kabhi process kiye.",
"Scholarship deadline ke liye zaroori mera income certificate renewal tehsildar office mein promise ki gayi timeline se aage nikal gaya hai.",
"Domicile certificate portal mere application ko approved dikhata hai, lekin ek mahine baad bhi physical copy issue nahi hui hai.",
"Survey ki galti ke baad requested land record correction revenue department mein lagbhag ek saal se pending hai.",
"Pending certificates ke baare mein hamari RTI query ka response khud legally mandated period se kaafi aage nikal gaya hai.",
"Hamari building ka occupancy certificate application municipal office mein paanch mahine se zyada time se atka hua hai, alag-alag clerks se conflicting information mil rahi hai.",
"Hamare OBC certificate ko verify karne ke jimmedaar sarkari office ne wahi affidavit teen alag-alag baar maanga hai.",
"Ek retired employee ka provident fund settlement department office mein chhe mahine se zyada time se bina explanation ke delay ho raha hai.",
"Court marriage ke baad humne jo marriage certificate ke liye apply kiya, woh registrar office mein unclear reasons se delay ho raha hai.",
"Mera ration card naye address par transfer karne ka application do mahine se zyada time se process mein pending hai.",
"Principle mein sanctioned ek sarkari subsidy application disburse nahi hua kyunki department ka kehna hai ki file abhi bhi 'under review' hai.",
"Disability certificate renewals sambhalne wale office ne humse un medical documents ko phir se submit karne ko kaha jo pichle saal hi verify ho chuke the.",
"Bank loan ke liye zaroori No Objection Certificate ke liye hamara application local office mein hafton se delay ho raha hai.",
"District administrative office ke staff ne reportedly recent office relocation ke dauran hamare original documents misplace kar diye.",
"Ek senior citizen ID card application welfare office mein chaar mahine se zyada time se pending hai, halanki applicant har hafte personally jaata hai.",
"Land acquisition ke baad hamare compensation claim ko process karne ke jimmedaar sarkari office ne chhe mahine se zyada time mein koi update nahi diya.",
"Mere father ke death record mein galti correct karne ka mera request mahinon se do alag-alag offices ke beech ghoom raha hai.",
"Public grievance portal hamari complaint ko 'resolved' dikhata hai, halanki kisi officer ne actually iske baare mein humse contact hi nahi kiya.",
]
