# -*- coding: utf-8 -*-

English = [
"The entrance to our block development office has stairs only, and there is no alternative route for wheelchair users.",
"The railway station's foot overbridge has no working lift, so a mobility-impaired commuter has to be carried up by strangers each time.",
"None of the buses on our route are low-floor, so a wheelchair user in our colony cannot travel without help lifting the chair aboard.",
"The ramp built at the government hospital entrance is too steep for a wheelchair to climb without someone pushing from behind.",
"Our local bank branch has no tactile flooring or audio cues, making it very difficult for a visually impaired customer to navigate the queue.",
"The accessible toilet at the bus terminal has been used for storage, leaving no functional option for a wheelchair user.",
"A newly built government office has an accessible entrance marked on the map, but it remains permanently locked with no staff aware of the key.",
"The footpath ramps installed near the market are blocked by parked two-wheelers most of the day, forcing wheelchair users onto the road.",
"Our community hall has no ramp at all, so an elderly resident with a walker cannot attend the panchayat meetings held there.",
"The lift at the district court complex has been out of order for months, and litigants who use wheelchairs must be carried up the stairs.",
"Braille signage promised at the new post office was never installed, leaving visually impaired visitors with no way to identify counters.",
"The ramp at our school's main gate is there, but it ends in a step at the classroom door, making the last few metres impassable.",
"A hearing-impaired resident in our colony says the government office refuses to communicate in writing, insisting on verbal-only interaction.",
"The railway platform has no tactile guidance path, making it risky for visually impaired passengers to judge the edge.",
"Wheelchair users in our town cannot access the upper floor of the municipal office because the lift has been non-functional since last winter.",
"The accessible parking spot outside the hospital is regularly occupied by other vehicles with no enforcement to keep it clear.",
"A ramp exists at the panchayat office but is at such a steep angle that it is unusable without assistance.",
"The community health centre has no signage or announcement system for visually impaired patients waiting for their turn.",
"Our neighbourhood's only accessible crossing signal has stopped making its audio cue, leaving visually impaired pedestrians unsure when to cross.",
"The government college library has books on the upper floor with no lift access at all for students with mobility impairments.",
"A wheelchair ramp was built at the ration shop, but shelves and the counter itself remain too high to reach from a seated position.",
"The bus stop shelter bench is designed in a way that leaves no clear space for a wheelchair to park alongside it.",
"An elderly resident who uses a cane says the uneven, unrepaired footpath near her house makes daily walks to the market genuinely dangerous.",
"The examination centre allotted to a visually impaired student did not arrange a scribe despite the request being submitted well in advance.",
"Public toilets at the bus stand have no grab bars or wide doorways, making them unusable for wheelchair users.",
"The government office's token system relies entirely on a digital display board with no audio announcement for visually impaired visitors.",
"A newly constructed flyover has no tactile paving or ramps at the pedestrian crossing beneath it, cutting off an accessible route that existed before.",
"The community centre's accessible entrance is technically present but kept locked, with the regular staircase entrance being the only one actually used.",
"A resident using a wheelchair reports that the pension disbursement counter is on the first floor of a building with no lift.",
"The railway reservation counter has no lowered section, forcing wheelchair users to strain upward to communicate with the clerk.",
"An accessible toilet was built at the primary health centre, but the door is too narrow for a standard wheelchair to pass through.",
"The public library's ramp is blocked every evening by parked bicycles, leaving no way in for wheelchair users after work hours.",
"A deaf resident says the emergency alert system in our area relies solely on a loudspeaker announcement with no visual signal.",
"The panchayat office renovated its entrance last year but left out the accessible ramp that was part of the approved plan.",
"Wheelchair users attending the government college have to be carried across a broken section of pathway that has no alternate route.",
"The ATM nearest our colony is placed on a raised platform with no ramp, making it inaccessible without help.",
"A newly built overbridge near the market has stairs on both ends with no lift or ramp for those unable to climb them.",
"The block office's accessible washroom has been locked and used as a storeroom for the past several months.",
"An elderly wheelchair user in our ward says the community centre stage has no ramp, excluding her from participating in local events held there.",
"The government school built a ramp for one building but the adjoining block, which houses the library, still has only stairs.",
]

Hindi = [
"हमारे ब्लॉक डेवलपमेंट कार्यालय के प्रवेश द्वार पर केवल सीढ़ियां हैं, और व्हीलचेयर इस्तेमाल करने वालों के लिए कोई वैकल्पिक रास्ता नहीं है।",
"रेलवे स्टेशन के फुट ओवरब्रिज पर कोई काम करती लिफ्ट नहीं है, इसलिए एक गतिशीलता-बाधित यात्री को हर बार अजनबियों द्वारा ऊपर उठाना पड़ता है।",
"हमारे रूट की एक भी बस लो-फ्लोर नहीं है, इसलिए हमारी कॉलोनी के एक व्हीलचेयर उपयोगकर्ता बिना मदद के कुर्सी को बस में चढ़ाए बिना यात्रा नहीं कर सकते।",
"सरकारी अस्पताल के प्रवेश द्वार पर बना रैंप इतना खड़ी ढलान वाला है कि बिना पीछे से धकेले व्हीलचेजर चढ़ ही नहीं सकती।",
"हमारी स्थानीय बैंक शाखा में कोई स्पर्शनीय फर्श या ऑडियो संकेत नहीं है, जिससे एक दृष्टिबाधित ग्राहक के लिए कतार में चलना बहुत मुश्किल हो जाता है।",
"बस टर्मिनल का सुलभ शौचालय भंडारण के लिए इस्तेमाल किया जा रहा है, जिससे व्हीलचेयर उपयोगकर्ता के लिए कोई कार्यात्मक विकल्प नहीं बचा।",
"नए बने सरकारी कार्यालय में नक्शे पर एक सुलभ प्रवेश द्वार चिह्नित है, लेकिन वह हमेशा बंद रहता है और किसी स्टाफ को चाबी की जानकारी नहीं है।",
"बाजार के पास बनाए गए फुटपाथ रैंप ज्यादातर दिन खड़े दोपहिया वाहनों से अवरुद्ध रहते हैं, जिससे व्हीलचेयर उपयोगकर्ताओं को सड़क पर आना पड़ता है।",
"हमारे सामुदायिक भवन में कोई रैंप ही नहीं है, इसलिए वॉकर इस्तेमाल करने वाली एक बुजुर्ग निवासी वहां होने वाली पंचायत बैठकों में शामिल नहीं हो पातीं।",
"जिला अदालत परिसर की लिफ्ट महीनों से खराब है, और व्हीलचेयर इस्तेमाल करने वाले मुकदमेबाजों को सीढ़ियों से ऊपर उठाना पड़ता है।",
"नए डाकघर में वादा किया गया ब्रेल संकेत कभी नहीं लगाया गया, जिससे दृष्टिबाधित आगंतुकों के लिए काउंटर पहचानने का कोई तरीका नहीं बचा।",
"हमारे स्कूल के मुख्य गेट पर रैंप तो है, लेकिन वह कक्षा के दरवाजे पर एक सीढ़ी में खत्म होता है, जिससे आखिरी कुछ मीटर पार करना असंभव हो जाता है।",
"हमारी कॉलोनी की एक श्रवण-बाधित निवासी का कहना है कि सरकारी कार्यालय लिखित संवाद से इनकार करता है और केवल मौखिक बातचीत पर जोर देता है।",
"रेलवे प्लेटफॉर्म पर कोई स्पर्शनीय मार्गदर्शन पथ नहीं है, जिससे दृष्टिबाधित यात्रियों के लिए किनारे का अंदाजा लगाना जोखिम भरा हो जाता है।",
"हमारे शहर में व्हीलचेयर उपयोगकर्ता नगरपालिका कार्यालय की ऊपरी मंजिल तक नहीं पहुंच सकते क्योंकि लिफ्ट पिछली सर्दियों से खराब है।",
"अस्पताल के बाहर सुलभ पार्किंग स्थान पर नियमित रूप से अन्य वाहन खड़े रहते हैं और इसे खाली रखने के लिए कोई प्रवर्तन नहीं है।",
"पंचायत कार्यालय में एक रैंप मौजूद है लेकिन इतने खड़े कोण पर है कि बिना सहायता के इस्तेमाल करना असंभव है।",
"सामुदायिक स्वास्थ्य केंद्र में अपनी बारी का इंतजार कर रहे दृष्टिबाधित मरीजों के लिए कोई संकेत या घोषणा प्रणाली नहीं है।",
"हमारे मोहल्ले के इकलौते सुलभ क्रॉसिंग सिग्नल ने अपना ऑडियो संकेत देना बंद कर दिया है, जिससे दृष्टिबाधित पैदल यात्रियों को यह पता नहीं चलता कि कब पार करें।",
"सरकारी कॉलेज की लाइब्रेरी में किताबें ऊपरी मंजिल पर हैं, गतिशीलता-बाधित छात्रों के लिए वहां कोई लिफ्ट एक्सेस ही नहीं है।",
"राशन दुकान पर व्हीलचेयर रैंप बनाया गया, लेकिन शेल्फ और काउंटर खुद इतने ऊंचे हैं कि बैठी हुई स्थिति से पहुंचना मुश्किल है।",
"बस स्टॉप शेल्टर की बेंच इस तरह बनाई गई है कि व्हीलचेयर को उसके साथ खड़ा करने के लिए कोई साफ जगह ही नहीं बचती।",
"छड़ी इस्तेमाल करने वाली एक बुजुर्ग निवासी का कहना है कि उनके घर के पास ऊबड़-खाबड़, बिना मरम्मत वाला फुटपाथ बाजार तक रोजाना पैदल जाना वाकई खतरनाक बना देता है।",
"एक दृष्टिबाधित छात्र को आवंटित परीक्षा केंद्र ने पहले से जमा किए गए अनुरोध के बावजूद लेखक की व्यवस्था नहीं की।",
"बस स्टैंड के सार्वजनिक शौचालयों में कोई ग्रैब बार या चौड़े दरवाजे नहीं हैं, जिससे वे व्हीलचेयर उपयोगकर्ताओं के लिए इस्तेमाल के लायक नहीं रहते।",
"सरकारी कार्यालय की टोकन प्रणाली पूरी तरह से एक डिजिटल डिस्प्ले बोर्ड पर निर्भर है, दृष्टिबाधित आगंतुकों के लिए कोई ऑडियो घोषणा नहीं है।",
"नए बने फ्लाईओवर के नीचे पैदल क्रॉसिंग पर कोई स्पर्शनीय पेविंग या रैंप नहीं है, जिससे पहले मौजूद एक सुलभ रास्ता कट गया है।",
"सामुदायिक केंद्र का सुलभ प्रवेश द्वार तकनीकी रूप से मौजूद है लेकिन बंद रहता है, नियमित सीढ़ी वाला प्रवेश द्वार ही वास्तव में इस्तेमाल होता है।",
"व्हीलचेयर इस्तेमाल करने वाले एक निवासी का कहना है कि पेंशन वितरण काउंटर एक ऐसी इमारत की पहली मंजिल पर है जहां कोई लिफ्ट नहीं है।",
"रेलवे आरक्षण काउंटर पर कोई नीचा हिस्सा नहीं है, जिससे व्हीलचेयर उपयोगकर्ताओं को क्लर्क से बात करने के लिए ऊपर की ओर खिंचना पड़ता है।",
"प्राथमिक स्वास्थ्य केंद्र में एक सुलभ शौचालय बनाया गया, लेकिन दरवाजा इतना संकरा है कि एक मानक व्हीलचेयर उसमें से गुजर ही नहीं सकती।",
"सार्वजनिक लाइब्रेरी का रैंप हर शाम खड़ी साइकिलों से अवरुद्ध रहता है, जिससे काम के घंटों के बाद व्हीलचेयर उपयोगकर्ताओं के लिए कोई रास्ता नहीं बचता।",
"एक बधिर निवासी का कहना है कि हमारे इलाके की आपातकालीन चेतावनी प्रणाली पूरी तरह से लाउडस्पीकर घोषणा पर निर्भर है, कोई दृश्य संकेत नहीं है।",
"पंचायत कार्यालय ने पिछले साल अपने प्रवेश द्वार का नवीनीकरण किया लेकिन स्वीकृत योजना का हिस्सा रहा सुलभ रैंप छोड़ दिया।",
"सरकारी कॉलेज में आने वाले व्हीलचेयर उपयोगकर्ताओं को रास्ते के एक टूटे हुए हिस्से से होकर उठाकर ले जाना पड़ता है जिसका कोई वैकल्पिक मार्ग नहीं है।",
"हमारी कॉलोनी के सबसे नजदीक का एटीएम एक ऊंचे प्लेटफॉर्म पर लगा है, बिना रैंप के, जिससे बिना मदद के वहां पहुंचना असंभव है।",
"बाजार के पास नया बना ओवरब्रिज दोनों सिरों पर सीढ़ियों वाला है, जिन्हें चढ़ न पाने वालों के लिए कोई लिफ्ट या रैंप नहीं है।",
"ब्लॉक कार्यालय का सुलभ वॉशरूम पिछले कई महीनों से बंद है और स्टोररूम के रूप में इस्तेमाल हो रहा है।",
"हमारे वार्ड की एक बुजुर्ग व्हीलचेयर उपयोगकर्ता का कहना है कि सामुदायिक केंद्र के मंच पर कोई रैंप नहीं है, जिससे वह वहां आयोजित स्थानीय कार्यक्रमों में भाग नहीं ले पातीं।",
"सरकारी स्कूल ने एक इमारत के लिए रैंप बनाया लेकिन साथ वाले ब्लॉक में, जहां लाइब्रेरी है, अभी भी केवल सीढ़ियां हैं।",
]

Hinglish = [
"Hamare block development office ke entrance par sirf stairs hain, aur wheelchair users ke liye koi alternative route nahi hai.",
"Railway station ke foot overbridge par koi working lift nahi hai, isliye ek mobility-impaired commuter ko har baar strangers dwara upar uthana padta hai.",
"Hamare route ki ek bhi bus low-floor nahi hai, isliye hamari colony ke ek wheelchair user bina help ke chair ko bus mein chadha nahi sakte.",
"Sarkari hospital ke entrance par bana ramp itna steep hai ki bina peeche se push kiye wheelchair chadh hi nahi sakti.",
"Hamari local bank branch mein koi tactile flooring ya audio cue nahi hai, jisse ek visually impaired customer ke liye queue mein chalna bahut mushkil ho jaata hai.",
"Bus terminal ka accessible toilet storage ke liye use ho raha hai, jisse wheelchair user ke liye koi functional option nahi bacha.",
"Naye bane sarkari office mein map par ek accessible entrance marked hai, lekin woh hamesha locked rehta hai aur kisi staff ko key ki jaankari nahi hai.",
"Market ke paas banaye gaye footpath ramps zyadatar din khade two-wheelers se blocked rehte hain, jisse wheelchair users ko road par aana padta hai.",
"Hamare community hall mein koi ramp hi nahi hai, isliye walker use karne wali ek elderly resident wahan hone wali panchayat meetings mein shaamil nahi ho paatin.",
"District court complex ki lift mahinon se kharab hai, aur wheelchair use karne wale litigants ko stairs se upar uthana padta hai.",
"Naye post office mein promise ki gayi braille signage kabhi nahi lagayi gayi, jisse visually impaired visitors ke liye counters identify karne ka koi tarika nahi bacha.",
"Hamare school ke main gate par ramp to hai, lekin woh classroom ke darwaze par ek step mein khatam hota hai, jisse aakhri kuch metre paar karna asambhav ho jaata hai.",
"Hamari colony ki ek hearing-impaired resident ka kehna hai ki sarkari office likhit communication se inkaar karta hai aur sirf verbal interaction par zor deta hai.",
"Railway platform par koi tactile guidance path nahi hai, jisse visually impaired passengers ke liye edge ka andaza lagana risky ho jaata hai.",
"Hamare town mein wheelchair users municipal office ki upper floor tak nahi pahunch sakte kyunki lift pichli sardi se kharab hai.",
"Hospital ke bahar accessible parking spot par regularly doosre vehicles khade rehte hain aur ise khaali rakhne ke liye koi enforcement nahi hai.",
"Panchayat office mein ek ramp maujood hai lekin itne steep angle par hai ki bina assistance ke use karna asambhav hai.",
"Community health centre mein apni baari ka wait kar rahe visually impaired patients ke liye koi signage ya announcement system nahi hai.",
"Hamare mohalle ke ikalauta accessible crossing signal ne apna audio cue dena band kar diya hai, jisse visually impaired pedestrians ko pata nahi chalta ki kab cross karein.",
"Sarkari college ki library mein books upper floor par hain, mobility-impaired students ke liye wahan koi lift access hi nahi hai.",
"Ration shop par wheelchair ramp banaya gaya, lekin shelves aur counter khud itne high hain ki baithi hui position se pahunchna mushkil hai.",
"Bus stop shelter ki bench is tarah banayi gayi hai ki wheelchair ko uske saath khada karne ke liye koi clear jagah hi nahi bachti.",
"Cane use karne wali ek elderly resident ka kehna hai ki unke ghar ke paas uneven, unrepaired footpath market tak roz paidal jaana genuinely dangerous bana deta hai.",
"Ek visually impaired student ko allot kiye gaye exam centre ne pehle se submit kiye gaye request ke bawajood scribe ki arrangement nahi ki.",
"Bus stand ke public toilets mein koi grab bars ya wide doorways nahi hain, jisse woh wheelchair users ke liye use ke layak nahi rehte.",
"Sarkari office ka token system poori tarah ek digital display board par depend karta hai, visually impaired visitors ke liye koi audio announcement nahi hai.",
"Naye construct hue flyover ke neeche pedestrian crossing par koi tactile paving ya ramps nahi hain, jisse pehle maujood ek accessible route cut ho gaya hai.",
"Community centre ka accessible entrance technically maujood hai lekin locked rehta hai, regular staircase entrance hi actually use hota hai.",
"Wheelchair use karne wale ek resident ka kehna hai ki pension disbursement counter ek aisi building ki first floor par hai jahan koi lift nahi hai.",
"Railway reservation counter par koi lowered section nahi hai, jisse wheelchair users ko clerk se baat karne ke liye upar ki taraf khinchna padta hai.",
"Primary health centre mein ek accessible toilet banaya gaya, lekin door itna narrow hai ki ek standard wheelchair usse guzar hi nahi sakti.",
"Public library ka ramp har shaam khadi bicycles se blocked rehta hai, jisse work hours ke baad wheelchair users ke liye koi rasta nahi bachta.",
"Ek deaf resident ka kehna hai ki hamare ilake ka emergency alert system poori tarah loudspeaker announcement par depend karta hai, koi visual signal nahi hai.",
"Panchayat office ne pichle saal apne entrance ka renovation kiya lekin approved plan ka hissa raha accessible ramp chhod diya.",
"Sarkari college mein aane wale wheelchair users ko path ke ek tooti hui section se hokar utha kar le jaana padta hai jiska koi alternate route nahi hai.",
"Hamari colony ke sabse nazdeek ka ATM ek raised platform par laga hai, bina ramp ke, jisse bina help ke wahan pahunchna asambhav hai.",
"Market ke paas naya bana overbridge dono ends par stairs wala hai, jinhe chadh na paane walon ke liye koi lift ya ramp nahi hai.",
"Block office ka accessible washroom pichle kayi mahinon se locked hai aur storeroom ki tarah use ho raha hai.",
"Hamare ward ki ek elderly wheelchair user ka kehna hai ki community centre ke stage par koi ramp nahi hai, jisse woh wahan hone wale local events mein participate nahi kar paatin.",
"Sarkari school ne ek building ke liye ramp banaya lekin saath wale block mein, jahan library hai, abhi bhi sirf stairs hain.",
]
